### ISSUE TITLE
numerical integration strategy

### ISSUE THREAD

**Issue by samira-m94** [jonathf/chaospy#101]
I don't know how to specify which numerical integration I want to use in the code. don't know the key words. and on the other hand in part 4.3 of the paper it gives an example of using 'Gaussian' as a rule in generating quadrature but it is not working when using the same argument in the package and giving me error.

**Comment by jonathf** [comment]
So, the `rule="G"` means Gaussian-Quadrature. Though hidden a little bit, you can find the list of algorithms listed by running `help(chaospy.quad.frontend)`. You can use the flag together with the `generate_quadrature` function.

As to why your code fails, that is hard to tell from what you have provided. Please post the following and I will take a look:
* A tiny script that reproduces the error.
* A few words about the behavior you would imagine the script should produce
* The actual output of running said script
* Your operating system used during execution
* The version of Python used during execution (`python --version`)
* Which version of chaospy is installed (`pip freeze`)

**Comment by samira-m94** [comment]
Thanks for your response I tried "G" and the code ran fine, and actually found the list of algorithms, too.

Other question is that whenever I use a different distribution do I have to change the quadrature with respect to the distribution? i.e. Hermite for Normal, Legendre for Uniform, or Laguerre for exponential or is there a transformation for that in the algorithm itself? since Gaussian quadrature needs a weight function it could be different for various distributions. So, Generally, What I am asking is that in Gaussian quadrature algorithm does it set the weight function with respect to the given distribution?

**Comment by jonathf** [comment]
The underlying algorithm for Gaussian quadrature is Golub-Weslch which is individually calculated for each distribution (or cheat a little if possible). In other words, if you provide `Normal(0, 1)` it is Hermite, `Uniform(-1, 1)` it is Legendre, etc.

So to answer your question: Yes chaospy sets both the nodes and weights with respect to each distribution.

**Comment by samira-m94** [comment]
And my last question is that what do you exactly mean by the "order" argument in "generate_quadrature" function. Unfortunately there is no part on the documentation talking about it. am asking this since normally in quadrature we specify the number of nodes that we want but here by changing order from 9 to higher numbers the number of abscissas does not match with the number we have already given. 
for example according to the distribution we have, the number of  abscissa does not appear to be m+1 (as m is the order). for log-normal distribution(miu = 1.5, sigma=0.37) with 3 inputs number of abscissa for order = 5 is not 216 instead it is 213! and as I change the parameters for my distribution same thing happens in different orders.(I use "G" as my rule)

sorry if it is basic but I have checked the documentation and even the paper you have cited but still couldn't find my answer. and in the code it says that number of abscissa must be m+1 for order = m but I am not getting that as run my code.

**Comment by samira-m94** [comment]
I am using this package on python 3.6 and I have installed Chaospy with pip.
I used exactly the code you have mentioned in the previous response but still I am not getting 216 nodes, instead I got 212 and this is happening only with Log-normal distribution I tried it for Normal it gave me 216 which is correct
