### ISSUE TITLE
How can I predict a new distribution using 'foo_approx'?

### ISSUE THREAD

**Issue by TribleCircle** [jonathf/chaospy#102]
Dear Jonathan:
I've been recently using your fantastic toolbox `chaospy` and gained some satisfying results following your guide. But I have a problem and hope that you can help me.
I typed these codes:
```
dist1 = cp.Normal(0, 0.0009)
dist2 = cp.Normal(0, 0.0009)
dist3 = cp.Normal(0, 0.0009)
dist4 = cp.Normal(0, 0.0009)
dist = cp.J(dist1, dist2, dist3, dist4)

P = cp.orth_ttr(3, dist)

nodes, weights = cp.generate_quadrature(3, dist, rule = 'G')
#nodes *= 0.03
np.savetxt('intsites_G.txt', nodes.T)

# Matlab needed for evaluating the response

resp = np.loadtxt('resp_gauss.txt')
respHat = cp.fit_quadrature(P, nodes, weights, resp)
```
I see that `respHat` is a `Poly` object:
```
>>> respHat
>>> <chaospy.poly.base.Poly at 0x28db0fe9940>
```
So now I'm wondering if I can make some prediction with a set of new samples using this `respHat` result? Like say, I have 500 new samples, and I want to know what their responses look like.
Thank you if you can spend some time helping me with this!

Yours
Dean

**Comment by jonathf** [comment]
I am glad you enjoy it.

Yes, making evaluations should be quite straight forward. Just run:
```
evaluations = respHat(*new_samples)
```
Here I assume `new_samples` is a `numpy.ndarray` and `len(new_samples) == input_dim`.

Hope this helps.

**Comment by TribleCircle** [comment]
Yes, that worked!
Appreciate that a lot!

**Comment by jonathf** [comment]
Glad to be of service. :)
