### ISSUE TITLE
Inconsistent behavior when sampling with rule = 'S'

### ISSUE THREAD

**Issue by CDNoyes** [jonathf/chaospy#105]
The behavior of sampling is different when using `rule='S'` than with all other rules. Here is a quick comparison with random sampling
```
import chaospy as cp

d = cp.Uniform(0,1)

for rule in ['R','S']:
    print(rule)
    print(d.sample(5, rule).shape)
    print(d.sample((5,10), rule).shape)
```
yields
```
R
(5,)
(5, 10)
S
(6,)
(51,)
```

In the scalar case, the Sobol output is one sample too many. In two or more dimensions, the output is flattened with Sobol but not with any other rule. 

Using chaospy 2.3.3, python 3.6.4.

**Comment by jonathf** [comment]
This kind of behavior to a certain degree is expected as the quadrature rules are available as sampling schemes. But the scheme in question is Sobol if I remember correctly, which is a pure sampler.

I'll take a look and make fix.

**Comment by jonathf** [comment]
Okay, I have gotten around to it now.

I've pushed version 2.3.5 to Pypi now and it should pop up any second for you to test out. Let me know if it works as expected.

**Comment by CDNoyes** [comment]
Looks like it works perfectly, thanks for the quick fix.
