### ISSUE TITLE
Residue

### ISSUE THREAD

**Issue by marcrocasalonso** [jonathf/chaospy#109]
Dear Jonathan,

I want to evaluate de residual in Point Collocation Polynomial Chaos. Chaospy have some function to known the orthogonal base matrix? I want to do this operation:

Base Matrix * Fourier Coefficients - Evaluations = Residual

Thanks in advance,

Marc

**Comment by jonathf** [comment]
You something along the line of this?
```
base_matrix = orthogonal_polynomials(*abscissas)
```
You might want to look at the shapes of the Fourier coefficients and base matrix shapes to figure out which ones need transposing for your residual calculation.

**Comment by jonathf** [comment]
Oh, right, there is also a hidden option in the code:
```
approx_model, fourier_coeffs, base_matrix = cp.fit_regression(..., retall=2)
```

**Comment by marcrocasalonso** [comment]
Thanks you Jonathan! :)
