### ISSUE TITLE
Memory error while calculating PCE based standard deviation  

### ISSUE THREAD

**Issue by flapingwings** [jonathf/chaospy#119]
Hi Jonathan,

Using chaospy, I have obtained PCE approximation for stochastic response of a mechanical structure.

The problem at hand has 225 random variables with known PDFs for each of them. 

The full PCE of order 2 will have 25651 terms and I evaluate the unknown coefficients using least-square regression. I use both the function values and gradients with respect to each of the 225 random variables to estimate the coefficients in PCE.

However, when I try to obtain the standard deviation from the pce approximation using the command chaospy.Std(model_approx, dist) , I run into Memory Error.

The error points to line 115, in chaospy/descriptives/second1d.py,
keys2 = np.empty((dim,N,N))

Could you please point me to any work around for this issue? 
I understand that once we obtain pce approximation, the statistical moments are analytically evaluated, so I hope there could be a possible way around this issue.

I tried to use truncated PCE which will reduce the terms in the expansion to around 450, but then the standard deviation does not compare well with that obtained using Monte Carlo method.

Many thanks for you time.

Regards,
Rahul

**Comment by jonathf** [comment]
Assuming that your random variables are stochastically independent and you are using `orth_ttr` to generate your polynomials, there is a shortcut to evaluate mean, variance and standard deviation from the Fourier coefficients directly. Something like:
```
approx_model, coeffs = cp.fit_regression(..., retall=True)
mean = coeffs[0]
variance = sum(coeffs[1:]**2)
standard_deviation = numpy.sqrt(variance)
```
Let me know if this works or not.

**Comment by jonathf** [comment]
No, the equivalence is general, but my expression was a bit off.

Here is general proof. Start with orthogonality asumptions:
* All orthogonal polynomials uphold: `<P_i, P_j> = E[ P_i P_j ] = 0` for all `i != j`.
* `P_0 = 1`

The expected value of the polynomial approximation `u` has the form:
```
E[ u ] =
E[ \sum_{i=0}^N c_i P_i ] =
\sum_{i=0}^N c_i E[ P_i ] =
\sum_{i=0}^N c_i E[ P_i P_0 ] = c_0
```

For the variance, the math get a bit more messy:
```
E[ u^2 ] =
E[ \sum_i \sum_j c_i c_j P_i P_j ] =
\sum_i \sum_j c_i c_j E[ P_i P_j ] =
\sum_i c_i^2 E[ P_i^2 ]

Var(u) = E[ u^2 ] - E[ u ]^2 =
\sum_{i=1}^N c_i^2 E[ P_i^2 ]
```

So the expression above to hold, you also need orthonormal polynomials:
```python
orthogonal_polynomials = chaospy.orth_ttr(..., normed=True)
```
This normalizes the polynomials such that `E[ P_i^2 ] = 1`, which means the the expression above holds.

Alternative, you can extract the norms:
```python
orthogonal_polynomials, norms = chaospy.orth_ttr(..., retall=True)
...
variance = sum(coeffs[1:]**2*norms[1:])
```

**Comment by flapingwings** [comment]
Thanks for taking the time to explain in detail.
