### ISSUE TITLE
How to get the general function relation between the unknown parameter and the observed data?

### ISSUE THREAD

**Issue by nguyenhoaiThanhbk2811** [jonathf/chaospy#121]
Hi you,
Could you helps me this problem? I have the data of the parameter from this data I get the output through the experiment. and then I have used the chaospy to consider the distribution of output. (Non-intrusive point collocation method) I have mean and the standard deviation. How to can I consider the function relative between parameter and output?
Thank you

**Comment by nguyenhoaiThanhbk2811** [comment]
This is my detail code:
`import chaospy as cp
import numpy as np
import pandas as pd
from pandas import ExcelFile
import matplotlib.pyplot as plt

df = pd.read_excel('dulieu.xlsx',sheet_name = 'Sheet6')

#print (df)
nodes1 = np.array(df['Ca2'])
nodes2 = np.array(df['Ce1'])
nodes3 = np.array(df['Ce2'])


distribution = cp.J(cp.Uniform(0.054, 0.066), cp.Uniform(0.9, 1.1), cp.Uniform( 45, 55))

nodes = np.vstack([nodes1, nodes2, nodes3])
# output value
evals = np.array(df['Cl'])

polynomial_expansion = cp.orth_ttr(2, distribution)
approx = cp.fit_regression(polynomial_expansion, nodes, evals)
expected = cp.E( approx, distribution)
variance = cp.Var(approx, distribution)
deviation = cp.Std( approx, distribution)

sobol_t = cp.Sens_t(approx,distribution)


print (sobol_t)


print (expected)

print(deviation)

samples = distribution.sample(10000,"L")

evaluations = approx(*samples)

plt.hist(evaluations,bins = 80, rwidth =1, color = 'b',edgecolor='K')
plt.xlim (1.37,1.45)
plt.ylim(0,2500)
plt.xlabel ('CL',fontsize=14)
plt.ylabel ('Numbers',fontsize=14)
plt.title ('Order 2',fontsize =20)
plt.show()`
when I run the code I have the distribution of Cl and the mean and standard deviation. what kind of distribution of Cl? and How can find the relative function between (nodes1, nodes2,nodes3) and Cl?
Thanks you

**Comment by jonathf** [comment]
I am sorry. By example I mean can you give me an example of the operator "relative function" in practice, not the problem context of where you want to use it.
More concrete, do you have an journal article or preferably a Wikipedia article that demonstrate the functionality that you are looking for?
