### ISSUE TITLE
join list of distributions

### ISSUE THREAD

**Issue by meyerfn** [jonathf/chaospy#123]
Hi,

is it possible to join a list of of distributions? 

jointDistribution=[]
for idxLevel,level in self.levels.items():
   for idxDist,dist in self.stochvar.items():
       if(dist['distribution']=="uniform"):
          jointDistribution.append(cp.Uniform(dist[dist['distribution']][0],dist[dist['distribution']][1]))
       elif(dist['distribution']=="normal"):
          jointDistribution.append(cp.Normal(dist[dist['distribution']][0],dist[dist['distribution']][1]))

jointDist = cp.J(jointDistribution)

Thank you,
Fabian

**Comment by jonathf** [comment]
try:
```
jointDist = cp.J(*jointDistribution)
```

**Comment by meyerfn** [comment]
Works like a charm, thanks!
