### ISSUE TITLE
chaospy.seed()

### ISSUE THREAD

**Issue by gaborxlaszlo** [jonathf/chaospy#124]
chaospy.seed doesn't seem to work anymore

**Comment by jonathf** [comment]
The seed is no longer needed for the most part. Setting `numpy.seed` should be enough.

Only exception is currently Sobol indices. I'll link it up to the numpy seed soon. In the mean time, you can use the function:
```
from chaospy.distribution.sampler.sequence.sobol import set_state
```

**Comment by jonathf** [comment]
Issue solved in current master
