### ISSUE TITLE
How to print the estimating function to computer language?

### ISSUE THREAD

**Issue by nguyenhoaiThanhbk2811** [jonathf/chaospy#125]
Hi you,
Now, I am using chaospy to estimate function by non-instructive point collocation method.
I want to use the estimating function to apply to Bayesian.
when I print the function. It is a kind of text not computer language.
example:
y = -5q0+2q0q1+q2^2 (it is a text)
how to change the function to like that:
y =-5*q0+2*q0*q1+q2**2
thanks you

**Comment by jonathf** [comment]
```
chaospy.poly.base.POWER = "**"
chaospy.poly.base.SEP = "*"
```
There is also `chaospy.poly.base.VARNAME` which you can use to change the `q` name with something else.
