### ISSUE TITLE
Quadrature weights incorrect when dist fed in

### ISSUE THREAD

**Issue by jennirinker** [jonathf/chaospy#132]
Not sure if this is a bug or a feature, maybe someone can shed light on this.

The quadrature weights don't seem to be scaled correctly when we feed in a chaospy distribution with non-standard boundaries. For example,
```
X, W = chaospy.generate_quadrature(1, chaospy.Uniform(-1, 1), rule="G")
print(W)
```
produces the correct abscissa (+/- 0.57735), but the weights are off by a factor of 2 (0.5 instead of 1). Any ideas as to why this behavior occurs?

**Comment by jonathf** [comment]
Yes, this is intensional behavior.

Gaussian Quadrature is designed to calculate integrals on the form:

    \int w(x) f(x) dx

by approximation:

    \sum W_i f(X_i)

In other words, for each weight function `w(x)`, we get a collection of `W_i, X_i` pairs.

The assumption you are making is that `w(x)` equals to 1 on the `[-1, 1]` interval, as commonly defined in the literature. However, as this is probability theory `w(x)` is represents a probability density function. As such, it can not have that form, as it is not the the density function of `chaospy.Uniform(-1, 1)`, nor a valid density function at all for that matter.

The `w(x)` in your example is instead equal to `1/2` on the interval `[-1, 1]`. This is what you are observing here.

The good news is that the difference between the canonical weight functions in the Askey-Wilson scheme is usually just a scaling constant away from the probability equivalent. Just figure out what constant `w(x)` has to be multiplied with to get what you want, and multiply that constant to each `W_i`. In your case, that is 2.

**Comment by jennirinker** [comment]
Ah, of course. Makes sense. Thanks for the quick response, I'll mark this as closed.
