### ISSUE TITLE
 PCE with truncation

### ISSUE THREAD

**Issue by ysd03** [jonathf/chaospy#135]
Hi Jonathan, 

I am trying yo use chaospy with experimental data set which has 8 input random inputs and one output. I need to construct PCE with Legendre polynomials and use some truncation (q-norm or hyperbolic).

First question is how to use my inputs in chaospy?

dataPoints = dist.sample(noSamples) needs to replaced with my data? I imported cvs file as data frame using pandas.

After that how to construct PCE and use hyperbolic truncation?

Thanks,

**Comment by jonathf** [comment]
If you have experimental data in the forms of some `X`s and `Y`s, you can use them directly with the `chaospy.fit_regression` function. Only requirement is that `X.shape == (len(distribution), len(Y))`.

If you want Legendre polynomials, then your distribution needs to be Uniform: `chaospy.Iid(chaospy.Uniform(-1, 1), 8)`. You won't use it to create samples, but it is required to get the Legendre polynomials through the `chaospy.orth_ttr` function. By passing a value to `cross_truncation` to the same function you get hyperbolic truncation.

Hope this helps.

**Comment by ysd03** [comment]
Thanks Jonathan.
I was able to use chaospy.fit_regression function and got some results. cross_truncation worked also.
Is there a way to evaluate how good the polynomial model is?

**Comment by jonathf** [comment]
That is a more difficult question to answer. There are some theory on error bounds, but it is more theoretical in nature as it depend on knowing some smoothness properties about the model that goes way beyond what is reasonable in practice.

In journal articles it is, typical to make a compare against the analytical truth, or using Monte Carlo with a extremely large N as a reference.

If you move over to the situation like yours where you only have samples, you best bet is to run cross-validation. Split samples randomly into folds; use all but one fold to train; do prediction on the last fold; compare the true values and the predicted value using a fitting metric of choice.

**Comment by ysd03** [comment]
I ended up using 10 fold cross validation as you guessed. Seeing good correlation with model and the data so far. Thanks for all help!

**Comment by jonathf** [comment]
You're welcome. :)
