### ISSUE TITLE
please explain for me the tutorial 4!!!

### ISSUE THREAD

**Issue by nguyenhoaiThanhbk2811** [jonathf/chaospy#137]
Hi you,
now I am reading the tutorial 4 in your material. I don't understand a problem in tutorial 4.
your documentation say that "All random variables can with aid of the Rosenblatt transformations be transformed to/from the uniform distribution" what is this mean? please give me a example simplicity.
thank you.

**Comment by jonathf** [comment]
Somthing like this?
https://en.wikipedia.org/wiki/Inverse_transform_sampling

**Comment by nguyenhoaiThanhbk2811** [comment]
Hi You,
this is my code:

```
import chaospy as cp
import numpy as np
import matplotlib.pyplot as plt


nodes2 = np.array([1.09642867,0.91106599,1.06070764,0.96805655,0.93692189,1.01983507])



distribution = cp.Uniform(0.9, 1.1)


evals = np.array([0.0207243,0.0205043,0.0206821,0.0204284,0.0204355,0.0206363])
#

polynomial_expansion = cp.orth_ttr(2, distribution)
approx = cp.fit_regression(polynomial_expansion, nodes2, evals,rule = "LS")
expected = cp.E( approx, distribution)
variance = cp.Var(approx, distribution)
deviation = cp.Std( approx, distribution)


samples = distribution.sample(10000, "L")
samples.shape = (1, len(samples))    # chuyen vec to thanh ma tran
evaluations = approx(*samples)        # thế giá trị vô hàm


plt.hist(evaluations,bins = 100, rwidth =1, color = 'b',edgecolor ='k')

plt.show()
```
when I run my code I plot the distribution of "evaluations".  beside that what things We can get from this code?

**Comment by jonathf** [comment]
Something like `distribution.fwd(nodes2)`?

Or were you thinking of `èvals`? In the latter case it is not as easy as we do not have the Rosenblatt transformation available.

**Comment by nguyenhoaiThanhbk2811** [comment]
when I run the `distribution.fwd(nodes2)`  code.
It have a result: `[0.98214335 0.05532995 0.8035382 0.34028275 0.178460945 0.59917535]`
what does this result mean?
initially, I have values of **nodes2** that I get it from random sampling distribution (cp.Uniform (0.9,1.1)).

**Comment by jonathf** [comment]
If `nodes2` are assumed to be randomly distributed from `Uniform(0.9, 1.1)`, than `distribution.fwd(nodes2)` can be assumed to be randomly distributed from `Uniform(0, 1)`.

**Comment by nguyenhoaiThanhbk2811** [comment]
I mean in my code the `nodes2` have distribution from Uniform (0.9,1.1), so after running the code how to consider the kind of `nodes2's` distribution (Uniform, Normal, or ...). it mean the initially it is a Unifrom Distribution. How to transfer to Normal distribution for nodes2?

**Comment by jonathf** [comment]
If you want to map from `Uniform(0.9, 1.1)` to `Normal(0, 1)`, do the following:
```python
dist1 = cp.Uniform(0.9, 1.1)
dist2 = cp.Normal(0, 1)
print(dist2.inv(dist1.fwd(nodes2)))
```
