### ISSUE TITLE
scipy.misc.comb no longer works with scipy v1.3.0

### ISSUE THREAD

**Issue by MatthewFlamm** [jonathf/chaospy#140]
`scipy.misc.comb` has been deprecated for several releases now, but is now completely dropped.  chaospy cannot be used with scipy v1.3.0 because of this.  The new function is `scipy.special.comb`.  The `special.comb` function doesn't exist in versions prior to scipy v0.14 as well.

**Comment by jonathf** [comment]
Solved on master now.
