### ISSUE TITLE
Mean of non-integral power of polynomials

### ISSUE THREAD

**Issue by jigarparekh279** [jonathf/chaospy#142]
I tried to find the mean of non-integral power of polynomials using -
cp.E( poly[i] * poly[j] * ( poly[k] ** (1/2) ), distr ) 

and I ran into the following error message -
ValueError: Power of Poly must be interger

Is it somehow possible to do such operations on the polynomial before taking the expected value with respect to the distribution (distr)?

It would be great if you could help.

**Comment by jonathf** [comment]
The polynomial objects does not support non-integer exponents, as the result is likely not an polynomial. Getting direct support for such operators isn't really feasible, as the majority of the chaospy library assumes polynomials as input everywhere.

That being said, chaospy does provide everything you need to create good approximation for such an evaluation. E.g. with quadrature integration:
```python
x, w = chaospy.generate_quadrature(order, distr, rule=rule)
evals = poly[i](*x)*poly[j](*x)*poly[k](*x)**(1/2)
custom_expected_value = chaospy.sum(evals*w, -1)
```
Here `rule, order` are parameters that should be chosen dependent on `distr` and the polynomial order of `poly`.

Or with Monte-Carlo integration:
```python
x = distr.sample(large_number)
evals = poly[i](*x)*poly[j](*x)*poly[k](*x)**(1/2)
custom_expected_value = chaospy.mean(evals, -1)
```

Let me know if this helps solve your problem.

**Comment by jigarparekh279** [comment]
Yes, the quadrature integration indeed works fine and solved my problem. Thank you.

**Comment by jonathf** [comment]
Glad I could help.
