### ISSUE TITLE
bivariate Legendre Polynomials

### ISSUE THREAD

**Issue by marcrocasalonso** [jonathf/chaospy#146]
Dear Jonathan,

How I can create a bivariate Legendre basis of degree 6 with your code?
For example, in a polynomial basis I do the Pascal Triangle by:
[ x**6, y**6, x**5*y**4,y**5*x**4,x**5,y**5,x**4*y**3,y**4*x**3,....,x, y, 1]

Thank you in advance!

Marc

**Comment by jonathf** [comment]
Something like this?

    poly = cp.orth_ttr(6, cp.Iid(cp.Uniform(-1, 1), 2))

**Comment by marcrocasalonso** [comment]
Yes!!! Perfect!

Marc
