### ISSUE TITLE
QoI example broken

### ISSUE THREAD

**Issue by jonathf** [jonathf/chaospy#15]
@flo2k I am working on a refactor of the code, I am noticing that your code example for `QoI_Dist` is incomplete:

    Examples:
        >>> cp.seed(1000)
        >>> x = cp.variable(1)
        >>> poly = cp.Poly([x])
        >>> qoi_dist = cp.QoI_Dist(poly, dist)
        >>> print(qoi_dist[0].pdf([-0.75, 0., 0.75]))
        [  1.27794383e-123   3.99317083e+000   1.16692607e-100]

What should `dist` be defined as to complete this example?

**Comment by flo2k** [comment]
Hi Jonathan,

I think, that I have time during the week to answer your question.

Best,

Florian

Am 24.09.2016 um 22:55 schrieb Jonathan Feinberg:

**Comment by flo2k** [comment]
Hi @jonathf you can find the solution in https://github.com/jonathf/chaospy/pull/17

**Comment by flo2k** [comment]
I do also have some unit tests written with python unittest framework. Do you know a place where I can put it in an let it automatically run from the CI system?

**Comment by jonathf** [comment]
Thank you.

As for the unittests, you can place them in `chaospy/tests` which you can find in the `development` branch. It is much appreciated.
