### ISSUE TITLE
coefficients of the polynomial expansion of uniform random variable

### ISSUE THREAD

**Issue by jigarparekh279** [jonathf/chaospy#153]
I have a random variable with uniform distribution in [a,b]. How can I use chaospy to estimate first 2 coefficients of the polynomial expansion of this random variable using the standard uniform distribution in [-1,1] as the germ along with the Legendre polynomials? 

distr = chaospy.Normal(-1,1)
poly = chaospy.orth_ttr(2, distr, normed=False)
...?

**Comment by jonathf** [comment]
You mean something like:

  distr = chaospy.Uniform(a, b)
  poly = chaospy.orth_ttr(2, distr, normed=False)

**Comment by jigarparekh279** [comment]
Sorry. I was unclear in my 1st comment. 

Let's say I have a general uniform random variable in [a,b] and I want to expand it using polynomial chaos, as the sum of products of coeffs and orthogonal polynomials. I would do so by mapping this random variable on to a standard uniform variable in [-1,1] (please see slide 62-66 [here](https://www.aices.rwth-aachen.de/files/Inhalte%20Webseite/pdf/EU%20Regional%20School/Slides2016/McClarren.pdf)). 

Also, why does:

distr = chaospy.Uniform(-1, 1)
poly = chaospy.orth_ttr(2, distr, normed=False)

gives me different polynomials as compared to slide 64 in the link above.

**Comment by jonathf** [comment]
Right. You are talking about generalized polynomial chaos, and the coefficients are the Fourier coefficients.

Something like:
```python
real_distribution = chaospy.Uniform(a, b)
proxy_distribution = chaospy.Uniform(-1, 1)

polynomial_expansion = chaospy.orth_ttr(2, proxy_distribution)

proxy_X, proxy_W = chaospy.generate_quadrature(4, proxy_distribution)
real_X = real_distribution.inv(proxy_distribution.fwd(proxy_X))
real_W = proxy_W * real_distribution.pdf(real_X) / proxy_distribution.pdf(proxy_X)

evals = [foo(sample) for sample in real_X.T]

foo_approx, fourier_coeffs = chaospy.fit_quadrature(
    polynomial_expansion, proxy_X, real_W, evals, retall=True)
```
Note that what I am doing here is a bit overkill for the uniform case of yours, as a lot of terms cancels out. But this formulation is general and can be used on any real/proxy pair. Though note that accuracy might suffer if real and proxy isn't sufficiently "similar" to each other.

The reason the polynomial isn't the same, is that the orthogonality property is invariant to scalar multiplication, and ``chaospy`` uses only monic polynomials. If you multiply your polynomial with the leading constant in front of the highest order term from the slide 64, you will get the same polynomial.

**Comment by jigarparekh279** [comment]
Thanks for the comment. This is exactly what I was looking for. I agree that its an overkill for the uniform case. I just wanted to confirm my hand calculations when using normed (=True/False) option in oth_ttr. I did find them in accordance with my calculations. Also, if we now take a Normal real/proxy pair, I see that more terms are non-zero as compared to the uniform real/proxy pair. And the accuracy is bad when we have very different distributions for real and proxy pair (I tried Uniform and Normal respectively).

Also, thanks for the comment on the monic polynomials used in chaospy. I indeed overlooked it.

**Comment by jonathf** [comment]
I am glad to hear that.

One last thing: You write at the top `chaospy.Normal(-1, 1)`. The canonical form is `choaspy.Normal(0, 1)`. Is it possible that your "more terms are non-zero" is because you are not using canonical form?

**Comment by jigarparekh279** [comment]
So I did three cases here.

`real_distribution = chaospy.Uniform(0.075, 0.125)`
`proxy_distribution = chaospy.Uniform(-1, 1)`
`evals = [(sample) for sample in real_X.T]`

gives these coeffs -
[[  1.00000000e-01]
 [  1.44337567e-02]
 [ -6.93889390e-18]
 [  2.37904934e-18]
 [ -1.46202209e-17]]

While, 

`real_distribution = chaospy.Normal(0.1, 0.01)`
`proxy_distribution = chaospy.Normal(0, 1)`
`evals = [(sample) for sample in real_X.T]`

I get these coeffs -
[[  1.00000000e-01]
 [  1.00000000e-02]
 [  4.20958654e-03]
 [  7.02546900e-04]
 [  3.45383443e-04]]

Although they are decreasing, I would say they are still significant.

and,

`real_distribution = chaospy.Uniform(0.075, 0.125)`
`proxy_distribution = chaospy.Normal(0, 1)`
`evals = [(sample) for sample in real_X.T]`

gives coeffs -
[[ 0.1       ]
 [ 0.00333334]
 [ 0.00255967]
 [ 0.00015333]
 [ 0.00017314]]

Which, as expected would need more terms, since the real/proxy pair are very different.

**Comment by jonathf** [comment]
Ah, then I misunderstood.

Looks like you have a good overview now. Closing.
