### ISSUE TITLE
Output's first and second statistical moments evaluations...

### ISSUE THREAD

**Issue by ar-valdez** [jonathf/chaospy#156]
Dear @jonathf ,

I have another question. In Chaospy, the expected value and std. deviation are evaluated over the model's output samples. This evaluation returns a positive value (or null) for the std. deviation.

Assume the following scenario you are measuring absolute temperatures. The expected value is positive always, but when we plot "expected value plus minus one std.dev" it can happen that negative "shaded temps" appear.... How do you avoid this situations?

Is it there any way to tell ChaosPy, that the model's output behaves as lognormal. Something like this:

`E = cp.Mean(model_output_samples,"lognormal")`
`S = cp.Std(model_output_samples,"lognormal")`

If so I would appreciate an advice on how to do sth like this. I am having negative "shaded" values.

**Comment by jonathf** [comment]
The idea of fitting the model "as if lognormal" for the response variable seems paradoxical to me. If `model_output_samples` and `lognormal` are nothing alike, you will not get very far.

But addressing the intent of what you are asking about; you want to put constrains on your model within legal ranges. This can be done using importance sampling. It can be done as follows:

* Do analysis such that you have `model_approx` and `dist`. (Use `SampleDist` if you need to.)
* generate a lot of random samples, e.g. `samples = dist.sample(10**6)`.
* Make evaluations `evals = model_approx(*samples)`
* Sub sample evaluations within legal bounds: `evals = evals[evals >= 0]`.
* Generate mean and standard deviation from samples: `E, S = np.mean(evals, -1), np.std(evals, -1)`

I assume here that the distribution you are after is exactly the same as before, only "trunkated" at one of the bounds.

Here there are two levels of sample generation that intuitively can seem a bit redundant. But there is difference in that the first order of sampling is assumed to be costly (or defined by a file in your case), while the other is cheap. So the secondary analysis removes "aliasing" from the first order by allowing a much large sample size.

Though that being said, your problem might also benefit from just sticking to traditional Monte Carlo. I don't know your use case well enough.

Last note:
The idea that a standard deviation upholds complex model bounds is a little troubling, and will easily not hold in the best of conditions. What I am describing above might not even solve your problem, though it likely will in practice. but a better measure to capture uncertain variability that actually captures constraints is percentile. E.g. 25-75 % for something similar to `E+/-S`, but shades between 5-95 percentile might be more canonical. Use `cp.Perc` and `np.percentile` to this end.

**Comment by ar-valdez** [comment]
Dear @jonathf thanks for the answer. I would like then to try the percentile approach. Can you tell me how to access them? Where you quoting this method(see the link)
https://chaospy.readthedocs.io/en/development/descriptives.html#percentile-function-perc

**Comment by jonathf** [comment]
In the simple case you just replace `E-S` with `cp.Perc(model_approx, 5)` and `E+S` with `cp.Perc(model_approx, 95)`.

For the recipe above, the equivalent would be `np.percentile(evals, 5)` and `np.percentile(evals, 95)` respectively.

**Comment by ar-valdez** [comment]
Thank you very much. I will close the issue.

**Comment by ar-valdez** [comment]
Thank you very much. I will close the issue.
