### ISSUE TITLE
Least Squares and truncated distributions

### ISSUE THREAD

**Issue by alejandro-pd** [jonathf/chaospy#165]
Is it possible to obtain a polynomial approximation with regression using truncated distributions with cp.trunk()? I have the following warning constantly showing when trying to call cp.fit_regression(poly, samples, evaluations, rule = 'LS'):

> Distribution Trunc(0.0001, Normal(mu=0.32184, sigma=0.001)) has stochastic dependencies; Approximating moments with quadrature.

This message is printed in a loop and no solution is achieved. The way I define a truncated normal distribution in the lower limit: 

`cp.trunk(lowerlimit, cp.Normal(mean,sigma)). `

I have tested the code without truncation in a basic scenario and everything works as expected, but truncation is necessary for the full case. Is there any way to work around this problem?

Thank you.

**Comment by jonathf** [comment]
Do you mind providing an example? I ran this little example without trouble:

    dist = cp.Trunc(0.0001, cp.Normal(mu=0.32184, sigma=0.001))
    poly = cp.orth_ttr(4, dist)
    X = dist.sample(100000)
    Y = [x*x-1 for x in X.T]
    approx = cp.fit_regression(poly, X, Y, rule="LS")
    print(cp.around(approx, 5))
    # q0^2-1.0

**Comment by jonathf** [comment]
This discussion might be relevant to your issue:
https://github.com/jonathf/chaospy/issues/79

**Comment by alejandro-pd** [comment]
It is really strange. I have chaospy installed on a laptop and also on a desktop. In the laptop I have no errors with your example or the attached code I am also using. However in the desktop I have the warning with the stochastic dependencies in the exact same code. Could it be related with the chaospy version? I installed it on the desktop more rencently, using 'conda install -c conda-forge chaospy'. 

```
    def testproblem(x1,x2):
        function = np.log(1+x1**2)*np.sin(5*x2)
        return function

    distribution = cp.J(cp.trunk(1.32,cp.Normal(2,0.4)), cp.trunk(1.34,cp.Normal(2,0.5)))
    orderPC = 8
    poly = cp.orth_ttr(orderPC,distribution)
    
    Np = 2
    numbersamples = len(poly) * Np 
    samplesPC = distribution.sample(numbersamples , rule = 'M')
    
    evalsPC = [testproblem(sample[0],sample[1]) for sample in samplesPC.T]
    
    funct_approx = cp.fit_regression(poly, samplesPC, evalsPC, rule = 'LS')
```

**Comment by jonathf** [comment]
That sounds like your problem stems from difference in setup. To start diagnosing I need to know the following for each of your systems:

Also, let us be a bit more rigorous, as clearly it matters in your case. For each system, please provide:
* chaospy version (from the variable `chaospy.__version__`)
* operating system
* python version (by running `python --version`)

**Comment by alejandro-pd** [comment]
Laptop (working with no errors): Windows 10 Home x64, chaospy version 2.3.5, python 3.7.

Desktop (stochastic dependencies errors): Windows 10 Pro x64, chaospy version 3.0.7, python 3.7.3.

**Comment by jonathf** [comment]
Found the warning message. Nothing of importance. It should be muffled in version 3.0.9.

Just to note, there is also a dedicated truncated normal distribution available: `chaospy.TruncNormal(lower, upper, mu, sigma)`. It has some analytical properties that makes it faster and potentially more accurate than the manually truncated distributions.

**Comment by alejandro-pd** [comment]
Thank you for your time.

Now I have another problem when importing chaospy. I have updated several modules, like numpy and scipy and I have this error:

>   File "C:\...\Anaconda3\lib\site-packages\chaospy-2.3.5-py3.7.egg\chaospy\distributions\approx.py", line 18, in <module>
>     import chaospy.quad
> 
>   File "C:\...\Anaconda3\lib\site-packages\chaospy-2.3.5-py3.7.egg\chaospy\quad\__init__.py", line 38, in <module>
>     from .interface import generate_quadrature
> 
>   File "C:\...\Anaconda3\lib\site-packages\chaospy-2.3.5-py3.7.egg\chaospy\quad\interface.py", line 4, in <module>
>     from scipy.misc import comb
> 
> ImportError: cannot import name 'comb' from 'scipy.misc' (C:\...\Anaconda3\lib\site-packages\scipy\misc\__init__.py)

It might be related with this:
https://stackoverflow.com/questions/47151453/sklearn-import-error-importerror-cannot-import-name-comb

Is there a quick way to solve this?

**Comment by jonathf** [comment]
Yes, you are correct. This is a known problem.

Quick fix: Update chaospy to the newest version, or downgrade scipy.

If there are incompatibilities I could release a 2.3.6 version that fixes the import. Let me know.

**Comment by alejandro-pd** [comment]
Everything working fine after the update.

Thank you very much again!

**Comment by jonathf** [comment]
I am glad i worked out.
