### ISSUE TITLE
Build fails with python-3.6: 'ascii' codec can't decode byte 0xc3 in position 4247

### ISSUE THREAD

**Issue by yurivict** [jonathf/chaospy#167]
```
===>  Configuring for py36-chaospy-3.0.9
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 15, in <module>
    LONG_DESCRIPTION = src.read()
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4247: ordinal not in range(128)
*** Error code 1

```

This is caused by non-ASCII characters in some files that it parses.

FreeBSD 12

**Comment by jonathf** [comment]
This is a bit outside my expertise, but here is my two cents.

If they aren't already, but the following in your shell rc file (e.g. `~.bashrc`):

    export LC_CTYPE=en_US.UTF-8
    export LC_ALL=en_US.UTF-8

If that doesn't work, could you try the following from a python terminal in the chaospy repo:

    open("README.rst", encoding="utf8").read()

If the latter works, I can issue a fix.

**Comment by jonathf** [comment]
Fair enough, but do you know how? Would adding the `encoding="utf8"` do the trick?

**Comment by jonathf** [comment]
Okay. I have uploaded version 3.0.10. Can you try if that works for you?

**Comment by yurivict** [comment]
```
===>  Configuring for py27-chaospy-3.0.10
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 10, in <module>
    with open(os.path.join("chaospy", "__init__.py"), encoding="utf8") as src:
TypeError: 'encoding' is an invalid keyword argument for this function
*** Error code 1
```

**Comment by jonathf** [comment]
Python 2 does not support the encoding. I have made another attempt with 3.0.11. Can you give it a shot?

If it doesn't work, do you mind trying to fig the problem on your system? I do not have OpenBSD, so I am really struggling to diagnose issues like these.

**Comment by yurivict** [comment]
The problem still exists in ```3.0.12```.

**Comment by jonathf** [comment]
Sure. Try now with version 3.0.13. I have change the installation procedure to follow PEP 517.

**Comment by jonathf** [comment]
Considering the issue as solved. Reopen if that is not the case.
