### ISSUE TITLE
How to implement the computation of probability in Chaospy?

### ISSUE THREAD

**Issue by AmosJoseph** [jonathf/chaospy#172]
the computation of probability like P(y<6)

**Comment by jonathf** [comment]
Assuming a probability distribution, you can use the `.cdf` method. E.g.

    dist = chaospy.Exponential(0, 1)
    print(dist.cdf(6))

**Comment by AmosJoseph** [comment]
OK,Many Thanks !!

**Comment by AmosJoseph** [comment]
Excuse me!
y=y(x1,x2,x3,x4).
x1,x2,x3,x4 are independent random varibles,and all obey normal distribution.

Then how to compute P(y<6)?

**Comment by AmosJoseph** [comment]
Excuse me!
y=y(x1,x2,x3,x4).
x1,x2,x3,x4 are independent random varibles,and all obey normal distribution.

Then how to compute P(y<6)?

**Comment by jonathf** [comment]
That is more a generic problem and depends upon context, and not always solvable. In you case, what kind of function is `y(x1, x2, x3, x4)`?

**Comment by AmosJoseph** [comment]
![image](https://user-images.githubusercontent.com/40055065/66630019-e8859080-ec35-11e9-8d2b-a1395e746a83.png)

Then how to compute??

**Comment by jonathf** [comment]
For this problem, Monte Carlo Integration is likely a good bet. Something like:

    dist = chaospy.J(chaospy.Normal(55.29, 0.0793**2), ...)
    X1, X2, X3, X4 = dist.samples(1000000)
    Y = numpy.arccos((X1+0.5*(X2+X3))/(X4-0.5*(X2+X3)))
    print(numpy.mean(Y < 6))

The bigger the number of samples, the more accurate the estimate.

**Comment by AmosJoseph** [comment]
What about the methods solving by Regression and Pseudo-spectral Projection?

**Comment by AmosJoseph** [comment]
What about the methods solving by Regression and Pseudo-spectral Projection?

**Comment by jonathf** [comment]
You can go that route as well, if you like. But if the aim is to just get a solution, MCI will get you there faster as it is less setup and you don't have a evaluation bottleneck.

However, if the aim is to learn PCE, you should be able to create a polynomial using the tutorial. But doing `P(Y < 6)` isn't really a trivial problem for polynomials either. So you will end up doing MCI in the end anyway, but on the polynomial instead of the real model.

That said, doing PCE first and MCI afterwards is what I would recommend for models where evaluation in the original model is to costly for traditional MCI.

**Comment by AmosJoseph** [comment]
Excuse me!
Do you have any practical examples about sensitivity analysis?

**Comment by AmosJoseph** [comment]
> For this problem, Monte Carlo Integration is likely a good bet. Something like:
> 
> ```
> dist = chaospy.J(chaospy.Normal(55.29, 0.0793**2), ...)
> X1, X2, X3, X4 = dist.samples(1000000)
> Y = numpy.arccos((X1+0.5*(X2+X3))/(X4-0.5*(X2+X3)))
> print(numpy.mean(Y < 6))
> ```
> 
> The bigger the number of samples, the more accurate the estimate.

When running the above program,there is an error "Y is list,  6 is int",how to handle?
Then numpy.mean(Y < 6) depics mean(expectation),but how to obtain probability(Y < 6)?

**Comment by AmosJoseph** [comment]
![image](https://user-images.githubusercontent.com/40055065/66799682-aebdce00-ef44-11e9-984b-7489f60a8571.png)

What does this mean ”Uncertain l slows down convergence, but introduction of auxiliary
dependent variables restores convergence”？

**Comment by jonathf** [comment]
If `Y` is a list, it is most likely your doing. `numpy.arccos` does not return a list. If you want my help, you need to provide the actual code.

As for the convergence, it is worth noting that polynomial chaos is an approximation method. One of its main properties is that it converges fast to the true value as a function of polynomial order. However, this is not the case for "non-smooth" models. `l` causes a discontinuity in the medium, causing the PCE to be a bad approximation. Auxiliary variable is a technique to restore said convergence properties.

**Comment by jonathf** [comment]
A general note, moving forward: Since this is a hobby project and you are asking a lot of question, please do me the following favor:

* Upon new issues for problem unrelated to the main topic.
* Close issues you consider complete.
* If filing a bug report, include a minimal working example which reproduce said bug. Make note of the difference between when you expect and what you received.

**Comment by AmosJoseph** [comment]
def f(x1,x2,x3,x4):
    return np.arccos((x1+0.5*(x2+x3))/(x4-0.5*(x2+x3)))
distribution = cp.J(cp.Normal(55.29, 0.0793)......
samples = distribution.sample(10**6,"H")
evals = [f(x[0], x[1],x[2], x[3]) for x in samples.T]
print(np.mean(f(x1,x2,x3,x4) < 6))             #code,below is the error
----------------------------------------------------------------------------------------------------
AttributeError: 'Mul' object has no attribute 'arccos'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/dell/PycharmProjects/untitled2/MonteCarol_Fortini.py", line 19, in <module>
    print(np.mean(f(x1,x2,x3,x4) < 6))
  File "C:/Users/dell/PycharmProjects/untitled2/MonteCarol_Fortini.py", line 5, in f
    return np.arccos((x1+0.5*(x2+x3))/(x4-0.5*(x2+x3)))
TypeError: loop of ufunc does not support argument 0 of type Mul which has no callable arccos method
------------------------------------------------------------------------------------------------------------
models must be smooth to use PCE?
Best regards!
Joseph

**Comment by jonathf** [comment]
Your code isn't coherent. My guess is that `x1,x2,x3,x4` is defined incorrectly, but hard to tell from this incomplete snippet.

As I noted above:
> If filing a bug report, include a minimal working example which reproduce said bug. Make note of the difference between when you expect and what you received.

Please provide a working example if you want my help.

To assure high accuracy to low number of evaluations, yes the model needs to be smooth.

**Comment by AmosJoseph** [comment]
import chaospy as cp
import numpy as np

def f(x1,x2,x3,x4):
    return np.arccos((x1+0.5*(x2+x3))/(x4-0.5*(x2+x3)))

x1 = cp.Normal(55.29, 0.0793)
x2 = cp.Normal(22.86, 0.0043)
x3 = cp.Normal(22.86, 0.0043)
x4 = cp.Normal(101.60, 0.0793)
distribution = cp.J(cp.Normal(55.29, 0.0793),cp.Normal(22.86, 0.0043),
                    cp.Normal(22.86, 0.0043),cp.Normal(101.60, 0.0793))

samples = distribution.sample(10**6,"H")
evals = [f(x[0], x[1],x[2], x[3]) for x in samples.T]
mean = np.mean(evals,0)       
deviation = np.std(evals,0)   
print(mean,deviation)
print(np.mean(f(x1,x2,x3,x4) < 6))



np.mean(f(x1,x2,x3,x4) < 6) is to obtain the mean of f(x1,x2,x3,x4) < 6,but how to compute Probability(f(x1,x2,x3,x4) < 6)?

Best regards!
Joseph

**Comment by jonathf** [comment]
There we go.

You are defining `x1,x2,x3,x4` as probability distributions and passing them to `numpy.arccos`. Numpy has no way of knowing how to interpret the probability distribution.

Instead try on of the following two approaches:
```python
print(np.mean(f(*samples) < 6))
print(np.mean(numpy.array(evals) < 6))
```
