### ISSUE TITLE
sensitivity,nataf

### ISSUE THREAD

**Issue by AmosJoseph** [jonathf/chaospy#178]
```python
import numpy as np
import chaospy as cp

def f(x1,x2,x3):
    return np.sin(x1) + 7*np.sin(x2)**2 + 0.1*np.power(x3,4)*np.sin(x1)


x1 = cp.Uniform(-np.pi,np.pi)
x2 = cp.Uniform(-np.pi,np.pi)
x3 = cp.Uniform(-np.pi,np.pi)
distribution = cp.J(x1,x2,x3)
polynomial_expansion = cp.orth_ttr(3, distribution)

samples = distribution.sample(2*len(polynomial_expansion), "H")    
evals = [f(x[0], x[1],x[2]) for x in samples.T]
f_approx = cp.fit_regression(
         polynomial_expansion, samples, evals,"T")
sens_first = cp.Sens_m_nataf(3,distribution,samples,evals)
sens_total = cp.Sens_t_nataf(3,distribution,samples,evals)

expected = cp.E(f_approx, distribution)       #cp(chaospy)
deviation = cp.Std(f_approx, distribution)    #cp(chaospy)
print(expected,deviation,2*len(polynomial_expansion))
print(sens_first,sens_total)
--------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Users/dell/PycharmProjects/untitled2/Ishigami.py", line 18, in <module>
    sens_first = cp.Sens_m_nataf(3,distribution,samples,evals)
  File "C:\Users\dell\AppData\Roaming\Python\Python37\site-packages\chaospy\descriptives\sensitivity\nataf.py", line 29, in Sens_m_nataf
    assert dist.__class__.__name__ == "Copula"
AssertionError
---------------------------------------------------------------------------------------------------------
```
Excuse me,I write the code according to the tourial,what is wrong?
and then what does “Main order sensitivity indices”  mean in Main and total order sensitivity indices？
Best regards!

**Comment by jonathf** [comment]
The Nataf sensitivity metric is a highly custom piece of code made for a very specific paper. For your use case, you should limit yourself to looking at `Sens_m`, `Sens_m2` and `Sens_t`.

If you need a primer, Wikipedia is your friend:
https://en.wikipedia.org/wiki/Variance-based_sensitivity_analysis

**Comment by AmosJoseph** [comment]
Sens_m, Sens_m2 and Sens_t can only be used in poly (Poly) – Polynomial.
In this case,f(x1,x2,x3)=np.sin(x1) + 7*np.sin(x2)**2 + 0.1*np.power(x3,4)*np.sin(x1) is not Polynomial,
so Sens_m, Sens_m2 and Sens_t cannot be applied?!

**Comment by jonathf** [comment]
Right. Uncharted territory.

So, put your samples into a distribution and your polynomial variable representation:
```python
dist = cp.J(*[cp.SampleDist(s) for s in samples])
poly = cp.variable(len(dist))
```

With these, you can use the Saltelli functions: `Sens_m_sample Sens_m2_sample Sens_t_sample`

Let me know how it turns out.

**Comment by AmosJoseph** [comment]
![image](https://user-images.githubusercontent.com/40055065/67194412-a6283480-f429-11e9-9df5-54cdaf164d1b.png)

There always exists variate assertion error between the three lines,no matter how to change the sequence  of the three lines.
How to handle the problem?  
Best regards!

**Comment by jonathf** [comment]
The value `2*len(polynomial_expansion)` is arbitrary. I've seen it used here and tere in leterature, but you can choose the value as you see fit.

In your case, I likely would go for `len(samples.T)` as a starting point.

**Comment by AmosJoseph** [comment]
import numpy as np
import chaospy as cp

def f(x1,x2,x3):
    return np.sin(x1) + 7*np.sin(x2)**2 + 0.1*np.power(x3,4)*np.sin(x1)


x1 = cp.Uniform(-np.pi,np.pi)
x2 = cp.Uniform(-np.pi,np.pi)
x3 = cp.Uniform(-np.pi,np.pi)
# distribution = cp.J(x1,x2,x3)
samples=np.linspace(0,1,70)
dist = cp.J(*[cp.SampleDist(samples)])
polynomial_expansion = cp.orth_ttr(3, dist)
samples = dist.sample(70, "H")

# dist = cp.J(*[cp.SampleDist(s) for s in samples])
# polynomial_expansion = cp.orth_ttr(3, dist)
poly = cp.variable(len(dist))

evals = [f(x[0], x[1],x[2]) for x in samples.T]
f_approx = cp.fit_regression(
         polynomial_expansion, samples, evals,"T")

sens_first =cp.Sens_m_sample(poly,dist,samples,"H")
sens_second = cp.Sens_m2_sample(poly,dist,samples,"H")
sens_total = cp.Sens_t_sample(poly,dist,samples,"H")

variance= cp.Var(f_approx, dist)
print(2*len(polynomial_expansion),variance)
print(sens_first,sens_second,sens_total)

There is still error.How to solve it?
What do you mean by  "I likely would go for len(samples.T) as a starting point."?

**Comment by AmosJoseph** [comment]
import numpy as np
import chaospy as cp

def f(x1,x2,x3):
    return np.sin(x1) + 7*np.sin(x2)**2 + 0.1*np.power(x3,4)*np.sin(x1)


x1 = cp.Uniform(-np.pi,np.pi)
x2 = cp.Uniform(-np.pi,np.pi)
x3 = cp.Uniform(-np.pi,np.pi)
# distribution = cp.J(x1,x2,x3)
samples=np.linspace(0,1,70)
dist = cp.J(*[cp.SampleDist(samples)])
polynomial_expansion = cp.orth_ttr(3, dist)
samples = dist.sample(70, "H")

# dist = cp.J(*[cp.SampleDist(s) for s in samples])
# polynomial_expansion = cp.orth_ttr(3, dist)
poly = cp.variable(len(dist))

evals = [f(x[0], x[1],x[2]) for x in samples.T]
f_approx = cp.fit_regression(
         polynomial_expansion, samples, evals,"T")

sens_first =cp.Sens_m_sample(poly,dist,samples,"H")
sens_second = cp.Sens_m2_sample(poly,dist,samples,"H")
sens_total = cp.Sens_t_sample(poly,dist,samples,"H")

variance= cp.Var(f_approx, dist)
print(2*len(polynomial_expansion),variance)
print(sens_first,sens_second,sens_total)

There is still error.How to solve it?
What do you mean by  "I likely would go for len(samples.T) as a starting point."?

**Comment by jonathf** [comment]
Here is a full example using PCE to address your problem aligned with the regression tutorial:
```python
import numpy as np
import chaospy as cp

def f(x1,x2,x3):
    return np.sin(x1) + 7*np.sin(x2)**2 + 0.1*np.power(x3,4)*np.sin(x1)

x1 = cp.Uniform(-np.pi,np.pi)
x2 = cp.Uniform(-np.pi,np.pi)
x3 = cp.Uniform(-np.pi,np.pi)
distribution = cp.J(x1, x2, x3)

polynomial_expansion = cp.orth_ttr(3, distribution)

samples = distribution.sample(2*len(polynomial_expansion), "H")
evaluations = [f(*x) for x in samples.T]
approx_model = cp.fit_regression(polynomial_expansion, samples, evaluations)

print(cp.Sens_m(approx_model, distribution))
print(cp.Sens_m2(approx_model, distribution))
print(cp.Sens_t(approx_model, distribution))
```
Does this work for you?

**Comment by AmosJoseph** [comment]
Extraordinary,Excellent!!
