### ISSUE TITLE
How to compute Probability(y<3) or cdf(y<3)

### ISSUE THREAD

**Issue by AmosJoseph** [jonathf/chaospy#181]
Pardon！There writes "once PCE is built,Statistical Moment and Probability is easily got instantly" in some papers.
Excuse me,but how to compute Probability(y<3)?

Best regards!

**Comment by jonathf** [comment]
Then we are full circle.

Polynomials do not support CDF easily. It requires root-solving which is hard to generalize.

However, as the polynomials are computationally cheaper to evaluate, you can do MCI without much difficulties. For example:

    Y = approx_model(*dist.samples(1000000))
    print(numpy.mean(Y < 3))

**Comment by jonathf** [comment]
I am curious to the papers that claim that probabilities are retrieved instantly from PCE though. If you have some examples, feel free to post them here.

**Comment by AmosJoseph** [comment]
PPT in https://people.cs.kuleuven.be/~dirk.nuyens/uqss2013/KUL_UQ_lec1.pdf  may be the answer.
Refer to "Plotting PDFs of RVs corresponding to PCEs" in slide36 of PPT.

**Comment by AmosJoseph** [comment]
Paper  ”Weighted stochastic response surface method considering sample weights” by Fenfen Xiong writes  "Step 4. Evaluate on the PCE model to obtain the probabilistic characteristics (such as mean, variance and probability of failure) of the output response y." 

This paper may be a clue.

**Comment by jonathf** [comment]
The PPT is saying the same as I am, almost verbatim:

> * Analytical formula formula for PDF(u) exists PCES
>     * Involves polynomial root finding, and is hard to generalize to multi-D
> * PCE is cheap to sample

**Comment by AmosJoseph** [comment]
Dear Jonathan：
         You are right.PDF can be got by performing MCI on PCE model.
         Happy Thanksgiving Festival.
         Many thanks for your help!!

Best regards!

Yours sincerely!

Joseph
