### ISSUE TITLE
Sparse grid,Leja quadrature

### ISSUE THREAD

**Issue by AmosJoseph** [jonathf/chaospy#182]
```python
import chaospy as cp
import numpy as np

x1 = cp.Normal(0.001, 0.00005)
x2 = cp.Normal(0.001, 0.00005)
x3 = cp.Normal(0.001, 0.00005)
x4 = cp.Normal(0.001, 0.00005)
x5 = cp.Normal(0.001, 0.00005)
x6 = cp.Normal(0.001, 0.00005)
x7 = cp.Normal(0.001, 0.00005)
x8 = cp.Normal(0.001, 0.00005)
x9 = cp.Normal(0.001, 0.00005)
x10 = cp.Normal(0.001,0.00005)

x11 = cp.Normal(80, 4)
x12 = cp.Normal(10,0.5)
x13 = cp.Normal(10, 0.5)

x14 = cp.Normal(1, 0.05)
x15 = cp.Normal(100,5)

a11 = (1/x1 + 1/x3 + 1/x5 + 2*np.sqrt(2)/x7 +2*np.sqrt(2)/x8)*x14/(2*x15)
a22 = (1/x2 + 1/x4 + 1/x5 + 1/x6 + 2*np.sqrt(2)/x9 +2*np.sqrt(2)/x10)*x14/(2*x15)
a12 = a21 = x14/(2*x5*x15)
b1 = (x12/x1 - (2*x12 + x11 - x13)/x3 - x12/x5 - 2*np.sqrt(2)*(x12 + x11)/x7)*np.sqrt(2)*x14/(2*x15)
b01 = (1/x1 - 2/x3 - 1/x5 - 2*np.sqrt(2)/x7)*np.sqrt(2)*x14/(2*x15)
b2 = (np.sqrt(2)*(x13 - x12)/x4 - np.sqrt(2)*x12/x5 - 4*x12/x9)*x14/(2*x15)
b02 = (-np.sqrt(2)/x4 - np.sqrt(2)/x5 - 4/x9)*x14/(2*x15)

N8 = (a22*b1 -a12*b2)/(a11*a22 - a12*a21)
N10 = (a11*b2 - a21*b1)/(a11*a22 - a12*a21)
N1 = x12 - 0.5*np.sqrt(2)*N8
N2 = -0.5*np.sqrt(2)*N10
N3 = -x11 -2*x12 + x13 - 0.5*np.sqrt(2)*N8
N4 = -x12 + x13 - 0.5*np.sqrt(2)*N10
N5 = -x12 - 0.5*np.sqrt(2)*N8 - 0.5*np.sqrt(2)*N10
N6 = - 0.5*np.sqrt(2)*N10
N7 = np.sqrt(2)*(x11 + x12 ) + N8
N9 = np.sqrt(2)*x12  + N10


N08 = (a22*b01 -a12*b02)/(a11*a22 - a12*a21)
N010 = (a11*b02 - a21*b01)/(a11*a22 - a12*a21)
N01 = 1 - 0.5*np.sqrt(2)*N08
N02 = -0.5*np.sqrt(2)*N010
N03 = -2 - 0.5*np.sqrt(2)*N08
N04 = -1 - 0.5*np.sqrt(2)*N010
N05 = -1 - 0.5*np.sqrt(2)*N08 - 0.5*np.sqrt(2)*N010
N06 = - 0.5*np.sqrt(2)*N010
N07 = np.sqrt(2) + N08
N09 = np.sqrt(2) + N010

def f(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15):
    return (N01*N1/x1 +N02*N2/x2 + N03*N3/x3+N04*N4/x4 +N05*N5/x5 +N06*N6/x6 + np.sqrt(2)*( N07*N7/x7+N08*N8/x8+ N09*N9/x9+N010*N10/x10))*x14/x15


distribution = cp.J(x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15)

abscissas, weights = cp.generate_quadrature(
    2, distribution, rule="Leja",growth=True, sparse=True)

polynomial_expansion = cp.orth_ttr(2, distribution)
evals = [f(*x) for x in abscissas.T]
f_approx = cp.fit_quadrature(
     polynomial_expansion, abscissas, weights, evals)

print(cp.Sens_m(f_approx, distribution))
print(cp.Sens_t(f_approx, distribution))
# expected = cp.E(f_approx, distribution)       #cp(chaospy)
# deviation = cp.Std(f_approx, distribution)    #cp(chaospy)
# print(expected,deviation)
```

Excuse me,Sparse grid with Leja quadrature works effectively to handle high dimensions problems,
However there still exists error using Sparse grid with Leja quadrature according to the tutorial,
How to solve it?

**Comment by jonathf** [comment]
You are using the same names in two different context in this code. The `x1 ... x15` in global scope are Normal distributions, while `x1 ... x15` in the function scope are samples.

The distributions supports some mathematical operations, but I'd advised against the kind of manipulation you are doing here in the global space. In particular, as all your `aX bX N0X` definitions depend on `x`-es in the global scope, they too become distributions. When combined with the `x`-es in the function scope, damage is already done, and the output becomes a distribution.

To fix this, try move your `aX bX N0X` definitions inside the `def f` scope.

**Comment by AmosJoseph** [comment]
Many thx!

**Comment by AmosJoseph** [comment]
Many thx!

**Comment by AmosJoseph** [comment]
Pardon！When the order of polynomial expansion is 2,the Sensitivity results are close to those in a certain paper,but when the order is 3,the results are totally different.

The higher order,the more accurate result can be got.
But "the results are totally different." as above.Why?

And how can the Sensitivity results be got by Monte Carlo method?

Best Regards!

**Comment by jonathf** [comment]
I don't know. I need more information to evaluate that question.
Please provide:
mean, variance, sensitivity indices for quadrature orders {1, 2, 3} x polynomial order {1, 2, 3}.
Also provided what you would expect, so I know where the problem lies.

Side note: Leja does not support `growth` parameter. It is ignored.

Sensitivity using MCI is not straight forward. But short story, I guess this should work:
```python
main_index = chaospy.Sens_m_sample(f, distribution, n_samples)
total_index = chaospy.Sens_t_sample(f, distribution, n_samples)
```
It isn't quite designed for it, so let me know if it breaks.

**Comment by AmosJoseph** [comment]
import numpy as np
import chaospy as cp

def f(x1,x2,x3):
    return np.sin(x1) + 7*np.sin(x2)**2 + 0.1*np.power(x3,4)*np.sin(x1)


x1 = cp.Uniform(-np.pi,np.pi)
x2 = cp.Uniform(-np.pi,np.pi)
x3 = cp.Uniform(-np.pi,np.pi)
distribution = cp.J(x1, x2, x3)
samples = distribution.sample(10**6,"H")
evals = [f(*x) for x in samples.T]
mean = np.mean(evals,0)        #  np(numpy) not cp(chaospy) in Monte Carlo
variance = np.var(evals,0)
print(mean,variance)
main_index = cp.Sens_m_sample(evals, distribution, samples)
total_index = cp.Sens_t_sample(evals, distribution, samples)
print(main_index)
print(total_index)

Is the code correct as you write?There is still error when running.

**Comment by jonathf** [comment]
`Sens_m_sample(f, distribution, 10**6)`

**Comment by jonathf** [comment]
The normal MCI can not be used to do sensitivity. (Or you can, but it is prohibatively expensive to compute.) So there are variations of the MCI algorithms like the Saltelli method, specifically designed to bring the number of evaluations down to do sensetivity analysis. But it requires a bit of tinkering, so the simple `evals = [f(*x) for x in samples.T]` wont suffice here.

**Comment by AmosJoseph** [comment]
import numpy as np
import chaospy as cp

def f(x1,x2,x3):
    return np.sin(x1) + 7*np.sin(x2)**2 + 0.1*np.power(x3,4)*np.sin(x1)


x1 = cp.Uniform(-np.pi,np.pi)
x2 = cp.Uniform(-np.pi,np.pi)
x3 = cp.Uniform(-np.pi,np.pi)
distribution = cp.J(x1, x2, x3)
samples = distribution.sample(10**6,"H")
evals = [f(*x) for x in samples.T]

mean = np.mean(evals,0)        
variance = np.var(evals,0)
print(mean,variance)

main_index = cp.Sens_m_sample(f, distribution, 10**7)
# main_index2 = cp.Sens_m2_sample(f, distribution, 10**6)
total_index = cp.Sens_t_sample(f, distribution, 10**7)
print(main_index)
# print(main_index2)
print(total_index)


mean and variance are correct.
---------------------------------------------------------------------------------------------
                                     MCI algorithms                               Analytical results   
main_index            [0.31   0.44   2.10931398e-04]               [0.31   0.44       0]
total_index             [0.31  0.44  -4.72604550e-06]               [0.56   0.44   0.24]

There are still big deviations for total_index using MCI algorithms with 10**7 samples!
While main_index provide accurate results. 
Sensitivity indices by PCE is perfect!
----------------------------------------------------------------------------------------------------------------
"main_index2 = cp.Sens_m2_sample(f, distribution, 10**6)" cannot be applied as Error occured!Why?

Sorry!So late to reply！
Best regards!

**Comment by jonathf** [comment]
As I noted above, the code you are running isn't quite designed for the experiment you are running. So the error is a bug.

I've made a patch. Update to version 3.0.16 and the problem should disappear.

**Comment by AmosJoseph** [comment]
Well done!Excellent all the time😄



发自我的iPhone


------------------ Original ------------------
