### ISSUE TITLE
 Multivariate Kernel Density Estimation(KDE)

### ISSUE THREAD

**Issue by AmosJoseph** [jonathf/chaospy#190]
Dear Jonathan：

Excuse me,I write to ask how to get the input marginal PDF by Kernel Density Estimation in the latest chaospy.

Best regards!

**Comment by jonathf** [comment]
Sure:
https://chaospy.readthedocs.io/en/master/recipes/external.html#module-chaospy.external.samples

**Comment by AmosJoseph** [comment]
OK,Many thanks!

Best Regards!






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jonathan Feinberg"<notifications@github.com&gt;; 
发送时间: 2019年12月18日(星期三) 晚上10:56
收件人: "jonathf/chaospy"<chaospy@noreply.github.com&gt;; 
抄送: "Joseph"<544591929@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jonathf/chaospy]  Multivariate Kernel Density Estimation(KDE) (#190)




Sure:
 https://chaospy.readthedocs.io/en/master/recipes/external.html#module-chaospy.external.samples

**Comment by AmosJoseph** [comment]
What about the issue #117&amp;#80 about KDE?

So it works well for issue #117&amp;#80?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jonathan Feinberg"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 晚上10:56
收件人:&nbsp;"jonathf/chaospy"<chaospy@noreply.github.com&gt;;
抄送:&nbsp;"Joseph"<544591929@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jonathf/chaospy]  Multivariate Kernel Density Estimation(KDE) (#190)




Sure:
 https://chaospy.readthedocs.io/en/master/recipes/external.html#module-chaospy.external.samples

**Comment by jonathf** [comment]
#117 addresses both the multivariate and the univariate case of KDE. For the former, there is still work to be done. (Which I may get to during next year.) However, as you only need the marginal density, you can take the data alone the dimension of interest and create a uni variate estimate just fine.

**Comment by AmosJoseph** [comment]
Thanks so much!!&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jonathan Feinberg"<notifications@github.com&gt;; 
发送时间: 2019年12月18日(星期三) 晚上11:44
收件人: "jonathf/chaospy"<chaospy@noreply.github.com&gt;; 
抄送: "Joseph"<544591929@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jonathf/chaospy]  Multivariate Kernel Density Estimation(KDE) (#190)




#117 addresses both the multivariate and the univariate case of KDE. For the former, there is still work to be done. (Which I may get to during next year.) However, as you only need the marginal density, you can take the data alone the dimension of interest and create a uni variate estimate just fine.

**Comment by AmosJoseph** [comment]
What about the issue you merged with #117 asked by Maggie?
Does that work well?



发自我的iPhone


------------------ Original ------------------

**Comment by AmosJoseph** [comment]
Does #83 works well?

**Comment by jonathf** [comment]
Kind of. Accuracy seems to drop of as a function of the number of dimensions, so as I said above: it still needs work.

**Comment by AmosJoseph** [comment]
What about the accuracy of Statsmodel(pypi) to do KDEMutilvariate?&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jonathan Feinberg"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 晚上8:18
收件人:&nbsp;"jonathf/chaospy"<chaospy@noreply.github.com&gt;;
抄送:&nbsp;"Joseph"<544591929@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jonathf/chaospy]  Multivariate Kernel Density Estimation(KDE) (#190)




Kind of. Accuracy seems to drop of as a function of the number of dimensions, so as I said above: it still needs work.

**Comment by jonathf** [comment]
I am not following. The statsmodel version works fine, though quite slow. But the properties need to to create a Rosenblatt transformation (which Chaospy relies on), does not work as well as we need them to. Thereby the drop in performance.
