### ISSUE TITLE
user-defined distribution

### ISSUE THREAD

**Issue by AmosJoseph** [jonathf/chaospy#194]
Dear Jonathan:

I get the joint pdf(in a form of numpy.ndarray),how to construct a user-defined distribution,  sample  and  evaluate according to the user-defined distribution?

Happy new year!

Best wishes to you!

Best regards!

**Comment by jonathf** [comment]
Not sure exactly what you are asking for.
Something like this, perhaps:
https://chaospy.readthedocs.io/en/master/recipes/external.html#module-chaospy.external.samples

**Comment by AmosJoseph** [comment]
Y = f(x1,x2,x3),I get joint probability density function pdf(x1,x2,x3) in a form of numpy.ndarray,

then how to sample on X(x1,x2,x3) and evaluate Y,eventually get Kernel Density Estimation

(namely probability density function pdf) of Y?

Mnay thanks!

**Comment by jonathf** [comment]
I am still struggling here.

what does it mean to have a pdf in the form of a ndarray?
What is X(x1, x2, x3) in this context?
What do you mean by "evaluate Y"

**Comment by AmosJoseph** [comment]
Dear Jonathan:

X(x1, x2, x3)  is sampling on input space.
"evaluate Y" is  to compute Y,the output.

![image](https://user-images.githubusercontent.com/40055065/72218175-fcad9680-3572-11ea-85d3-19d2477afbd5.png){from "Data-driven polynomial chaos expansion for machine learning regression"}
-------------------------------------------------------------------------------
Code:
import pyvinecopulib as pv
import numpy as np
import chaospy as cp
import statsmodels.api as sm

def f(x1,x2,x3):
    return 1 + (np.sin(x1) + 7*np.sin(x2)**2 + 0.1*np.power(x3,4)*np.sin(x1) + 1 + np.pi**4/10)/(9 + np.pi**4/5)

x1 = cp.Uniform(-np.pi,np.pi)
x2 = cp.Uniform(-np.pi,np.pi)
x3 = cp.Uniform(-np.pi,np.pi)

t1 = pv.Bicop(family=pv.BicopFamily.student,rotation=0, parameters=[0.5, 3])
sim_data1 = t1.simulate(10**7)
c_student = t1.pdf(sim_data1)  #copula  density of the pairwise  t-copula families

g1 = pv.Bicop(family=pv.BicopFamily.gumbel,rotation=0,parameters=[2])
sim_data2 = g1.simulate(10**7)
c_gumbel = g1.pdf(sim_data2)  #copula  density of the pairwise Gumbel families

distribution = c_student*c_gumbel*(1/((2*np.pi)**3))  #joint pdf   
#!! print(type(distribution)) <class 'numpy.ndarray'>
# distribution is joint pdf in the form of a numpy.ndarray!But not the usual form as in Chaospy.

samples = distribution.sample(10**7, "H")  #cannot be done as usual in Chaospy!!
evaluations = [f(*x) for x in samples.T]        #cannot be done
kde = sm.nonparametric.KDEUnivariate(evaluations)   #cannot be done
-------------------------------------------------------------------------------------------------------
[Data-driven polynomial chaos expansion for machine learning regression.pdf](https://github.com/jonathf/chaospy/files/4050617/Data-driven.polynomial.chaos.expansion.for.machine.learning.regression.pdf)

**Comment by jonathf** [comment]
Am I understanding the context correctly that you want to couple the copulas from the `pyvinecopulib` and get it working with `chaospy`? And the approach you want to do is data driven PCE?

Is the aim here to get it to work, or are you married to the data driven approach?

Is there any reason the `statsmodels` line is included in the example?

**Comment by AmosJoseph** [comment]
Am I understanding the context correctly that you want to couple the copulas from the&nbsp;pyvinecopulib&nbsp;and get it working with&nbsp;chaospy?&nbsp; &nbsp; &nbsp;Yes!
&nbsp;And the approach you want to do is data driven PCE?&nbsp; &nbsp; &nbsp;Yes!



Is the aim here to get it to work, or are you married to the data driven approach?

The aim is to get it to work!&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Honestly I am not familiar with data driven approach,I try to do the fisrt case(Ishigami function).&nbsp;



Is there any reason the&nbsp;statsmodels&nbsp;line is included in the example?
I think statsmodels is easy to understand and to implement KDE(get the approximate pdf of output) in comparison with Scikit-learn.

Best Regards!

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jonathan Feinberg"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月12日(星期天) 晚上11:29
收件人:&nbsp;"jonathf/chaospy"<chaospy@noreply.github.com&gt;;
抄送:&nbsp;"Joseph"<544591929@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jonathf/chaospy] user-defined distribution (#194)




Am I understanding the context correctly that you want to couple the copulas from the pyvinecopulib and get it working with chaospy? And the approach you want to do is data driven PCE?
 
Is the aim here to get it to work, or are you married to the data driven approach?
 
Is there any reason the statsmodels line is included in the example?

**Comment by jonathf** [comment]
Then we are on a track I understand a bit more.

Next round of questions:

* How does the input `(X1, X2, X3)` relate to the `(StudentT, Gumbel)` joint distribution? `Bicop` kind of hints to that it is bivariate only, so I am not seeing how your problem can be addressed.
* Is there a reason you are interested in creating `.pdf` values per say? If you are doing data driven PCE, `(sim_data1, sim_data2)` what you want, right?

**Comment by jonathf** [comment]
Ah, right, the picture. Now I see.

Can you create this  `C_X(u1, u2, u3)` using `pyvinecopulib`?
Will it support `.simulate` to generate `(3, N)` ndarrays?

**Comment by AmosJoseph** [comment]
Can this be done by copula in chaospy?

**Comment by jonathf** [comment]
Well, I don't know how the Vine copula works, but for the copulas chaospy support: yes it can. And it makes data driven pce much easier.

**Comment by jonathf** [comment]
Not wure why this ended up in my inbox and not the thread.

AmosJoseph said:
> Am I understanding the context correctly that you want to couple the copulas from the&nbsp;pyvinecopulib&nbsp;and get it working with&nbsp;chaospy?&nbsp; &nbsp; &nbsp;Yes!
&nbsp;And the approach you want to do is data driven PCE?&nbsp; &nbsp; &nbsp;Yes!
> 
> Is the aim here to get it to work, or are you married to the data driven approach?
> 
> The aim is to get it to work!&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Honestly I am not familiar with data driven approach,I try to do the fisrt case(Ishigami function).&nbsp;
> 
> Is there any reason the&nbsp;statsmodels&nbsp;line is included in the example?
I think statsmodels is easy to understand and to implement KDE(get the approximate pdf of output) in comparison with Scikit-learn.
> 
> Best Regards!

**Comment by AmosJoseph** [comment]
> Ah, right, the picture. Now I see.        Make sense?OK!
> 
> Can you create this `C_X(u1, u2, u3)` using `pyvinecopulib`?     Yes!
> Will it support `.simulate` to generate `(3, N)` ndarrays?            Maybe not!
----------------------------------------------------------------------------------------
Code:
c_X = c_student*c_gumbel
sim_data = c_X.simulate(10**7)
----------------------------------running error:
    sim_data = c_X.simulate(10**7)
AttributeError: 'numpy.ndarray' object has no attribute 'simulate'

c_X = c_student*c_gumbel  is  a  form  of   'numpy.ndarray'!

**Comment by AmosJoseph** [comment]
> Not wure why this ended up in my inbox and not the thread.
> 
> AmosJoseph said:
> 
> > Am I understanding the context correctly that you want to couple the copulas from the pyvinecopulib and get it working with chaospy?     Yes!
> >  And the approach you want to do is data driven PCE?     Yes!
> > Is the aim here to get it to work, or are you married to the data driven approach?
> > The aim is to get it to work!          Honestly I am not familiar with data driven approach,I try to do the fisrt case(Ishigami function). 
> > Is there any reason the statsmodels line is included in the example?
> > I think statsmodels is easy to understand and to implement KDE(get the approximate pdf of output) in comparison with Scikit-learn.
> > Best Regards!

Maybe I reply by the email...

**Comment by jonathf** [comment]
> c_X = c_student*c_gumbel
> sim_data = c_X.simulate(10**7) ----------------------------------running error: sim_data = c_X.simulate(10**7)
> AttributeError: 'numpy.ndarray' object has no attribute 'simulate'
> 
> c_X = c_student*c_gumbel is a form of 'numpy.ndarray'!

No. The `c_student` and `c_gumbel` are not the models. They are density evaluations. They are not expected to have any custom `pyvinecopulib` method attached to them.
The objects `t1` and `g1` however, does. We are interested in creating the Copula of interest before `.pdf` is used. But it doesn't give you the 3-D model. Only two 2-D models.

**Comment by AmosJoseph** [comment]
Dear Jonathan:

c_X(u1, u2, u3) is C-vine copula with density(copula density),and can be represented by copula pair,
so c_X(u1, u2, u3) = c(G)_12(u1, u2;2)*c(t)_13(u1, u3;0.5,3),
c(G)_12(u1, u2;2) is density of the pairwise Gumbel families(copula density) ,
c(t)_13(u1, u3;0.5,3) is density of the pairwise  t-copula families(copula density).
therefore 3-D model can be represented by  two 2-D models!

Joint pdf is c_X(u1, u2, u3)*maginal pdf(u1) *maginal pdf(u2)*maginal pdf(u3),
which is 'numpy.ndarray'  by the code.

**Comment by jonathf** [comment]
If density evaluation is the only thing you have, than it is not possible to do data driven PCE. The pieces of your puzzle simply does not fit together.

**Comment by AmosJoseph** [comment]
Would you like to explain in detail please?

**Comment by jonathf** [comment]
You have access to PDF evaluation.

Data driven PCE requires you to either have a random number generator or an inverse Rosenblatt transformation functoin to map into the correct space. Without it, you can construct your KDE/Sample distribution.

**Comment by AmosJoseph** [comment]
Excuse me!
Do you have any examples?
Could you please send me?

Best Regards!

**Comment by jonathf** [comment]
I am not following. You want me to give you examples of why the approach you are going for doesn't work?
Or you want an example of data driven PCE combined with Copula that does wotk?

I can not help with the former as it involves proving a negative.

For the latter however, I can give you the chaospy page on Copula:
https://chaospy.readthedocs.io/en/master/distributions/copulas.html

Each copula can generate random samples (though quite slow) with:

    samples = copula.sample(N)

With the samples, creating evaluations and sample dist is straight forward:

    distribution = cp.J(cp.SampleDist(xcol) for xcol in samples)
    evals = [f(*xrow) for xrow in samples.T]

Though this approach misses the dependencies between the dimensions, so it doesn't work until a multivariate SampleDIst is in place. Getting one ready is on my (long) bucket list of things to do.

**Comment by AmosJoseph** [comment]
What about the example of inverse Rosenblatt transformation function to map into the correct space?

**Comment by jonathf** [comment]
See line 3:
https://github.com/vinecopulib/pyvinecopulib/blob/master/examples/vine_copulas.ipynb

**Comment by AmosJoseph** [comment]
OK!

**Comment by AmosJoseph** [comment]
Pardon,What do you mean by “I can not help with the former as it involves proving a negative”?proving a negative?

" You have access to PDF evaluation." I have?

**Comment by jonathf** [comment]
> Pardon,What do you mean by “I can not help with the former as it involves proving a negative”?proving a negative?

I can not help you prove that data driven PCE can not be done from PDF evaluations alone.

> 
> " You have access to PDF evaluation." I have?

I am not your teacher. There is a limit to how much time I have to help you understand your own code. But I'll indulge a little more.

Take this snippet fo yours:

    t1 = pv.Bicop(family=pv.BicopFamily.student,rotation=0, parameters=[0.5, 3])
    sim_data1 = t1.simulate(10**7)
    c_student = t1.pdf(sim_data1)  #copula  density of the pairwise  t-copula families

Here `t1` is bivarite copula. It has a set of methods. Two of these methods are `.simulate` which generate random samples from the copula, and `.pdf` which is the probability density function. You use the former to generate `10**7` samples, and then you feed them back into the density function. Since you are evaluating random samples with the PDF, I call it "PDF evaluations". It is what you have done.

Why you are doing so is entirely another matter. It would make sense if the goal was maximum likelihood estimation (MLE), but that is not where we are. This make you code somewhat nonsensical. But that being said, that doesn't mean that there isn't a sense here, it might be, given I have zero experience with `pyvinecopulib` and how to operate it. It just doesn't point anywhere from my point of view.

**Comment by AmosJoseph** [comment]
ok,many thanks!
