### ISSUE TITLE
Update requirements poetry 1.0.0

### ISSUE THREAD

**Issue by lbazan** [jonathf/chaospy#195]
Hi @jonathf 

Cam you update the requirements? thanks! 

Handling poetry>=0.12 from build-system.requires
**Requirement satisfied: poetry>=0.12**
   (installed: poetry 1.0.0)

**Comment by jonathf** [comment]
Not sure what you are asking for. Do you mean update the `requirements.txt` file?

**Comment by lbazan** [comment]
> Not sure what you are asking for. Do you mean update the `requirements.txt` file?

https://github.com/jonathf/chaospy/blob/master/pyproject.toml 

Hi @jonathf 

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

**Comment by jonathf** [comment]
I am willing to change it if there is a reason for it.

So the poetry version is not set in the lock file, as it is a build dependency. It can be whatever it wants to be 0.12 or 1.0.0. And there is a rational to leaving it to `>=0.12`. Most notably, tt is recommended by poetry documentation:
https://python-poetry.org/docs/pyproject/#poetry-and-pep-517
So do you mind elaborating why we should deviate from this, first?

**Comment by jonathf** [comment]
Okay, so I have have updated the req to 1.0 as it is becoming clear that poetry's backwards compatibility to 0.12 from 1.0 is really poor.
