### ISSUE TITLE
Should we mention chaospy on Wikipedia?

### ISSUE THREAD

**Issue by flo2k** [jonathf/chaospy#197]
Hi Jonathan,

on https://en.wikipedia.org/wiki/List_of_uncertainty_propagation_software is a list of UQ software. Should we mention chaospy here, too?

Best,

Florian

**Comment by jonathf** [comment]
Not a bad idea. :)

**Comment by jonathf** [comment]
Solved

**Comment by flo2k** [comment]
cool.
