### ISSUE TITLE
Large number of variables

### ISSUE THREAD

**Issue by DorDveer** [jonathf/chaospy#205]
Hello!
Assuming that i have large number of variables from different distributions, there is a smart way to input them to :
_chaospy.J(......)_ function?

Regards
Dor.

**Comment by jonathf** [comment]
Something like this?
```python
distribution_list = [chaospy.Uniform(), chaospy.Normal(), ...]
joint = chaospy.J(*distribution_list)
```

**Comment by IritDor** [comment]
exactly. Tank's.
There is NumPy way which not include list?

**Comment by jonathf** [comment]
If I understand you correctly, the answer is no.
Chaospy is not designed to scale to very high numbers of dimension where lists needs to be replaced with Numpy arrays.
