### ISSUE TITLE
Ordering of exponents and polynomials

### ISSUE THREAD

**Issue by jigarparekh279** [jonathf/chaospy#211]
I use the following code to generate 3-dimensional Hermite polynomials :

```python
import chaospy as cp

dim   = 3     
order = 2     
 
xiList = [cp.Normal(0,1), cp.Normal(0,1), cp.Normal(0,1)]

dist = cp.J(*xiList)
phi, norms = cp.orth_ttr(order, dist, retall=True, normed = False)

print(phi.exponents)
print(phi)
```
The output :
```python
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 2]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [0 2 0]
 [2 0 0]]

[1.0, q2, q1, q0, q2^2-1.0, q1q2, q1^2-1.0, q0q2, q0q1, q0^2-1.0]
```
From the array of polynomials, the fourth entry in the array of exponents should have been `[1 0 0]`, which is not the case here. Why is there a difference in the ordering of exponents and polynomials?

**Comment by jonathf** [comment]
`polynomial.exponents` is an internal component relating to how the polynomial is represented, not it's leading exponent, as you are insinuating.

The real use for the `exponents` attribute is that you can do the following:
```python
poly == poly.coefficients * poly.indeterminants ** poly.exponents
```

If you want the leading polynomial power relative to the expansion creation, use the following function:
```python
indices = chaospy.bertran.bindex(start=0, stop=order, dim=len(dist))
```

Note that this only works if the he arguments for `bindex` and `orth_ttr` correspond.
So if you choose to change e.g. `sort` or `cross_trucation` you must do so for both functions.

**Comment by jigarparekh279** [comment]
Hi Jonathan,

Thanks for your reply.
I indeed wanted the indices as : 

```python
indices = chaospy.bertran.bindex(start=0, stop=order, dim=len(dist))
```
