### ISSUE TITLE
multivariate moment

### ISSUE THREAD

**Issue by jschueller** [jonathf/chaospy#216]
it seems the moment of a multivariate distribution returns one single component instead of d:
```
import chaospy as cp
d0 = cp.Triangle(2.0, 3.5, 4.0)
d1 = cp.Kumaraswamy(2.0, 3.0, -1.0, 4.0)
d2 = cp.J(d0, d1)
print(d2.mom([1,1]))
=> array(4.07142857)
```

**Comment by jonathf** [comment]
Yes, that is deliberate as ``chaospy`` supports dependent distributions where `E[XY] != E[X]E[Y]`. If you want the individual moments for each distribution, do the following:
```python
print(d2.mom([[1, 0], [0, 1]]))
```
