### ISSUE TITLE
chaospy is too verbose.

### ISSUE THREAD

**Issue by tobiasraabe** [jonathf/chaospy#217]
Hi,

thank you very much for awesome package!

chaospy skipped some versions on [conda-forge](https://anaconda.org/conda-forge/chaospy) from 3.0.12 to 3.2.4 and now it is very verbose. For example, I see this during my pytest runs

```
=============================================== test session starts ================================================
platform win32 -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.0
Using --randomly-seed=1582843781
rootdir: C:\Users\xxx, inifile: tox.ini
plugins: cov-2.8.1, datadir-1.3.1, forked-1.1.2, monkeytype-1.0.5, randomly-3.2.1, regressions-2.0.0, xdist-1.29.0
gw0 [177] / gw1 [177] / gw2 [177] / gw3 [177]
.............generating random samples using sobol rule
order: 116, dim: 4 -> shape: (4, 116)
generating random samples using sobol rule
order: 36, dim: 4 -> shape: (4, 36)
...............generating random samples using sobol rule
```
Version 3.0.12 does not print the additional information.

**Comment by jonathf** [comment]
Yes, you are right. I switched the hardcoded logging flag from warning to logging. I will switch it back on the next release.

**Comment by jonathf** [comment]
Solved in version 3.2.5.

**Comment by jonathf** [comment]
Ah, perhaps a bit too fast.

What I have done is to parameterize the logging level. During normal usage it defaults to WARNING, but I set it to DEBUG during testing, as I use it there.

You used tests as example. Was that because you need the tests to be less verbose, or the normal usage?

**Comment by tobiasraabe** [comment]
I wanted `chaospy` to have the same level of verbosity as before :) which means for me that there are no debug messages during normal usage and while testing without errors. I noticed that chaospy printed more info when an error in a test happened and this is fine.

I tested it again with the version from the master branch and everything seems fine.

```
=============================================== test session starts ================================================
platform win32 -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.0
Using --randomly-seed=1583412123
rootdir: C:\Users\xxx, inifile: tox.ini
plugins: cov-2.8.1, forked-1.1.2, randomly-3.2.1, xdist-1.29.0
gw0 [10] / gw1 [10] / gw2 [10] / gw3 [10]
..........
=============================================== 10 passed in 47.88s ================================================
```
