### ISSUE TITLE
numpoly version dependency

### ISSUE THREAD

**Issue by fjansson** [jonathf/chaospy#222]
I think chaospy has a dependency on a recent-enough numpoly version, which might not be known to pip.

I just updated chaospy from 3.2.1 to 3.2.6, using  `pip install --upgrade chaospy`
in a virtual environment. After this, chaospy would not import. My numpoly version was 0.1.6 here.
```
>>> import chaospy as cp
../uq_env/lib64/python3.7/site-packages/chaospy/__init__.py:11: in <module>
    import chaospy.bertran
../uq_env/lib64/python3.7/site-packages/chaospy/bertran/__init__.py:7: in <module>
    from numpoly import bindex
E   ImportError: cannot import name 'bindex' from 'numpoly' (/home/jansson/code/VECMA/uq_env/lib64/python3.7/site-packages/numpoly/__init__.py)
```

After manually updating numpoly to 0.1.12 chaospy works again.

**Comment by jonathf** [comment]
You are absolutely right. The dependency to numpoly is coupled tight enough that it should be bound to a specific version.

I've made a mini release 3.2.7 now with a lower bound for what version of numpoly  is required for chaospy to work.

**Comment by tostenzel** [comment]
Hey, Is it possible that this can still be a problem? When importing chaospy I obtain

`    from numpoly import bindex
  File "/home/tobias/.cache/pypoetry/virtualenvs/hypermodern-screening-QgLmLkbB-py3.7/lib/python3.7/site-packages/numpoly/__init__.py", line 3, in <module>
    from .baseclass import ndpoly
  File "/home/tobias/.cache/pypoetry/virtualenvs/hypermodern-screening-QgLmLkbB-py3.7/lib/python3.7/site-packages/numpoly/baseclass.py", line 4, in <module>
    from six import string_types
ModuleNotFoundError: No module named 'six'`

Here is a minimal script in a minimal repository using `poetry` like chaspy: [repo](https://github.com/tostenzel/hypermodern-screening/blob/chaospy_dependency/src/hypermodern_screening/foo.py). I cross-checked the script on [repl](https://repl.it). Here it works.

Thank you!

**Comment by jonathf** [comment]
@tostenzel,
That is a missing dependency. It fell under the radar, as six is pre-installed on in the docker containers used for testing.

I made another mini-release 3.2.8 where six is included in the reqs.

**Comment by tostenzel** [comment]
That did the job. Thanks for the great support and stay healthy up in the Norden.
