### ISSUE TITLE
chaospy with different types of probability distributions 

### ISSUE THREAD

**Issue by alejozen** [jonathf/chaospy#232]
Hi @jonathf :

I am not mathematician or an expert in python. So I have 2 very silly questions (I guess):

1) Is it possible to get the polynomial expansion using different types of probability distributions (normal, uniform, beta) by using `orth_ttr`?

2) I would like to know if I can use `QoI_Dist` to construct a distribution that is based on different distributions. For instance:
```
    d_qoi = cp.QoI_Dist(f_approximation, joint_dist, sample=1000)
```
where:
```
dist_A = cp.Uniform(1, 10)
dist_B = cp.Uniform(20, 25.5)
dist_C = cp.Normal(mu=0, sigma=0.5)

joint_dist = cp.J(dist_A, dist_B, dist_C)
```

Thanks for your time and for writing this very nice tool!!

**Comment by jonathf** [comment]
1. Yes. Your `joint_dist` for example is a valid input for `orth_ttr`.
2. Yes, that is what it is for.

Glad you enjoy it. :)

**Comment by alejozen** [comment]
Thank you!!
