### ISSUE TITLE
legendre polynomials from uniform distribution

### ISSUE THREAD

**Issue by Pablo-MR** [jonathf/chaospy#233]
Hi @jonathf.  I have a question about how the orthogonal polynomials for the uniform distributions are generated. It is indicated in the manual, that many of the pre-defined probability distributions in chaospy are calculated analytically. I was expecting for the case of uniform distributions to use legendre polynomials. Is there any way to generate the legendre polynomials using chaospy? Thank you in advance!

**Comment by jonathf** [comment]
Yes, should be quite straight forward:
```python
distribution = chaospy.Uniform(-1, 1)
expansion = chaospy.orth_ttr(5, distribution)
```

**Comment by Pablo-MR** [comment]
But, when I plot the polynomials, they don't look the same. And the polynomials look actually different.

**Comment by jonathf** [comment]
Orthogonal polynomials usually come in probabilist and physisist variants, which typically differs a tiny bit in form.

For example, for the physisist variant listed on Wikipedia 
https://en.wikipedia.org/wiki/Legendre_polynomials
You can do the following:
```python
expansion = expansion - expansion(1)
```
If that is not the version you are looking for, let me know what you expect Legendre to look like.

**Comment by Pablo-MR** [comment]
That's just what I needed to know. Thank you, @jonathf. And congratulations for the great work with the chaospy library. It is super useful for applied science.

**Comment by jonathf** [comment]
Thank you. I am glad you think so.
