### ISSUE TITLE
NaN calculating standard deviation for polynomial order > 2

### ISSUE THREAD

**Issue by ahenkes** [jonathf/chaospy#234]
Hi @jonathf .

For my specific problem, I have a an independent joint distribution of three normal distributions via chp.J(). I create an polynomial expansion via chp.orth_ttr(). Using pseudospectral PCE, I create nodes and weights with chp.generate_quadrature(). I than gather the solves on the quadrature nodes with my solver. Finally I use chp.fit_quadrature() to bring everything together.

Now: using polynomial order 1 & 2, I get nice results for different quadrature rules and quadrature orders.

But: using polynomial order 3 and higher, chp.fit_quadrature() produces pretty wild coefficients and I get NaN when calculating the standard deviations with chp.Std(). I already tried different quadrature rules and orders. The mean values using chp.E() are all reasonable. 

Do you have a guess whats going on here? If you need something for further clarification of the problem, please let me know.

Thank you!

**Comment by jonathf** [comment]
That doesn't sound right.

Can you give me some statistics on the evaluations you have generated. Like `np.min, np.max, np.median`. I want to know if behave sanely.

Also, are you using `sparse=True`?

**Comment by ahenkes** [comment]
"Gaussian", QOrder = 3, POrder = 2

0.18611504549820965
13716.994675842878
6795.10677385073

-7.60840931516494e-10q0^2+1.6394340778727852q1^2+5.226635975203766e-05q0q1+0.00018899944951074728q0q2-4.807880438310067e-05q0+2.4144495050972066q1q2-0.9025485834416416q2^2-0.5948998752071467q1-1.4652737075432893q2+0.4763256317516742
----------

"Gaussian", QOrder = 3, POrder = 3:

min/max/median:
0.16560710097724712
13813.261335318688
6671.79417639802

-3.9468367031186875e-13q0^3+1.1366982639107719e-07q0^2q1+8.927627345291811e-08q0^2q2-5.5866112372229226e-08q0^2-0.004308908391442307q0q1^2+21.054832702969208q1^3-0.00491285753978157q0q2^2+43.379682717888784q1^2q2-0.0069171009552382885q0q1q2-5.369667403811626q1^2+0.0029088768975041287q0q1-44.41704618138655q1q2^2+0.002990203667865664q0q2-0.0003883570852228839q0-141.21577740898366q2^3+23.022851956087038q1q2+120.6515141571488q2^2-7.25216027687748q1-33.63528149350221q2+3.501070716787008
-----

I tried different quadrature rules and high order quadrature , full and sparse. POrder 1 and 2 produces nice results for mean and std, POrder 3 and higher produces good results for mean and NaN for std

**Comment by ahenkes** [comment]
Here are good results for [mean std]:
[[9.32e+03 1.08e+03]
 [9.36e+03 974]
 [9.28e+03 1.09e+03]
 [7.22e+03 987]
 [7.19e+03 796]
 [7.11e+03 802]
 [0.269 0.025]
 [0.271 0.0351]
 [0.27 0.0343]] 

And for higher order:
 [[9.26e+03 nan]
 [8.97e+03 nan]
 [9.14e+03 nan]
 [7.14e+03 nan]
 [7.18e+03 368]
 [7.1e+03 nan]
 [0.278 nan]
 [0.271 nan]
 [0.266 nan]]

**Comment by jonathf** [comment]
What version of chaospy are you using? If you are not on the newest version, do you mind doing a `pip install -U chaospy`?

Also what are the rules that you have tried?

**Comment by ahenkes** [comment]
I am using 3.0.11. will try reinstalling.

I used (all with full and sparse):
gaussian, clenshaw_curtis, leja

**Comment by ahenkes** [comment]
using chp.gs() instead of chp.ttr results in the following error using POrder = 3:

/.local/lib/python3.6/site-packages/numpoly/array_function/multiply.py:70: RuntimeWarning: overflow encountered in multiply
  coeff1, coeff2, out=out[key], where=where, **kwargs)
/.local/lib/python3.6/site-packages/numpoly/array_function/multiply.py:67: RuntimeWarning: overflow encountered in multiply
  coeff1, coeff2, where=where, **kwargs)
.local/lib/python3.6/site-packages/numpoly/array_function/multiply.py:67: RuntimeWarning: invalid value encountered in add
  coeff1, coeff2, where=where, **kwargs)
/.local/lib/python3.6/site-packages/chaospy/descriptives/expected.py:48: RuntimeWarning: overflow encountered in multiply
  out += poly[key]*moments[idx]

**Comment by jonathf** [comment]
Those are warnings, not errors.

I think I have gone as far as I can on a theoretical level. I will need a minimal code snippet to be able to continue diagnose your problem.

**Comment by ahenkes** [comment]
Here is some code to reproduce the above warnings...maybe something is odd with the polynomial? Because the solves seem to be ok....


```
import chaospy as chp
mu1 = 5000
mu2 = 0.3
mu3 = 0.2

std1 = 0.1 * mu1
std2 = 0.1 * mu2
std3 = 0.1 * mu3

dist1 = chp.Normal(mu=mu1, sigma=std1)
dist2 = chp.Normal(mu=mu2, sigma=std2)
dist3 = chp.Normal(mu=mu3, sigma=std3)

distJ = chp.J(dist1, dist2, dist3)

poly = chp.orth_gs(order=3, dist=distJ)
```

**Comment by ahenkes** [comment]
Here is a more complete version. Maybe something is wrong with chp.fit()?

```
import chaospy as chp
import numpy as np
import tqdm

mu1 = 5000
mu2 = 0.3
mu3 = 0.2

std1 = 0.1 * mu1
std2 = 0.1 * mu2
std3 = 0.1 * mu3

dist1 = chp.Normal(mu=mu1, sigma=std1)
dist2 = chp.Normal(mu=mu2, sigma=std2)
dist3 = chp.Normal(mu=mu3, sigma=std3)

distJ = chp.J(dist1, dist2, dist3)

poly = chp.orth_ttr(order=3, dist=distJ)

nodes, weights = chp.generate_quadrature(order=5, dist=distJ, rule='gaussian')

solves = np.zeros((nodes[0].size, 9))
count = 0

with tqdm.tqdm(total=nodes[0].size) as pbar:
    for ab in nodes.T:
        solves[count, :] = custom_function(ab)
        count = count + 1
        pbar.update(1)

count_approx = 0
matpar_expectation = np.zeros((9, 1))
matpar_deviation = np.zeros((9, 1))

for loop_gp in range(9):
    approx = chp.fit_quadrature(poly, nodes, weights, solves[:, loop_gp])

    expected_pce = chp.E(approx, distJ)
    deviation_pce = chp.Std(approx, distJ)
    matpar_expectation[count_approx, 0] = expected_pce
    matpar_deviation[count_approx, 0] = deviation_pce
    count_approx = count_approx + 1
```

**Comment by jonathf** [comment]
The covariance of your distribution has a matrix condition number about `6.25e+9`. Expansion generation will likely be fragile no matter what method you use, as precision will drop too quickly with polynomial order.

But fortunately there is a workaround for this.

Create a proxy distribution that behaves nicely. Generate polynomial, nodes and weights using it instead of the one of interest. Then just transform nodes to the domain of interest using Rosenblatt. In practice:
```python
distJ = chp.J(dist1, dist2, dist3)
dist_proxy = chp.J(chp.Normal(0, 1), chp.Normal(0, 1), chp.Normal(0, 1))

poly = chp.orth_ttr(order=3, dist=dist_proxy)

nodes_proxy, weights = chp.generate_quadrature(order=5, dist=dist_proxy, rule='gaussian')
nodes = distJ.inv(dist_proxy.fwd(nodes_proxy))

# ...

for loop_gp in range(9):
    approx = chp.fit_quadrature(poly, nodes, weights, solves[:, loop_gp])

    expected_pce = chp.E(approx, dist_proxy)
    deviation_pce = chp.Std(approx, dist_proxy)
    matpar_expectation[count_approx, 0] = expected_pce
    matpar_deviation[count_approx, 0] = deviation_pce
    count_approx = count_approx + 1
```

**Comment by ahenkes** [comment]
Thank you for your suggestion! I will try it and report back!

**Comment by ahenkes** [comment]
It works! Thank you very much for your help!

**Comment by ahenkes** [comment]
Hi again @jonathf  ...
It seems that I get wrong results:
PO: 2; QO: 3; gaussian, full
 [[1.57e+04 2.68e+05]
 [1.6e+04 2.73e+05]
 [1.56e+04 2.67e+05]
 [1.22e+04 2.08e+05]
 [1.18e+04 2.01e+05]
 [1.24e+04 2.12e+05]
 [0.271 4.61]
 [0.275 4.69]
 [0.279 4.76]]

Before your suggested changes I had:

[[9.32e+03 1.08e+03]
[9.36e+03 974]
[9.28e+03 1.09e+03]
[7.22e+03 987]
[7.19e+03 796]
[7.11e+03 802]
[0.269 0.025]
[0.271 0.0351]
[0.27 0.0343]]

And MC simulation with 1e4 solves gives:

==> saves/MC_mean_10000.0.txt <==
9.263318568799639252e+03
9.230952651854320720e+03
9.196660784355330179e+03
7.170039297102256569e+03
7.103657701772908695e+03
7.192453904849487117e+03
2.710156261211824069e-01
2.705425859413232437e-01
2.696775401092185165e-01

==> saves/MC_std_10000.0.txt <==
1.147294853945655859e+03
1.140805523182353227e+03
1.154542273620388414e+03
9.299842485512206167e+02
9.162014327695475231e+02
9.155133706805162319e+02
3.256899785572986428e-02
3.199946833394718554e-02
3.100193958158752386e-02

------
This is my routine:

```
import chaospy as chp
import numpy as np
import tqdm

mean1 = 5000
mean2 = 0.3
mean3 = 0.2

std1 = 0.1 * mean1
std2 = 0.1 * mean2
std3 = 0.1 * mean3

dist1 = chp.Normal(mu=mean1, sigma=std1)
dist2 = chp.Normal(mu=mean2, sigma=std2)
dist3 = chp.Normal(mu=mean3, sigma=std3)

distJ = chp.J(dist1, dist2, dist3)
dist_proxy = chp.J(chp.Normal(0, 1), chp.Normal(0, 1), chp.Normal(0, 1))

poly = chp.orth_ttr(order=2, dist=dist_proxy)

nodes_proxy, weights = chp.generate_quadrature(order=3, dist=distJ, rule="gaussian")
nodes = distJ.inv(dist_proxy.fwd(nodes_proxy))

solves = np.zeros((nodes[0].size, 9))
counter_pce = 0
with tqdm.tqdm(total=nodes[0].size) as pbar:
    for ab in nodes.T:
        solves[counter_pce, :] = custom_function(ab)
        counter_pce = counter_pce + 1
        pbar.update(1)

count_approx = 0
matpar_expectation = np.zeros((9, 1))
matpar_deviation = np.zeros((9, 1))
for loop_gp in range(9):
    approx = chp.fit_quadrature(poly, nodes, weights, solves[:, loop_gp])

    expected_pce = chp.E(approx, dist_proxy)
    deviation_pce = chp.Std(approx, dist_proxy)
    matpar_expectation[count_approx, 0] = expected_pce
    matpar_deviation[count_approx, 0] = deviation_pce
    count_approx = count_approx + 1
```

Is there everything correct with the _proxy?

Thank you again

**Comment by ahenkes** [comment]
Maybe you have to use the "nodes_proxy" for fitting?

**Comment by jonathf** [comment]
Quick look here:
https://chaospy.readthedocs.io/en/master/recipes/dependent.html#pseudo-spectral-projection
(Getting a better tutorial for this in place is on my todo list.)

I skipped readjusting the weights, as I though it didn't matter as they should be the same in this case, but I am realizing I might be wrong.

As you are pointing out, yes `nodes_proxy` is the one that should be passed to `fit_quadrature`. Glad you catched my mistake.

Does fixing these two things fix the problem?

**Comment by ahenkes** [comment]
I think using `nodes_proxy` did the thing, because my results are resonable again. I didn't adjust the weights though because I got this error:
```

  File "deep_learning_pce.py", line 707, in <module>
    matpar_mu, matpar_sigma = polynomial_chaos_expansion(cf_user)
  File "deep_learning_pce.py", line 79, in polynomial_chaos_expansion
    weights = dist_independent.inv(dist_proxy.fwd(weights_proxy))
  File "/usr/local/lib/python3.6/dist-packages/chaospy/distributions/baseclass.py", line 119, in fwd
    x_data = x_data.reshape(len(self), -1)
ValueError: cannot reshape array of size 64 into shape (3,newaxis)
```

Which is of course due to the dimension mismatch, as `weights` are same for all dimensions and seem to be implemented as one dimensional array. At the moment I think, the weights don't have to be adjusted. What do you think?

**Comment by jonathf** [comment]
Good!

I don't think so either, as source and target distribution should be the same. But I might be wrong, as it has been a while since the last time I played with G-PCE.

**Comment by ahenkes** [comment]
So using the code in the tutorial to transform the weights I get `nan` for `weights_q`:
```
RuntimeWarning: invalid value encountered in true_divide
  weights_q = weights_r*dist_q.pdf(nodes_r)/dist_r.pdf(nodes_q)
```
because `dist_r.pdf(nodes_q)` is all zero

**Comment by jonathf** [comment]
A typo, try this instead:
```
weights_q = weights_r*dist_q.pdf(abscissas_q)/dist_r.pdf(abscissas_r)
```

I'll correct the tutorial.

**Comment by ahenkes** [comment]
Thank you for your help. It works now. The weights don't affect the solution.
