### ISSUE TITLE
Difference in quad weights between 3.0.17 and 3.2.10

### ISSUE THREAD

**Issue by wedeling** [jonathf/chaospy#241]
In EasyVVUQ, we changed to chaospy 3.2.10 from 3.0.17. The quadrature weights changed, at least for Uniform distributions:

New chaospy 3.2.10, quad weight for uniform dist, order 0 and 1
```
In [6]: cp.generate_quadrature(0, cp.Uniform(0.9, 1.1), "C", growth=True)
Out[6]: (array([[1.]]), array([1.]))

cp.generate_quadrature(1, cp.Uniform(0.9, 1.1), "C", growth=True)
Out[7]: (array([[0.9, 1. , 1.1]]), array([0., 1., 0.]))
```
Old chaospy (3.0.17), quad weight for uniform dist, order 0 and 1

```
cp.generate_quadrature(0, cp.Uniform(0.9, 1.1), "C", growth=True)
Out[2]: (array([[1.]]), array([1.]))

cp.generate_quadrature(1, cp.Uniform(0.9, 1.1), "C", growth=True)
Out[3]: (array([[0.9, 1. , 1.1]]), array([0.16666667, 0.66666667, 0.16666667]))
```
Note that in the new version the weights are zero at the edges for order 1. Similar behavior occurs at higher order. With these new weights some of the EasyVVUQ samplers do not work properly.

Another thing I noticed is this:

```
cp.generate_quadrature(1, cp.Uniform(0.9, 1.1))
/home/wouter/.local/lib/python3.7/site-packages/chaospy-3.2.10-py3.7.egg/chaospy/quadrature/clenshaw_curtis.py:107: RuntimeWarning: invalid value encountered in true_divide
  weights /= numpy.sum(weights)
Out[20]: (array([[0.9, 1.1]]), array([nan, nan]))
```
This used to work in 3.0.17, now it gives nan as weights.

**Comment by jonathf** [comment]
Yeah, I saw it when you tagged me on your issues tracker.

That is somewhat of a subtle bug, and the two errors you are describing has the same source.

It is easy to fix though. Testing a patch now:
https://github.com/jonathf/chaospy/pull/242

**Comment by jonathf** [comment]
Version 3.2.12 is now released with a fix in place.

Feel free to reopen if the bug still persists.
