### ISSUE TITLE
Pseudospectral Approach Quadrature Order

### ISSUE THREAD

**Issue by ahenkes1** [jonathf/chaospy#254]
Hello,

I just looked in your new tutorials. For the pseudospectral approach I have a little question:

First you use quadrature order = 8 and polynomial order = 4 and in the error convergence study you choose them to be equal. How did you choose the quadrature order (m-1) w.r.t. polynomial order (p)? As far as I understand, p <= 2m - 1 holds, which would result in a much lower order of quadrature and thus less nodes to evaluate you model on. What am I missing?

**Comment by jonathf** [comment]
The dies of `p <= 2m-1` is an abstract idea from 1D problems with exact polynomial solutions. Most applications are neither 1D nor polynomial, so something else have to be used. what that should be, is not obvious to me. I've seen different conventions, and I think there is no one-size-fit all for this issue.

But if you like my two cents:
Select polynomial order `p` as large as possible given that `N+1 <= m*K`, where `N+1` is the number of polynomial terms and `K` is some multiplier typically in `{1, 2, 4}`.
Simple problems can be done with `K=1`, while complicated problems is solved with `K=4`.

I'll update to tutorial to not have the 4/8 mismatch, and I might add a section on sample selection later.

**Comment by ahenkes1** [comment]
Thank you for your reply.
