### ISSUE TITLE
poly_divmod infinite loop

### ISSUE THREAD

**Issue by mmanzi95** [jonathf/chaospy#257]
Hello,

I'm having problems with polynomial divisions. I am not able to exit the While loop in the poly_divmod, that is, it the "get_division_candidate" function I reach a point in which idx2, exponent2, include2, idx, exponent, idx1, exponent1 are all zero and I keep going. 

I'm calling this function inside a propagator and I get this behaviour only for certain inputs, not always.
I've tried to reduce the complexity of the problem, going back to polynomials of degree 0, and I still get the same issue. The problematic call is:

"polynomial(-1.715408531156317e+18) / polynomial(3.097893826691672e+18)"

Thank you

**Comment by jonathf** [comment]
Bug in Numpoly backend: jonathf/numpoly#64
Addressed there.

**Comment by mmanzi95** [comment]
Sorry, not sure if this is a related issue, but I am also not able to compute the following:

(24 * 3600)**2 * 398600.4415 / polynomial(2.689498059130061e-63*q0**2+4.351432444850692e-27*q0+1760083471.506941)

since I get "polynomial(0.0)".
Thank you, 
Matteo

**Comment by mmanzi95** [comment]
Changing "x2.coefficients[idx] == 0" to "x2.coefficients[idx] < 1e-20" in get_division_candidate solved it for me.

Matteo

**Comment by jonathf** [comment]
> Changing "x2.coefficients[idx] == 0" to "x2.coefficients[idx] < 1e-10" in get_division_candidate seems to have solved it.
> 
> p.s. I guess keeping the == and applying the .around() to the various terms is a smarter move..

My first proposal like yours relies on rounding to work. That is a bit dangourous as it is hard to predict edge cases where the rounding causes new unintended bugs. The update solution should not depend on roudning anymore and fix the problem.

> Sorry, not sure if this is a related issue, but I am also not able to compute the following:
> 
> (24 * 3600) ** 2 * 398600.4415 / polynomial(2.689498059130061e-63_q0**2+4.351432444850692e-27_q0+1760083471.506941)
> 
> since I get "polynomial(0.0)".

The division A/(B*X**2 + C*X + D) should be:
divided = 0
remainder = A
In other words, the solution you are getting looks correct to me.

**Comment by jonathf** [comment]
Solved in #260.
