### ISSUE TITLE
unequal quadrature weights DiscreteUniform

### ISSUE THREAD

**Issue by wedeling** [jonathf/chaospy#258]
Hi @jonathf 

This is more a question than an issue perhaps, but why does `cp.DiscreteUniform` generate unequal quadrature weights? For instance:

```python
In: cp.generate_quadrature(2, cp.DiscreteUniform(1,3))
Out: (array([[1, 2, 3]]), array([0.16666667, 0.66666667, 0.16666667]))
```

The mean and variance of this example should be 2 and 2/3 respectively, and `cp.E(cp.DiscreteUniform(1,3))` and `cp.Var(cp.DiscreteUniform(1,3))` do give the correct results. If I use the generated quadrature weights however, I get this result:

```python
xi, wi = cp.generate_quadrature(2, cp.DiscreteUniform(1,3))

np.sum(xi*wi)
Out: 2.0

np.sum((xi-2.0)**2*wi)
Out: 0.33333333333333337
```

The mean is correct, but the variance is not. Equal quadrature weights do give the correct answer:

```python
np.sum((xi-2.0)**2*(1/3))
Out: 0.6666666666666666
```

**Comment by jonathf** [comment]
Discrete distributions and quadrature weights is a bit of a weird match.
Quadrature nodes build on approximation assumption about continous polynomial representation (or close to that) for the integration to work. Discrete distribution assumes countable states and unless states are large and some approximation to continous function is used, is not really compatible with quadrature rules.

So yes, using quadrature with DiscreteUniform works poorly.

Using `xi=nparange(lo, up+1)` and `wi=np.ones(len(x1))/len(x1)`, as you insinuate, will give you the analytical results. This holds true for all finite state discrete distributions.

If this is for EasyVVUQ and you guys need a way to ensure that discrete distribution get the correct quadrature rule automatically, I can make a proposal for a solution for you guys, if you are interested.

**Comment by wedeling** [comment]
Thanks for your quick reply. I am indeed using this for EasyVVUQ, where I use chaospy to build the 1D quadrature rules for a (sparse/adaptive) Stochastic Collocation sampler. A proposal solution would be great.

**Comment by jonathf** [comment]
@wedeling, I've created #259 with the feature I am proposing.

* The example you posted should now work perfectly out of the box.
* if you have multivariate distribution which mixes continuous and discrete variables, the correct scheme will be automatically selected as needed, is the `rule` flag is not passed.
* If the user provides the `rule` flat, using the scheme `discrete`for all discrete distributions will give the correct behavior.

As noted in the PR, the methods `dist.fwd` and `dist.inv` have breaking changes made to them. Let me know if that is a concern that needs to be addressed.

**Comment by wedeling** [comment]
Great! I'll test it now

**Comment by jonathf** [comment]
Featue added in Chaospy version 3.3.5.
