### ISSUE TITLE
How to use orthogonal polynomials to describe a distribution

### ISSUE THREAD

**Issue by mmanzi95** [jonathf/chaospy#261]
Hello,

is there an easy/better way of doing the following in chaospy?

After performing a propagation with respect to a number of uncertain parameters, I get a distribution related to the initial uncertain space through PCE. I would now like to get rid of the initial source of uncertainty and use the current state distribution as an input for the next step of the PCE. I was thinking I could generate a number of samples, perform fit_regression() with respect to a polynomial basis expressed in terms of the current state (not the initial one), and get an approximation of the current distribution to be later used as a source of uncertainty. But in this way, the polynomial object could not be used as a distribution (e.g. as an input of the cp.E() function).

Thank you very much,
Matteo

**Comment by flo2k** [comment]
Hello,

This sounds very much that you could give the QoI_Dist() function a try: https://chaospy.readthedocs.io/en/master/descriptives.html#miscellaneous

Let me know if it works for you.

**Comment by mmanzi95** [comment]
Great! Looks like what I was looking for, thank you very much, let me try it out.

**Comment by mmanzi95** [comment]
Hello, 
it does not appear to work accurately enough on a simple toy problem.
I have a 
distribution = cp.Normal(0, 1) of the variable q0, and a variable x = 0.009722248451937806*q0+1.0. I compute test1 = cp.Var(x, distribution) and I get  0.040806322451597814.
I then use qoi_dist = cp.QoI_Dist(x, cp.Normal(0, 1)) and the associated xk = cp.variable() to compute test2 = cp.Var(xk, qoi_dist) but I get 0.04201063.

I was thinking about alternative solutions. For example, make use of only the moments of xk to compute the orthogonal basis w.r.t xk and averages with respect to its distribution. Is this easily implementable in chaospy?

Thank you very much for the great work,
Matteo

**Comment by flo2k** [comment]
The QoI_Dist() function has an additional parameter `sample` which defaults to 10000. You could try to increase this number. Does this improve your test case?

**Comment by mmanzi95** [comment]
Yes, sorry, I forgot to mention that I had already tried to do so: indeed, the error gets smaller, but the computation becomes too expensive for me.

**Comment by jonathf** [comment]
@mmanzi95, I am trying to reconstruct your toy example:
```python
import numpy as np
import chaospy as cp

np.random.seed(1234)

distribution = cp.Normal(0, 1)
q0 = cp.variable()
x = 0.009722248451937806*q0+1.0
print(cp.Var(x, distribution))
# 9.452211496120706e-05

qoi_dist = cp.QoI_Dist(x, cp.Normal(0, 1))
print(cp.Var(q0, qoi_dist))
# 9.701814298834766e-05
```

Can you comment on what I need to change to get the 0.040 vs 0.042 discrepency?

**Comment by mmanzi95** [comment]
Apologies, not sure why I got the wrong value:

x = polynomial(0.20200574856077194*q0+1.0)

**Comment by jonathf** [comment]
> I was thinking about alternative solutions. For example, make use of only the moments of xk to compute the orthogonal basis w.r.t xk and averages with respect to its distribution. Is this easily implementable in chaospy?

That is an excellent question. My intusition tells me it should be possible through `cp.QoI_Dist`, but looking at the code, looks like it isn't implemented. I made branch `qoi` where it is possible to do:
```python
expansion = cp.orth_chol(order, qoi_dist)
```
Which uses the raw moments of the underlying data instead of the initial uncertainty.

We could look at doing the same from the polynomial itself, but then you don't get rid of the initial uncertainty.

> Apologies, not sure why I got the wrong value:
> 
> x = polynomial(0.20200574856077194*q0+1.0)

Okay, that makes more sense.
I get a little bit smaller error than you. I guess that is the random seed.

**Comment by jonathf** [comment]
Technical detail: you don't need the `qoi` branch for running the code. But without it, momemts will be created by integrating the KDE distributrion, which is really slow and larger errors.

**Comment by mmanzi95** [comment]
Thank you very much. Sorry for the late reply but I'm now focusing on a different approach. I would say the issue is closed, at least for me.

Thank you again,
Matteo
