### ISSUE TITLE
StochasticallyDependentError

### ISSUE THREAD

**Issue by Jingfei-Liu** [jonathf/chaospy#263]
Hi Jonathan：

I have got a problem recently and I hope you can give some kindly guideness. 

When I run the following codes, I got "StochasticallyDependentError" : 

import chaospy as cp

a=0.86558486*cp.Normal(-0.02663545823418139,0.09360906)+0.12743674*cp.Normal(0.011532629286901575,0.48983097)

order=3

P, norms = cp.orth_ttr(order, a, retall=True, cross_truncation=1)

or add the transformation cp.J():

b=cp.J(a)

P, norms = cp.orth_ttr(order, b, retall=True, cross_truncation=1)

The error messege is
" File "C:\Users\LjfPy\Anaconda3\lib\site-packages\chaospy\distributions\operators\addition.py", line 274, in _ttr
    "{} and {}".format(left, right) "

Why this error occurs and how can I overcome it? Could you please give me some help? 

Thank you very much,

Best regards!

**Comment by jonathf** [comment]
The canonical three-terms recurrence algorithms do not play nice with stochastically dependent distributions.
You will need to switch to an algorithm that does support it. For example `cp.orth_chol`.

I would say that you have a "incomplete" distribution, but I think for the case of generating polynomials, the incompltion is not an issue, and ust swapping `orth_ttr` with `orth_chol` should do the job.

**Comment by Jingfei-Liu** [comment]
Thank you very much！ It does work.
