### ISSUE TITLE
TypeError: fit_regression() got an unexpected keyword argument 'rule' when using uncertainpy with chaospy

### ISSUE THREAD

**Issue by philomatic95** [jonathf/chaospy#267]
Hello,

I hope it is okay that I am opening this issue with regard to chaospy as it seem like the TypeError is thrown by this library due to being called upon by uncertainpy. 

After finally having managed to install uncertainpy and all its requirements on windows I ran the following code:

`if __name__ == '__main__':
    
    def janosi_model(c, k, phi):
        path = 'censored'
        location = sys.argv[1]
        moisture = sys.argv[2]
        path = 'censored'

        #determine number of samples 
        pFile = path + "p.txt"
        p = np.loadtxt(fname=pFile)
        jFile = path + "j.txt"
        j = np.loadtxt(fname=jFile)
        Y = np.zeros(len(j))
        def f(c,k,phi,j,p):
            for i in range(len(j)):
                Y[i] = (c+p[i]*math.tan(phi))*(1-math.exp(-j[i]/k))
            return Y
         
        tau=f(c,k,phi,j,p)
        return None, tau

    mod = un.Model(run=janosi_model)

    c_dist = cp.Uniform(0,30000)
    k_dist = cp.Uniform(0,0.0017)
    phi_dist = cp.Uniform(0,20)

    params = {"c": c_dist, "k": k_dist, "phi": phi_dist}

    UQ = un.UncertaintyQuantification(model=mod, parameters=params)

    data = UQ.quantify(method="mc",seed=10)

    print(UQ)`

However, I get the following error:

> Traceback (most recent call last):
  File "SA_un.py", line 52, in <module>
    data = UQ.quantify(seed=10)
  File "C:\Users\phil\AppData\Local\Programs\Python\Python38\lib\site-packages\uncertainpy-1.2.1-py3.8.egg\uncertainpy\uncertainty.py", line 415, in quantify
  File "C:\Users\phil\AppData\Local\Programs\Python\Python38\lib\site-packages\uncertainpy-1.2.1-py3.8.egg\uncertainpy\uncertainty.py", line 702, in polynomial_chaos
  File "C:\Users\phil\AppData\Local\Programs\Python\Python38\lib\site-packages\uncertainpy-1.2.1-py3.8.egg\uncertainpy\core\uncertainty_calculations.py", line 1353, in polynomial_chaos
  File "C:\Users\phil\AppData\Local\Programs\Python\Python38\lib\site-packages\uncertainpy-1.2.1-py3.8.egg\uncertainpy\core\uncertainty_calculations.py", line 647, in create_PCE_collocation
TypeError: fit_regression() got an unexpected keyword argument 'rule'<

I tried to trace it back and understand the code to the very best of my ability. As far as I understood, the actual error is thrown in line 647 in create_PCE_collocation. 
`if (np.all(mask) or allow_incomplete) and sum(mask) > 0:
                U_hat[feature] = cp.fit_regression(P, masked_nodes,
                                                   masked_evaluations, rule="T")`
So the function fit_regression from the chaospy library is called. 
It is defined as `def fit_regression(
        polynomials,
        abscissas,
        evals,
        model=None,
        retall=False,
):`
While the first parameters passed, P, masked_nodes, masked_evaluations, seem to correspond to the expected ones, I am not quite sure how and where the 'rule="T"' argument comes into play. Furthermore, I could not find this TypeError within "regression.py" so I am not quite sure where this error is actually thrown. 

I just tried running the simulation with MC instead of CP and it worked fine. 

I have the following version of chaospy installed: 
> Requirement already satisfied: chaospy in c:\users\phil\appdata\local\programs\python\python38\lib\site-packages (3.3.6)
Requirement already satisfied: numpoly==1.0.5 in c:\users\phil\appdata\local\programs\python\python38\lib\site-packages (from chaospy) (1.0.5)
Requirement already satisfied: numpy in c:\users\phil\appdata\local\programs\python\python38\lib\site-packages (from chaospy) (1.18.4+mkl)
Requirement already satisfied: scipy in c:\users\phil\appdata\local\programs\python\python38\lib\site-packages (from chaospy) (1.5.2)
Requirement already satisfied: six in c:\users\phil\appdata\local\programs\python\python38\lib\site-packages (from numpoly==1.0.5->chaospy) (1.15.0)< 

I hope I have added all the required information and do apologize if not as this is my very first issue I have submitted. 

edit: actually, the more I think about it I should have rather opened this issue with regard to uncertainpy as it is that library who passes these arguments among which the faulty one is. Will still just wait for your answer before opening a second issue as you might still now a solution to this issue.

**Comment by jonathf** [comment]
This is indeed a Uncertainpy issue, but it comes from a deprecation in Chaospy.
The "T" is no more, as `scikit-learn` does regularization a lot better.
I've made a tutorial listing up how to use `sklearn.linear_model` together with `chaospy` here:
https://chaospy.readthedocs.io/en/master/tutorials/advanced/scikitlearn_regression.html
The "T" uses an L2-regularizaation, making it roughly equivalent to `Ridge` in the tutorial.

@simetenn, do you want to make a patch to Uncertainpy, or should I?

**Comment by simetenn** [comment]
Thanks for the notice! I will take a look :)

**Comment by simetenn** [comment]
This is fixed in the newest version of Uncertainpy (1.2.3). Thank you for your patience, I completely forgot to report back here once it was done.
