### ISSUE TITLE
quadrature weights for CC and standard uniform input

### ISSUE THREAD

**Issue by wedeling** [jonathf/chaospy#268]
Hi @jonathf ,

If I generate a 1D clenshaw curtis quad rule for a standard normal input as follows:

```python
cp.generate_quadrature(2, cp.Normal(), rule="C", growth=True)
Out[20]: 
(array([[-7.5       , -5.30330086,  0.        ,  5.30330086,  7.5       ]]),
 array([5.08494194e-14, 5.20765418e-07, 9.99998958e-01, 5.20765418e-07,
        5.08494194e-14]))
```

I get nodes which seem very far removed from the mean, with very small weights. Changing the rule to "G" produces results like I would expect.

**Comment by jonathf** [comment]
Clenshaw-Curtis is a bound quadrature rule that includes endpoints. Applied on an unbound Normal distribution means that +/- inf should be included, which is a bit nonsensical.

Chaospy doesn't deal with infinity directly and instead use wide bounds that are good enough for numerical applications. That is what you are observing here in your example.

I would note that CC is a bad match for unbound distributions in general, but if you need it, I suggest you instead switch to Fejer in those cases. Fejer is the same as CC, but with the endpoints removed.

**Comment by wedeling** [comment]
I see, thanks for that. Makes sense.
