### ISSUE TITLE
How to reset sampling so it give me different values when running in a loop

### ISSUE THREAD

**Issue by mayejudi** [jonathf/chaospy#279]
```python
import numpy as np
from matplotlib import pyplot
import chaospy as cp

size = 1024
dim = 2
iter = 5
pyplot.ion()
for ii in range(0,5):
   pyplot.figure()
   distribution = cp.J(cp.Uniform(0, 1), cp.Uniform(0, 1))
   points = distribution.sample(size, rule="halton")
   pyplot.scatter(*points[:, :size], marker="x", color="k")
   pyplot.xlabel("init (normal)")
   pyplot.ylabel("rate (uniform)") 
   pyplot.axis([0, 1, 0, 1])
   pyplot.title('halton')
   pyplot.savefig('C:/QRS-results/fig_'+str(ii))
   pyplot.pause(1)
```
However the plots are identical, I was expecting the points to change from one iteration to the next. How I can make it show different values every time the loop runs.

**Comment by jonathf** [comment]
That behvior is a design choice to make analysis using different orders directly comparable.
Getting the behavior you want can be done easily by modifying your script just a little bit:
```python
import numpy as np
from matplotlib import pyplot
import chaospy as cp

size = 1024
dim = 2
iter = 5
points = distribution.sample(size*iter, rule="halton").reshape(dim, iter, size)
pyplot.ion()
for ii in range(0,5):
   pyplot.figure()
   distribution = cp.J(cp.Uniform(0, 1), cp.Uniform(0, 1))
   pyplot.scatter(*points[:, ii, :size], marker="x", color="k")
   pyplot.xlabel("init (normal)")
   pyplot.ylabel("rate (uniform)") 
   pyplot.axis([0, 1, 0, 1])
   pyplot.title('halton')
   pyplot.savefig('C:/QRS-results/fig_'+str(ii))
   pyplot.pause(1)
```

**Comment by mayejudi** [comment]
Thank you very much for your answer. I see that you need to know the number of iterations ahead of time. However how do you do when you have  a system in which there is an optimization scheme that stop the iteration, so the number of iterations are not known ahead of time? I suppose that ```iter``` value might be a large enough number. However when efficiency is a must, you might end up with a bunch of unnecessary operations.

**Comment by jonathf** [comment]
That isn't feasable for all sampling schemes siply by the nature of what they are. But for Halton in particular on standard uniform distribution, you could use the lower level interface:
```python
from chaospy.distributions.sampler.sequences.halton import create_halton_samples

burnin = 117
create_halton_samples(5, dim=2, burnin=burnin)
# array([[0.4296875 , 0.9296875 , 0.1171875 , 0.6171875 , 0.3671875 ],
#        [0.38683128, 0.72016461, 0.16460905, 0.49794239, 0.83127572]])
create_halton_samples(2, dim=2, burnin=burnin)
# array([[0.4296875 , 0.9296875 ],
#        [0.38683128, 0.72016461]])
create_halton_samples(3, dim=2, burnin=burnin+2)
# array([[0.1171875 , 0.6171875 , 0.3671875 ],
#        [0.16460905, 0.49794239, 0.83127572]])
```

The burnin value is somewhat arbitrary, but needs to be larger when the number of dimensions grows.

**Comment by mayejudi** [comment]
Thank you very much!
