### ISSUE TITLE
PCE with dependent input parameters

### ISSUE THREAD

**Issue by Tangzl922** [jonathf/chaospy#301]
Hi Jonathf,
I've met a problem about PCE with denpendent input parameters. Suppose we have a nested addition model, where x1,x2,x3,x4 are all independent parameters with a Uniform distribution from(0, 5). Then we have models x5 = x1+2*x2 and x6 = 3*x2+4*x3+5*x4. These are easy to implement. However by the next step, we have a model x7 = 6*x5+7*x6+8*x4, and here are three dependent parameters(x5, x6, x4). How to implement the PCE in this case? 
Here are my codes with `errors.

```python
import numpy as np
import chaospy as cp

def model_x5(x1,x2):
    return 1*x1+2*x2

def model_x6(x2,x3,x4):
    return 3*x2+4*x3+5*x4

def model_x7(x5,x6,x4):
    return 6*x5+7*x6+8*x4

x1 = cp.Uniform(0,5)
x2 = cp.Uniform(0,5)
x3 = cp.Uniform(0,5)
x4 = cp.Uniform(0,5)

x5 = model_x5(x1,x2)
x6 = model_x6(x2,x3,x4)

distribution = cp.J(x5,x6,x4)

polynomials = cp.orth_ttr(3,distribution)
print(polynomials)
nodes, weights = cp.generate_quadrature(4, distribution, rule='G')
samples_u = [model_x6(*node) for node in nodes.T]

u_hat = cp.fit_quadrature(polynomials, nodes, weights, samples_u)

print(cp.Sens_m(u_hat, distribution))
```

And I got the StochasticallyDependentError.

**Comment by jonathf** [comment]
There are a few things going on here.

* `orth_ttr` does not support dependencies. Use `orth_chol` instead.
* `distribution` is not well defined here. Length of distribution must much length of number of variables. E.g. `cp.J(x1, x2, x3, x4, x5, x6)` is valid.
* `rule="G"` assumes independence. For your case, switch it to e.g. `rule="clenshaw_curtis"`.
* Sobol indices and dependent variables is a bit of a difficult topic that is currently being worked on. In your case, you will get incorrect values for x5 and x6. And there is no simple way around that. Other statistics like E, Var, Cov etc. works fine though.
* Should `samples_u` be defined in ter terms of `model_x7`? Or are you actually analyzing x6 as a function of x6 and others?

**Comment by Tangzl922** [comment]
Ah, yes, it should be model_x7.
Thank you for your help!
