### ISSUE TITLE
Sampling a joint distribution containing a discrete distribution gives non-integer values

### ISSUE THREAD

**Issue by fjansson** [jonathf/chaospy#303]
```
import chaospy as cp
N = cp.Uniform(50, 100)
seed = cp.DiscreteUniform(1, 2000)
j = cp.J(N, seed)
j.sample(10)
```
Returns this, where the seed samples are non-integer:
```
array([[  83.60746283,   81.28286667,   54.93770224,   81.54784429,
          91.50222779,   99.09912877,   89.32286419,   61.63314081,
          53.12798169,   59.48945316],
       [1701.37552108, 1842.2456103 , 1863.33264069,  134.77264764,
        1527.74731926, 1505.45322541,  196.89872698,  513.16150195,
         713.0349854 , 1769.64793344]])
 ```
Tested with chaospy 3.3.6 and 4.2.0.

**Comment by jonathf** [comment]
The way chaospy works internally, discrete variables have to be represented as continous variables. So to "fake" the corret behavior, a continous variable with all the correct properties is used instead, and at the end coverted to integers.

So this is an edge case is clearly incorrectly handled. Bugfix added to 4.2.1.
