### ISSUE TITLE
Unexpected representation of triangle distribution

### ISSUE THREAD

**Issue by yoelcortes** [jonathf/chaospy#314]
**Describe the bug**

Unexpected representation of triangle distribution

**To Reproduce**

```python
>>> from chaospy.distributions import Triangle
>>> Triangle(0, 1.1, 2)
Triangle(0, 0.55, 2)

```

**Expected behavior**

```python
>>> from chaospy.distributions import Triangle
>>> Triangle(0, 1.1, 2)
Triangle(0, 1.1 2)

```

**Desktop:**
 - OS: Windows
 - Python version: 3.8.5
 - Chaospy version 4.2.2

**Additional context**

I realize the `_repr` attribute from v3 of chaospy is gone. I found it useful for bookkeeping distributions and creating a dataframe of all the distributions being used... Is there a simple way to get the values used to create the distributions?

 Thanks!

**Comment by jonathf** [comment]
Try again with Chaospy version 4.2.3. Triangle repr should be fixed.

The `_repr` argument is gone, yes. The way the code was structured made it obsolete code wise.
But a variant of the attribute is stored in `_repr_args`, though unfortunatly it is only a list of values and not the key-value dict you are used to.

**Comment by yoelcortes** [comment]
Perfect, thanks!
