### ISSUE TITLE
Error using generate_quadrature 

### ISSUE THREAD

**Issue by John3221** [jonathf/chaospy#324]
Hi,

I am trying to generate sampling points and weights using the `rule = 'gauss_kronrod'` quadrature scheme, however I seem to get an error that I dont fully understand: 
`LinAlgError: Invalid recurrence coefficients can not be used for constructing Gaussian quadrature rule` 

Here is a minimal code to replicate the error:

```
import chaospy as cp
n = 4 
order = 3 
normal_distribution = cp.Normal(0,1)
joint_dist = cp.Iid(normal_distribution,n)
quadratures, weights = cp.generate_quadrature(order, joint_dist, rule = 'gauss_kronrod', sparse = True)
```

Am I doing something fundamentally wrong here? Should Kronrod not be used in conjunction with Normal distributions?  

Thanks in advance!

**Comment by jonathf** [comment]
Kronrod should not b used with Normal distribution. From the chaospy docs on Kronrod:

```
    The algorithm is well suited for any Jacobi scheme, i.e. quadrature
    involving Uniform or Beta distribution, and might work on others as well.
    However, it will not work everywhere. For example `Kahaner and Monegato
    <https://link.springer.com/article/10.1007/BF01590820>`_ showed that higher
    order Gauss-Kronrod quadrature for Gauss-Hermite and Gauss-Laguerre does
    not exist.
```

**Comment by John3221** [comment]
Thanks for your prompt response!
