### ISSUE TITLE
Flipped LogNormal distribution

### ISSUE THREAD

**Issue by marcrocasalonso** [jonathf/chaospy#328]
**Describe your problem**
I want to flipp a LogNormal distribution.

**Initial implementation**
sigma=0.6
mu=0.8
h6=cp.LogNormal(mu, mu*sigma, shift=0.7, scale=0.1) #random variable h6

**Additional context**
My idea is create a LogNormal distribution with the long tail situated in the left are of the distribution.
How can I do it with Chaospy?

Thanks in advance Jonathan

**Comment by jonathf** [comment]
Have you tried adding a negative sign in front of the distribution:
```python
h6 = -cp.LogNormal(mu, mu*sigma, shift=0.7, scale=0.1)
```

**Comment by marcrocasalonso** [comment]
With negative sign you make a distribution simmetry with respect the axis zero. Then you obtain all the distribution in the negative region. I only want to have the long tail of the lognormal in the left area.I am sorry if I did not explain correctly.
Thanks in adavance,
Marc

**Comment by marcrocasalonso** [comment]
My idea is, fit a LogNormal distribution with:
Median=0.9
inferior limit=0.70
superior limit=0.97

**Comment by marcrocasalonso** [comment]
Something like that:
h6=cp.LogNormal(mu, sigma, shift=0.7, scale),

but I want with the lower bound 0.7 in the long tail. I want to start in 0.97 an decrese the lognormal to 0.7.

Thank you very much

**Comment by jonathf** [comment]
For the matching of median and limits, that is fitting question. You could try solving this as a optimization problem. A quick optimization by hand, gave me:
```python
dist = chaospy.Trunc(0.97-cp.LogNormal(-2.7, 0.2), lower=0.7)
```
If you want to be more rigouriuous, I suggest you use something like `scipy.optimize.fmin` to find the parameters more accuratly.

**Comment by marcrocasalonso** [comment]
Thank you very much. I will try it! :)
