### ISSUE TITLE
Can't construct reciprocal of uniform distribution

### ISSUE THREAD

**Issue by robertsawko** [jonathf/chaospy#33]
Hi,

I am trying the following code

```python
viscosity_rv = 1.0 / Uniform(907, 1232)
```

But unfortunately `generate_quadrature` crashes with the following error:
```
/home/rsa/.local/lib/python2.7/site-packages/chaospy/dist/operators.py:699: RuntimeWarning: divide by zero encountered in reciprocal
  y = np.sign(x)*np.abs(x)**(1./num)
/home/rsa/.local/lib/python2.7/site-packages/chaospy/dist/operators.py:699: RuntimeWarning: invalid value encountered in multiply
  y = np.sign(x)*np.abs(x)**(1./num)
```

**Comment by jonathf** [comment]
I will take a look.

To be able to replicate the problem, do you mind providing me with the following information:

Could you provide a minimal example that caused the error?
What python version are you running?
On what OS are you on?

**Comment by robertsawko** [comment]
Thanks for a quick reply. This is a minimal example I concocted:
```python
from chaospy import Uniform, generate_quadrature

rv = 1 / Uniform(1, 2)
node, abcissa = generate_quadrature(3, rv)
print(node, abcissa)
```
My Python version is 2.7.12 and I am on Arch Linux with reasonably latest updates.

**Comment by jonathf** [comment]
Okay. I think I understand what is going on here, but the solution to it would require a little more time than I have currently. I will likely have a fix ready in a week or two. I'll keep you posted.

**Comment by jonathf** [comment]
I have now made a fix for you which should work.

It will take some time before I add it to the stable version and pypi, so currently you will have to install the module from source to get the update.

I will also note that as I was diagnosing a fix, I noticed that the Reciprocal distribution is already supported nativly as `chaospy.Reciprocal`.

I hereby consider the issue as resolved. If you consider that not to be the case, or if there are other problems related to the same issue, feel free to re-open the issue.
