### ISSUE TITLE
Truncated exponents of scipy.stats and chaospy give different values

### ISSUE THREAD

**Issue by robertsawko** [jonathf/chaospy#34]
I've looked at the documentations of both functions and tested it against the followign minimal example and I cannot find what's going wrong.

```python
from chaospy import Truncexpon
from scipy.stats import truncexpon
from pickle import load

with open('params.pickle', 'rb') as f:
    p = load(f)[0]

x = 0.00085
print(truncexpon.pdf(x, b=p[0], loc=p[1], scale=p[2]))
print(Truncexpon(up=p[0], shift=p[1], scale=p[2]).pdf(x))
```
I believe these should be similar. What I am getting though is:

```
$python2 test.py
4518.666471
2535.1745292
```

[params.zip](https://github.com/jonathf/chaospy/files/579123/params.zip)

**Comment by jonathf** [comment]
The parameters here have the same meaning.

My implementation from core function is like this:
```
dist = chaospy.dist.cores.truncexpon((up-shift)/scale)*scale + shift
```
For the stats model it is like this:
```
dist = truncexpon(b)*scale + loc
```
In other words I rescale such that `up` is always the upper bound.

To get around it, it should be enough to do something like:
```
up=p[0]*p[2]+p[1]
```

**Comment by jonathf** [comment]
I consider the issue as resolved.

If you consider that not to be the case, or if there are other problems related to the same issue, feel free to re-open the issue.

**Comment by robertsawko** [comment]
Thanks a lot Jonathan. I was expecting a slight different formulation with these more unusual distributions, but missed it on a quick perusal of the code. Happy to report that with suggested rescaling it works fine.

**Comment by robertsawko** [comment]
A quick suggestion. Maybe the rescaling of `up` is something worth adding to the User Guide you've got? I was using that heavily in my study so a note on different formulation is there, I wouldn't bother you with my question.
