### ISSUE TITLE
Computing sensitivity of mean and std

### ISSUE THREAD

**Issue by Dee718** [jonathf/chaospy#342]
Hey,

This is really a great library and it is very well documented, so thank you!

I am using PCE to calculate the mean and std of a function within a gradient based optimisation program. I am already able to compute the gradient of the mean and std w.r.t. the design variables, as required for the optimisation algorithm using the code below. 

While this code works, it is quite slow and I run into numpy memory issues when I try to increase the quadrature order past 8. Do you have any tips or workarounds for computing these sensitivities in a more efficient manner?

```
# -------- Initialise prior to optimization -------- #
polynomial_order = 6
quadrature_order = 8
num_modes = 3

# Create distributions
Trunc_distribution = cp.TruncNormal(lower = 0, upper = 1, sigma = sigma)
j_dist = cp.Iid(Trunc_distribution, num_modes)

# Create PCE exapansions
polynomial_expansion = cp.generate_expansion(polynomial_order, j_dist)

# Generate quadratures
abscissas, weights = cp.generate_quadrature(
quadrature_order, j_dist, rule="j", sparse=True)

# -------- Within optimization loop -------- #
# Evaluate function for each quadrature point
evals = [ func(x_i, w) for w in abscissas ] # x_i - design variables in the ith iteration of the optimisation 

# Evaluate gradient of function at each quadrature point w.r.t design variables (x)
grad_evals = dfuncdx(x_i, w) for w in abscissas] # shape = [n x m], n = num quadrature points, m = number of design variables (around 100,000 for my optimization)

# Fit quadrature 
u_hat = cp.fit_quadrature(polynomial_expansion, abscissas, weights, evals) 
du_hat,coefs = cp.fit_quadrature(polynomial_expansion, abscissas, weights, grad_evals, retall=1) # slow/causes memory issues in numpy 

# Calculate mean and std
mean = cp.E(u_hat, j_dist)
std = cp.Std(u_hat, j_dist)

# Calculate dmean/dx
dmean_dx = coefs[0]

# Calculate dstd/dx 
uu = cp.fit_quadrature(polynomial_expansion, abscissas, weights, evals[:,np.newaxis]*grad_evals) # slow
a = cp.E(uu,j_dist)
b = mean*dmean_dx
dsigdx = (a - b)/std
```

**Comment by jonathf** [comment]
Some question so I understand a bit more what is going on:
1. Can I assume that `mun_KLE_modes` is somewhat large?
2. What are the shapes produced each evaluations of `func` and `dfuncdx`?
3. Your code do not transpose abscissas for evaluation. Can I assume this is pseudo-code and needs touch-ups before running?
4. What is `obj`?

**Comment by Dee718** [comment]
Sorry, yes should have mentioned that this is pseudo-code. 

1. num_modes (or num_KLE_modes) = 3
2. func results in an array of [n,] where n is the number of nodes (resulting from generate_quadrature). dfuncdx results in [n,n_x] where n_x is the number of design variables (around 100,000)
3. Yep
4. Sorry, obj should be evals (updated the code)

**Comment by Dee718** [comment]
I should also mention that my formulations for the sensitivities of the mean and std are taken from Eq 50 and 51 in https://link.springer.com/article/10.1007/s40430-018-1464-2

**Comment by jonathf** [comment]
Here is the core code of what is going on beneath the hood:
```python
shape = evals.shape[1:]
evals = evals.reshape(len(solves), -1)
ovals = polynomial_expansion(*nodes)
vals1 = [(val*evals.T*weights).T for val in ovals]
norms = numpy.sum(ovals**2*weights, -1)
coefs = (numpy.sum(vals1, 1).T/norms).T
coefs = coefs.reshape(len(coefs), *shape)
approx_model = cp.sum(polynomial_expansion*coefs.T, -1).T
```

You can time it to see where the bottleneck is in your code.
If you do, let me know, and I'll see if there is anything I can do to optimize the code.

In the mean time, if it is of interest, I can add batching to the fit_quadrature function.
Assuming the end result isn't too big for memory, it should solve your memory issue.
And if you have problem with swapping, this might also increase the speed.

**Comment by Dee718** [comment]
Hey, 

Thanks for the code. I've timed it and it seems that the bottleneck is the last line of code:
 `approx_model = cp.sum(polynomial_expansion*coefs.T, -1).T`

I setup a problem with the following parameters:

- `num_modes = 3`
- `polynomial_order = quadrature_order = 4`
-  35 quadrature nodes
- `evals.shape = [35,28611]` 
-  norms directly from `poly, norms = generate_expansion(..., retall = True)` 

Running the code you provided above with these parameters took 55.36 sec to run in total. From this, 55.01 sec was spent on the last line alone, so I think this is the culprit. 

Do you know if there is anything I can do to to make this portion of the code faster?

Thanks for your help!

**Comment by jonathf** [comment]
Ah, right. Thank you, I think I know where the problem is. I'll see if I have can improve that part code this coming week.

**Comment by Dee718** [comment]
Thanks, I appreciate you looking into this!

**Comment by jonathf** [comment]
Are you using python version >=3.7?
If so, you can try updating:
```sh
pip install numpoly==1.2.2
```
That should hopefully give you a proper speed boost.

**Comment by Dee718** [comment]
Hey,

I was previously using python version 3.6, however I've just created a new conda environment with `python == 3.7`. 

It seems that I can't install `numpoly==1.2.2`, I get the following error:

```
pip install numpoly==1.2.2
ERROR: Could not find a version that satisfies the requirement numpoly==1.2.2 (from versions: 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.1.0, 0.1.1, 0.1.2, 0.1.4, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.1.15, 0.1.16, 0.1.17, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4)
ERROR: No matching distribution found for numpoly==1.2.2
```

Do you know if any of these versions are sufficient?

**Comment by jonathf** [comment]
That is weird. I just checked, and it works on my system with python 3.7.10.
Can you give me more specifics about your setup:
* OS/distro version.
* Full Python version in virtual environment, including patch level: 3.7.X.
* Version of pip.

**Comment by Dee718** [comment]
Fixed the install issue and the code is much faster now! 

FYI - I am running on HPC cluster system with Linux version 3.10.0-1127.19.1.el7.x86_64 

After your message I upgraded my conda and created a new env which seems to have solved the issue. I am now running on `numpoly == 1.2.2`, `chaospy == 4.3.1` with `python == 3.7.10`. 

The code is significantly faster now (39.3 sec vs. 7.7 sec with the update) so thank you for your help! 

I'm now hoping to push the a bit code further - with `quadrature_order = 8`, `abscissas.shape = (3, 165)`, `evals.shape = (165, 91875)` the `approx_model = ...` call is taking 230.6sec. Do you have any suggestions for any code optimization I can do to speed this up? I'm going to be calling this function repeatedly within my optimization program with `evals` array changed each time (the array shape remains constant but values themselves will be different). For example, do you think there are any arrays/coefficients I can store and reuse for example to save time?

Thanks for your help!

**Comment by jonathf** [comment]
So numpoly does a lot of array copying to avoid having to deal with numpy views.
I was able to remove a bit of this copying, hopfully making the code even faster in your case.

Update numpoly to version 1.2.3 and give it a try. :)

**Comment by Dee718** [comment]
With the settings mentioned above (`quadrature_order = 8`, `abscissas.shape = (3, 165)`, `evals.shape = (165, 91875)` ) the `approx_model = ...` call takes only 84 sec now vs 230sec earlier.

I really appreciate your help and providing updates so quickly - thank you!
