### ISSUE TITLE
Creating a general polynomial approximation with an unknown but bounded parameter

### ISSUE THREAD

**Issue by KPJoshi** [jonathf/chaospy#347]
Suppose I have a function `z = f(x,y)` where `x` is random variable(s). If the value of `y` was fixed, then I can use GPC to get a polynomial approximation of `f` and the distribution and statistics of `z`. But what if I don't know the value of `y`, only the range of values it can take? To be clear, `y` is not a random variable, but rather a nondeterministic one, and I want to use GPC to construct a polynomial approximation for `f` that will work for any value of `y` within its range that I choose later.

Here is my plan:
* For purposes of GPC, assume `y` is a uniform random variable over its range
* Do GPC with the joint distribution of `x` and `y`
* After constructing the polynomial approximation for `f`, when getting the statistics for `z`, only vary `x` and set `y` to my desired value(s)

Would this plan work (i.e., statistics for `z` are resonably accurate)? Would assuming `y` to be a uniform distribution be the best choice?

Lastly, would GPC still work properly if `x` was not sampled from its distribution, but rather from, say, a uniform distribution over the same support?

Thank you!

**Comment by jonathf** [comment]
Yes, your plan would work just fine.

Your approach also allows for the flexibility of doing partial evaluation: The resulting polynomial from PCE can be evaluated as `poly(q0=None, q1=some_float)` (here `x,y` cooresponds to `q0,q1`) will give you the right polynomial given `y=some_value`.

You could alternatively not make `y` a random variable by making a mesh for `y`. E.g.
```python
evaluations = [[f(x,y) for y in np.linspace(...)] for x in dist.sample(...).T]
```
Then `poly[0]` and `poly[-1]` will correspond to `y` set to its lower and upper bound respectively.

As for the sampling `x` from another distribution:
GPC is not one method, but a class of methods. For methods like intrusive Galerkin and pseudo-spectral projection, that would not work. But for point collocation, that approach is completely reasonable.
