### ISSUE TITLE
Error while following Chaospy quick tutorial

### ISSUE THREAD

**Issue by hfsf** [jonathf/chaospy#348]
Hello,

First of all, many thanks for your attention. Chaospy is an amazing lib.

I am having trouble following the quick tutorial (https://chaospy.readthedocs.io/en/master/user_guide/quick_tutorial.html). 

In the step that the expected value is calculated:

```
expected = chaospy.E(approx_solver, joint)
```

I am obtaining the following error message:

```
~/anaconda3/envs/Numerical/lib/python3.9/site-packages/chaospy/descriptives/expected.py in E(poly, dist, **kws)
     46     out = numpy.zeros(poly.shape)
     47     for idx, key in enumerate(poly.keys):
---> 48         out += poly[key]*moments[idx]
     49     return out

~/anaconda3/envs/Numerical/lib/python3.9/site-packages/numpoly/baseclass.py in __getitem__(self, index)
    625         return numpoly.polynomial_from_attributes(
    626             exponents=self.exponents,
--> 627             coefficients=[coeff[index] for coeff in self.coefficients],
    628             names=self.names,
    629         )

~/anaconda3/envs/Numerical/lib/python3.9/site-packages/numpoly/baseclass.py in <listcomp>(.0)
    625         return numpoly.polynomial_from_attributes(
    626             exponents=self.exponents,
--> 627             coefficients=[coeff[index] for coeff in self.coefficients],
    628             names=self.names,
    629         )

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```
I don't know what else to do, I have revised the code, and followed it step by step. I am currently using chaospy v. 3.3.8, and python version is 3.9.5. It may be some sort of version clash? Many thanks.

**Comment by hfsf** [comment]
I have tested the version provided by pip, and python 3.7, and there is no error. Perhaps is some sort of version issue?
Additionally, conda-forge version is stucked at 3.3.8, while pip version is at 4.3.2.

**Comment by jonathf** [comment]
Yes, that is a version issue. Conda is out-of-date and its dependency `numpoly` is not.

I am not the maintainer of the Conda build, but I've made a PR to the feedstock now with an update:
https://github.com/conda-forge/chaospy-feedstock/pull/45

In the mean time, if you like to use the conda version, pin the dependency `numpoly==1.0.5` and everything should work as expected.
