### ISSUE TITLE
Getting NaN values from a gamma distribution

### ISSUE THREAD

**Issue by jaimeambrus** [jonathf/chaospy#358]
Hi,

I'm currently trying to use a gamma distribution (for a later use on `uncertainpy`) but got some NaN values. The snippet below show what I did. I'm not sure if I'm setting the proper values although `a > 0` and `scale != 0`.

I also got some warnings:

```
/usr/local/lib/python3.7/dist-packages/chaospy/distributions/collection/gamma.py:14: RuntimeWarning: overflow encountered in power
  return x**(a-1)*numpy.e**(-x)/special.gamma(a)
/usr/local/lib/python3.7/dist-packages/chaospy/distributions/collection/gamma.py:14: RuntimeWarning: invalid value encountered in true_divide
  return x**(a-1)*numpy.e**(-x)/special.gamma(a)
```
Any hints will help!

Thanks
```
import chaospy as cp
import numpy as np

expected_value = 4.0
uloc = np.linspace(2.0, 6.0, 1000)
f = 5.0

std_dev = (f/100.0) * expected_value
variance = std_dev * std_dev

theta = variance / expected_value
a = expected_value * expected_value / variance
distribution = cp.Gamma(a, scale = theta)

from scipy.stats import gamma
distribution_np = gamma(k, scale = theta)
print('k: ', k)
print('theta: ', theta)

print(distribution.pdf(uloc))
fig2 = plt.figure()
plt.plot(uloc, distribution.pdf(uloc), '-')
plt.plot(uloc, distribution_np.pdf(uloc), '-')
```

**Comment by jonathf** [comment]
Okay, that is a good catch.

Gamma breaks down for larger values of alpha. Looking at the scipy implementation it looks like they fixed it simply by updating to a more robust formula. Good to know.

Version 4.3.4 is relased with a fix. Check it out.

**Comment by jaimeambrus** [comment]
Hi @jonathf , thanks for updating this!
Is 4.3.4 already out? (I can use the master branch if not, no problem. Just asking :) )

**Comment by jaimeambrus** [comment]
Just got it. Works like a charm. Thanks!
