### ISSUE TITLE
Point collocation method with or without Rosenblatt transformation 

### ISSUE THREAD

**Issue by hamzabuw** [jonathf/chaospy#369]
Hi,

I am currently working on applying Non-Intrusive PCE to fire safety problems and still new with PCE and Chaospy.
I have a question regarding the steps for Point collocation method:

In [Generalized polynomial chaos script](https://hub.gke2.mybinder.org/user/jonathf-chaospy-3v2so42f/notebooks/docs/user_guide/advanced_topics/generalized_polynomial_chaos.ipynb) Rosenblatt transformation is applied to make dependent samples independent. However in the [Point collocation script](https://hub.gke2.mybinder.org/user/jonathf-chaospy-t8jrepac/notebooks/docs/user_guide/main_usage/point_collocation.ipynb), it appears to be neglected. Can you kindly tell why is that? Or is it implicitly included somehow?

Secondly the following error arises for expected value at running the given code [Point collocation](https://hub.gke2.mybinder.org/user/jonathf-chaospy-t8jrepac/notebooks/docs/user_guide/main_usage/point_collocation.ipynb):
![image](https://user-images.githubusercontent.com/97860562/149689005-e34428a6-0759-43d3-8555-c10d0eebab81.png)

Can you help me with fixing this error or guide me to another forum? Didn't find it in the issues so probably has to do with my installation.
Thank you in anticipation.

**Comment by jonathf** [comment]
That looks like an issue with the current version of numpoly.

Can you try to update with `pip install -U numpoly` and try again?

If that doesn't work, can you report OS, the version of Python, Numpy, Chaospy and Numpoly?

**Comment by jonathf** [comment]
I think I've seen this before.

Do you mind updating both numpy and chaospy to the latest version and trying again?

**Comment by hamzabuw** [comment]
Hi,

I updated both numpy and chaospy but couldn't fix the bug.
I tried a [simpler](https://chaospy.readthedocs.io/en/master/user_guide/fundamentals/descriptive_statistics.html) code below and got a new error message. Maybe this helps in finding the actual bug.

`import chaospy`
`uniform = chaospy.Uniform(0, 4)`
`samples = uniform.sample(1e7)`
`chaospy.E(uniform)`

![image](https://user-images.githubusercontent.com/97860562/151884776-5dc8d7fb-79a8-431f-9008-b2805ae65c18.png)

**Comment by jonathf** [comment]
That is still not reproducible.

I am wondering if you don't have multiple versions overlapping on your system.
Do you mind uninstalling numpy, numpoly and chaospy and installing them again from scratch using pip.
Then run the code:
```python
import numpy
import numpoly
import chaospy
print(numpy.__version__, numpoly.__version, chaospy.__version__)
```

**Comment by hamzabuw** [comment]
This worked. I believe you were right about multiple versions. Thank you for the support and sorry for the trouble.

So these are the versions which finally worked:
`print(numpy.__version__, numpoly.__version__, chaospy.__version__)`
1.21.5 1.2.3 4.3.4
