### ISSUE TITLE
Installation issue - 'Dist' from 'chaospy.distributions.baseclass' 

### ISSUE THREAD

**Issue by GuillaumeGirier** [jonathf/chaospy#372]
Dear developers,

First of all, thank you for this package which seems very interesting.

I am contacting you because I have an issue during the installation of the package.
I used this command line to install the package :

`pip install chaospy`

Normally every dependencies are well installed but this is the raised error when I try to import the package :

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-13-b22e5313a076> in <module>
----> 1 import chaospy as cp
      2 #import uncertainpy as un

~/anaconda3/lib/python3.8/site-packages/chaospy/__init__.py in <module>
     12 
     13 import chaospy.chol
---> 14 import chaospy.descriptives
     15 import chaospy.distributions
     16 import chaospy.orthogonal

~/anaconda3/lib/python3.8/site-packages/chaospy/descriptives/__init__.py in <module>
     36 """
     37 from .expected import E
---> 38 from .conditional import E_cond
     39 from .covariance import Cov
     40 from .kurtosis import Kurt

~/anaconda3/lib/python3.8/site-packages/chaospy/descriptives/conditional.py in <module>
      6 
      7 from .expected import E
----> 8 from .. import distributions
      9 
     10 

~/anaconda3/lib/python3.8/site-packages/chaospy/distributions/__init__.py in <module>
     67 """
     68 from . import baseclass
---> 69 from .baseclass import Dist, StochasticallyDependentError
     70 
     71 from .sampler import *

ImportError: cannot import name 'Dist' from 'chaospy.distributions.baseclass' (/home/ggirier/anaconda3/lib/python3.8/site-packages/chaospy/distributions/baseclass/__init__.py)
```

I have check on internet, and I didn't find any solution which works.

Have you already had this issue? If yes, how can I solve it?

Thank you very much,

Respectfully,

GIRIER Guillaume.

**Comment by jonathf** [comment]
Glad you find it interesting.

That looks like old code. Please do an update with `pip install -U chaospy`.
If that doesn't work, run `pip freeze` and post the results back here.

**Comment by GuillaumeGirier** [comment]
Thank you very much for your quick answer.

It seems to be the solution indeed. Now, I can import the package.

Thank you very much,

GIRIER Guillaume.
