### ISSUE TITLE
chaospy.Normal(0.253,0.02024

### ISSUE THREAD

**Issue by AmosJoseph** [jonathf/chaospy#380]
Samples of chaospy.Normal(0.253,0.02024) are all positive, however in theory Normal distribution can get negative samples. But why?

Peace!

**Comment by jonathf** [comment]
Chaospy doesn't really support unbound distributions. In most cases that doesn't matter as one can easily approximate unbound distribution by taking a large enough finite interval.

For Normal I think I take 8 standard deviations on each side to ensure the error is smaller than machine precision. The eaxample you are providing ha origin at around 12 deviations away.

In general if you need to do analysis on extreme values of tails where cumulative probabilities are bello 1e-16, then chaospy is likely to be the wrong tool for the job.
