### ISSUE TITLE
How to generate samples with covariance matrix for distributions of interest?

### ISSUE THREAD

**Issue by dirge1** [jonathf/chaospy#381]
For example, a uniform distribution and a normal distribution with correlation coefficient 0.4

**Comment by jonathf** [comment]
If you want to keep the marginsl distributions, but induce correlation, I'd look into Copula theory.

If you want a simple suggestion, I'd go for something like cp.Nataf and provide it with the matrix [[1, r], [r, 1]] as parameter. To get correlation at 0.4, you'll likely need to tweak r a bit.

**Comment by dirge1** [comment]
Hi, Jonathan. Thank you for your reply! I will try it.
