### ISSUE TITLE
How to generate samples from bimodal normal distribution in chaospy?

### ISSUE THREAD

**Issue by dirge1** [jonathf/chaospy#382]
For example, I have a Gaussian mixture model with mean=[2150 2200], standard deviation=[100 100], and weight=[0.4 0.6]. How can I describe this distribution and generate samples using chaospy? Thanks a lot!

**Comment by jonathf** [comment]
Something like this:
```python
>>> dist = chaospy.GaussianMixture([2150, 2200], covariances=[10, 10], weights=[0.4, 0.6])
... print(dist.sample(10))
[2147.7770397  2150.47062522 2149.4234327  2202.93726047 2199.42326192
 2145.29237617 2151.6406198  2153.3474095  2195.61122906 2196.84543046]
```

**Comment by dirge1** [comment]
It works quite well. Thank you very much!
