### ISSUE TITLE
Hi,jonathf. It seems that this function "cp.orth_ttr" is not available in the latest chaospy version. Isn't it? Glad for your reply!

### ISSUE THREAD

**Issue by KIDDProgress** [jonathf/chaospy#383]
Hi,
I have another question about the PCE method.
`polynomials=cp.orth_ttr(1,distribution)` generates the total-order expansion. How does Chaospy generate the tensor-product expansion with the dimension preference?

_Originally posted by @Einshane in https://github.com/jonathf/chaospy/issues/95#issuecomment-447328964_

**Comment by jonathf** [comment]
`orth_ttr` is fone from the main interface, but it is still accessible through the main wrapper in `generate_expansion`:
https://chaospy.readthedocs.io/en/master/user_guide/polynomial/orthogonality.html#Wiener-Askey-scheme
The default `rule="stieltjes"` corresponds to the TTR algorithm.

Dimension preference is done by passing a vector to `order`, like:
```python
>>> import chaospy as cp
>>> dist = cp.Iid(cp.Normal(0, 1), 2)
>>> print(cp.generate_expansion([2, 3], dist))
[1.0 q1 q0 q1**2-1.0 q0*q1 q0**2-1.0 q1**3-3.0*q1]
```
