### ISSUE TITLE
memory leak in GaussianKDE

### ISSUE THREAD

**Issue by uqyge** [jonathf/chaospy#389]
**Describe the bug**
GaussianKDE will leak memory when you calculate pdf or cdf.

**To Reproduce**
Provide a minimal code example that reproduces the error
```python
def f(x):
    mu = x[0]
    sigma = x[1]

    dist = chaospy.Normal(mu, sigma)
    samples = dist.sample(1000)
    kde = chaospy.GaussianKDE(samples)
    return kde


x0=[11,0.3]
t = np.linspace(9, 13, 20000)

for _ in range(500):
    f(x0).pdf(t)
```
**Expected behavior**
memory keeps leaking.

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Python version: 3.8.10
 - Chaospy version 4.3.7
 
**Additional context**
I am doing a maximum entropy optimization, which requires repeatedly calculating pdf and cdf of the model.  The code above will create a constant memory leak.

**Comment by jonathf** [comment]
I look through the KDE-code and I don't think that is a chaospy-bug, but more of a Python gc problem that keeps the full distribution in memory even though there is no obvious reference to it. Python gc is hard to interact with, so perhaps a better approach is re-use the referenced distribution.

Not super idiomatic, but the following works okay without leaking on my machine atleast:

```python
import numpy
import chaospy

kde = chaospy.GaussianKDE([1, 2, 3])  # a dummy to be refilled

def f(x):
    mu = x[0]
    sigma = x[1]

    dist = chaospy.Normal(mu, sigma)
    samples = dist.sample(1000)
    kde.__init__(samples)


x0 = [11, 0.3]
t = numpy.linspace(9, 13, 20000)

for _ in range(500):
    f(x0)
    kde.pdf(t)
```

**Comment by jonathf** [comment]
Looks like you were right. I found a cache that stored all old distributions.

I've added a patch to v4.3.8.
