### ISSUE TITLE
Latin hypercube sampling, rule="L"

### ISSUE THREAD

**Issue by AmosJoseph** [jonathf/chaospy#395]
I'm writing to ask the usage below:
samples =distribution.sample(size = 250, rule="L")
print( samples )

pardon! Is the data got by print( samples) ordered or shuffled without order?

Thanks a lot!

**Comment by jonathf** [comment]
Sorry for the late reply. This has gotten forgotten a bit.

I think there are a few different definitions of what LHC sampling does, depending on usecase.
Your best bet to get a good answer is to just look at the code here:
https://github.com/jonathf/chaospy/blob/master/chaospy/distributions/sampler/latin_hypercube.py

Hope that helps.

**Comment by AmosJoseph** [comment]
OK. Thanks a lot!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jonathf/chaospy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月10日(星期四) 晚上9:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jonathf/chaospy] Latin hypercube sampling, rule="L" (Issue #395)





 
Sorry for the late reply. This has gotten forgotten a bit.
 
I think there are a few different definitions of what LHC sampling does, depending on usecase.
 Your best bet to get a good answer is to just look at the code here:
 https://github.com/jonathf/chaospy/blob/master/chaospy/distributions/sampler/latin_hypercube.py
 
Hope that helps.
