### ISSUE TITLE
TruncNormal changed meaning for lower and upper for version >4.3.6

### ISSUE THREAD

**Issue by silvanfischbacher** [jonathf/chaospy#396]
Hi,
In version 4.3.6 the backend of TruncNormal switched to scipy. In earlier versions
`chaospy.TruncNormal(lower=1, upper=5, mu=2, sigma=1)`
returned a normal distribution centered at 2 with std 1 truncated at 1 and 5. In the new version, the same command returns a normal distribution that is truncated 3 and 5. Is this intentional? I assume it is related to the way `scipy` does the truncation (see https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.truncnorm.html).
Thank you!

**Comment by jonathf** [comment]
That is a regression, yes.

Fixed made in version 4.3.9. Let me know if it works or not.

**Comment by silvanfischbacher** [comment]
Thanks for the quick reply. It works not perfectly, yet. Again with the example from above, the lower truncation works, the upper is now at 3 instead of 5. I guess there is some backtransformation missing since the upper truncation is always at the value of `b` that is used for scipy.

**Comment by jonathf** [comment]
You're right. something went wrong in the implementation there.

I've made a fix now that I think is a bit more robust, but I had to give up analytical statistical moments. I might have to revisit it at some point.

Anyway, try again with version 4.3.9-post1.

**Comment by silvanfischbacher** [comment]
Now it works! Thanks!
