### ISSUE TITLE
How to deal with high-dimensional system?

### ISSUE THREAD

**Issue by Jiaxing-Wang** [jonathf/chaospy#40]
1.
I  tried to construct the PCE using spectral projection method like this:

distribution = cp.Iid(cp.Normal(0, 1), 39)    
nodes, weights = cp.generate_quadrature(order = 1, domain = distribution)

My computer crashed directly, as there are too many parameters.  My question is I want to construct a PCE, which has 39 uncertainty parameters. Can  I use the spectral projection method? Are there any other way to using  spectral projection method to reduce the samples?

2.
I have construct PCE using the linear regression method with 4000 samples like this (P and Y are my samples and predictions):
    
distribution = cp.Iid(cp.Uniform(0, 1), 39)
polynomial_expansion = cp.orth_ttr(2, distribution)    
foo_approx = cp.fit_regression(polynomial_expansion, P, Y)

and the relative accuracy is 1% which is acceptable for me. 

I want to compare  spectral projection and linear regression. Are they comparable at dealing with the high dimensional question, which has 39 model inputs? 

Thank you very much.

**Comment by Jiaxing-Wang** [comment]
@tsilifis, Thank you for your answer. I understand how to compare different methods.

I have an another question about the sparse gird. I am trying to generate the sparse grid using the code like this:
    dimension = 39
    distribution = cp.Iid(cp.Uniform(0, 1), dimension )
    polynomial_expansion = cp.orth_ttr(1, distribution)    
    nodes, weights = cp.generate_quadrature(order = 1, domain = distribution, sparse=True,rule = "c")

The memory of my computer is 64g now. However, the generating process using the code above is quite slow. I can not get the results. 

Is there any thing wrong?

**Comment by Jiaxing-Wang** [comment]
@tsilifis , I can not use a PCE with the order larger than 2. This is also because the dimension of my problem is  as large as 39. The unknown parameter for a third order PCE is too large.

**Comment by jonathf** [comment]
The library for pseudo-spectral projections was never designed to scale smoothly upwards, so the limitations you are experiencing is not much of a surprises. Non-sparse order 3 -> 4^39=302231454903657293676544 samples. Sparse helps a few orders of magnitude, but that is still quite a bit of samples to handle even if the generator wasn't struggling.

The method `cp.fit_quadrature` takes the arguments `nodes, weights, evals`, which only need to be numpy complient. I.e. If you have a quadrature rule that works well on joint 39-dimensional i.i.d. Gaussian random variable, you are good to go. (If you are aware of any well functioning high-dimensional quadrature schemes out there, let me know.)

A naive approach that will work, is to use Monte Carlo integration: Generate random samples from your distributions, use `weights = 1./len(samples)`. Not nearly as accurate, but technically still pseudo-spectral projection.

Side note:
The `rule="C"` is Clenshaw-Curtis quadrature, which works poorly on infinite-interval distributions like the Gaussian you are using. I might recommend using something like Gauss-Patterson `rule="P"` instead.

**Comment by Jiaxing-Wang** [comment]
@jonathf, Thanks a lot. 

I try the method as you said. P is the samples using sobol's sequence and Y is the model output:

    distribution = cp.Iid(cp.Uniform(0, 1), P.shape[0])
    polynomial_expansion = cp.orth_ttr(2, distribution)
    foo_approx = cp.fit_quadrature(polynomial_expansion,P,1./len(Y)*np.ones(len(Y)),Y)

The convergence of this method is much slower compared to the point collocation method. 
![image](https://cloud.githubusercontent.com/assets/22335211/23639693/0c8f35b0-0324-11e7-9c84-5a9e8cd7d3ed.png)

Can I draw a conclusion that the point collocation is better than pseudo-spectral projection method, when the dimension of the input is very large?

**Comment by jonathf** [comment]
Yes, you can safely conclude that PC is better than PSP in higher dimensions.

**Comment by Jiaxing-Wang** [comment]
@jonathf  Thank you very much. 

I get my answer.
