### ISSUE TITLE
Problem Defining dependant random variables with absolute and minimum operators

### ISSUE THREAD

**Issue by kilojoules** [jonathf/chaospy#403]
I would like to define random variables that are dependent on other variables based on absolute or minimum operators. When I implement these definitions, I get an unexpected recursion error.

Here are two examples to illustrate the issue

minimum operator:
```
import chaospy as cp

dist1 = cp.Uniform(2, 5)
dist2 = cp.Uniform(0, cp.minimum(dist1, 3))

joint = cp.J(dist1, dist2)

samps = joint.samples(10)
```

absolute operator:

```
import chaospy as cp

dist1 = cp.Uniform(-2, 5)
dist2 = cp.Uniform(-10, cp.abs(dist1))

joint = cp.J(dist1, dist2)

samps = joint.samples(10)
```

In both cases, I get a `RecursionError`.

Error when running the code with the minimum operator:

```
....
  File "/Users/julianquick/miniconda3/envs/sgd/lib/python3.10/site-packages/numpoly/construct/compose.py", line 42, in <listcomp>
    numpoly.expand_dims(numpoly.aspolynomial(array, dtype=dtype), axis=0)
  File "/Users/julianquick/miniconda3/envs/sgd/lib/python3.10/site-packages/numpoly/construct/aspolynomial.py", line 59, in aspolynomial
    return numpoly.polynomial(poly_like, names=names, dtype=dtype)
  File "/Users/julianquick/miniconda3/envs/sgd/lib/python3.10/site-packages/numpoly/construct/polynomial.py", line 137, in polynomial
    poly = compose_polynomial_array(
  File "/Users/julianquick/miniconda3/envs/sgd/lib/python3.10/site-packages/numpoly/construct/compose.py", line 35, in compose_polynomial_array
    oarrays = numpy.array(arrays, dtype=object)
  File "/Users/julianquick/miniconda3/envs/sgd/lib/python3.10/site-packages/chaospy/distributions/baseclass/distribution.py", line 809, in __iter__
    for idx in range(len(self)):
  File "/Users/julianquick/miniconda3/envs/sgd/lib/python3.10/site-packages/chaospy/distributions/baseclass/distribution.py", line 814, in __len__
    return len(self._dependencies)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Error when running the code with the absolute operator:

```
....
  File "/Users/julianquick/miniconda3/envs/sgd/lib/python3.10/site-packages/numpoly/construct/compose.py", line 42, in <listcomp>
    numpoly.expand_dims(numpoly.aspolynomial(array, dtype=dtype), axis=0)
  File "/Users/julianquick/miniconda3/envs/sgd/lib/python3.10/site-packages/numpoly/construct/aspolynomial.py", line 59, in aspolynomial
    return numpoly.polynomial(poly_like, names=names, dtype=dtype)
  File "/Users/julianquick/miniconda3/envs/sgd/lib/python3.10/site-packages/numpoly/construct/polynomial.py", line 137, in polynomial
    poly = compose_polynomial_array(
  File "/Users/julianquick/miniconda3/envs/sgd/lib/python3.10/site-packages/numpoly/construct/compose.py", line 35, in compose_polynomial_array
    oarrays = numpy.array(arrays, dtype=object)
  File "/Users/julianquick/miniconda3/envs/sgd/lib/python3.10/site-packages/chaospy/distributions/baseclass/distribution.py", line 809, in __iter__
    for idx in range(len(self)):
RecursionError: maximum recursion depth exceeded
```

**Comment by jonathf** [comment]
The operation `cp.abs` is meant for polynomials, not distributions. Chaospy does not support `abs` unfortunatly. That is the reason for the error.

**Comment by jonathf** [comment]
Same with `cp.minimum`

**Comment by regislebrun** [comment]
Hi,

You can use an OpenTURNS distribution to build dist2 with the properties you want:
```
import openturns as ot
import chaospy as cp

dist1_ot = ot.Uniform(2, 5)
link = ot.SymbolicFunction(["t"], ["0.0", "min(t, 3)"])
dist_param = ot.Uniform()
dist2_ot = ot.ConditionalDistribution(dist_param, dist1_ot, link)
```
The link function maps your conditioning distribution into the set of parameters of the output distribution. The conditional distribution has the following PDF:
![dist2_min](https://user-images.githubusercontent.com/8220933/224558450-6972162f-64cd-415c-b068-70fab60a8492.png)

Using the updated OpenTURNS wrapper proposed in PR#405, you can convert this distribution as well as the conditioning distribution into a chaospy distributions:
```
dist1 = cp.OpenTURNSDist(dist1_ot)
dist2 = cp.OpenTURNSDist(dist2_ot)
```
Then you can join them:
```
joint = cp.J(dist1, dist2)
```
but be careful, what you are doing here is to build a bivariate distribution with independent components and univariate marginals distributed according to dist1 and dist2. The link between dist1 and dist2 as being conditioned by dist1 is lost.

In OpenTURNS you can build the distribution you probably want this way:
```
dist3_ot = ot.BayesDistribution(dist_param, dist1_ot, link)
```

Here is a graph of the iso-PDF of `dist3_ot`, and a cloud based on a sample of size 1000 of this distribution.
![dist3_min](https://user-images.githubusercontent.com/8220933/224558473-71532c2b-ff58-42ba-9e85-872de9aaff74.png)

Note that for a strange reason, the conditioned distribution is the first component and the conditioning distribution is the second component. Let's call it a *curiosity* ;-)

If we add a sample of the same size given by `joint`,  in black in the following graph (it has been transposed to match the strange OpenTURNS convention) we see that the components of `joint` are independent, even if they have the correct marginal distributions.
![dist3_min_cp](https://user-images.githubusercontent.com/8220933/224558805-4546d400-71ea-46c0-8ae7-4337f5b145f2.png)

For the abs case we get for dist2:
![dist2_abs](https://user-images.githubusercontent.com/8220933/224558952-27c48708-30b8-4a30-8c7d-2de4d17b04cb.png)

and for dist3_ot:
![dist3_abs](https://user-images.githubusercontent.com/8220933/224558968-ecb8d054-cd34-4dd6-8779-2e68a683a2c7.png)

and with `joint` sample:
![dist3_abs_cp](https://user-images.githubusercontent.com/8220933/224558986-d2d614cd-d7b0-4e71-b4bb-6a6091733e49.png)

Here is the quick and dirty code allowing to reproduce the graphs:
```
import openturns as ot
import openturns.viewer as otv
import chaospy as cp

# Minimum case
dist1_ot = ot.Uniform(2, 5)
link = ot.SymbolicFunction(["t"], ["0.0", "min(t, 3)"])
dist_param = ot.Uniform()
dist2_ot = ot.ConditionalDistribution(dist_param, dist1_ot, link)
g = dist2_ot.drawPDF()
g.setXTitle(r"$x_1$")
g.setYTitle("pdf")
g.setTitle("Conditioned distribution PDF (min case)")
g.setLegendPosition("")
view = otv.View(g)
view.save("dist2_min.png")
view.close()
dist3_ot = ot.BayesDistribution(dist_param, dist1_ot, link)
g = dist3_ot.drawPDF()
g.add(ot.Cloud(dist3_ot.getSample(1000)))
g.setXTitle(r"$x_1$")
g.setYTitle(r"$x_2$")
g.setTitle("Bayes distribution iso-PDF (min case)")
g.setLegendPosition("")
view = otv.View(g)
view.save("dist3_min.png")
view.close()

print("convert dist1_ot")
dist1 = cp.OpenTURNSDist(dist1_ot)
print("convert dist2_ot")
dist2 = cp.OpenTURNSDist(dist2_ot)
print("joint")
joint = cp.J(dist1, dist2)

samps = joint.sample(1000)
print(samps.shape)
c = ot.Cloud(ot.Sample(samps.T).getMarginal([1,0]))
c.setColor("black")
g.add(c)
view = otv.View(g)
view.save("dist3_min_cp.png")
view.close()

# Abs case
dist1_ot = ot.Uniform(-2, 5)
link = ot.SymbolicFunction(["t"], ["-10.0", "abs(t)"])
dist_param = ot.Uniform()
dist2_ot = ot.ConditionalDistribution(dist_param, dist1_ot, link)
g = dist2_ot.drawPDF()
g.setXTitle(r"$x_1$")
g.setYTitle("pdf")
g.setTitle("Conditioned distribution PDF (abs case)")
g.setLegendPosition("")
view = otv.View(g)
view.save("dist2_abs.png")
view.close()
dist3_ot = ot.BayesDistribution(dist_param, dist1_ot, link)
g = dist3_ot.drawPDF()
g.add(ot.Cloud(dist3_ot.getSample(1000)))
g.setXTitle(r"$x_1$")
g.setYTitle(r"$x_2$")
g.setTitle("Bayes distribution iso-PDF (abs case)")
g.setLegendPosition("")
view = otv.View(g)
view.save("dist3_abs.png")
view.close()

print("convert dist1_ot")
dist1 = cp.OpenTURNSDist(dist1_ot)
print("convert dist2_ot")
dist2 = cp.OpenTURNSDist(dist2_ot)
print("joint")
joint = cp.J(dist1, dist2)

samps = joint.sample(1000)
print(samps.shape)
c = ot.Cloud(ot.Sample(samps.T).getMarginal([1,0]))
c.setColor("black")
g.add(c)
view = otv.View(g)
view.save("dist3_abs_cp.png")
view.close()
```

Cheers

Régis

**Comment by regislebrun** [comment]
Hi,
My previous post was buggy, sorry for that. I was considering the conditioning uniform distribution instead of its transformation.

Here is a way to do what @kilojoules using either 100% OpenTURNS or a mix of OpenTURNS and chaospy (and IMO the resulting script is more concise and more readable using the latest option):
```
import openturns as ot
import openturns.viewer as otv
import chaospy as cp

# Minimum case
# Full OT
link_min = ot.SymbolicFunction("t", "min(t, 3)")
dist1_ot = ot.CompositeDistribution(link_min, ot.Uniform(2, 5))
link = ot.SymbolicFunction(["t"], ["0.0", "t"])
dist_param = ot.Uniform()
dist3_ot = ot.BayesDistribution(dist_param, dist1_ot, link)
g = dist3_ot.drawPDF()
g.add(ot.Cloud(dist3_ot.getSample(1000)))
g.setXTitle(r"$x_1$")
g.setYTitle(r"$x_2$")
g.setTitle("Bayes distribution iso-PDF (min case)")
g.setLegendPosition("")
view = otv.View(g)
view.save("dist3_min.png")
view.close()

# OT + chaospy
dist1 = cp.OpenTURNSDist(dist1_ot)
dist2 = cp.Uniform(0, dist1)

joint = cp.J(dist1, dist2)

samps = joint.sample(1000)
c = ot.Cloud(ot.Sample(samps.T).getMarginal([1,0]))
c.setColor("black")
g.add(c)
view = otv.View(g)
view.save("dist3_min_cp.png")
view.close()

# Abs case
# Full OT
dist1_ot = ot.Uniform(-2, 5).abs()
link = ot.SymbolicFunction(["t"], ["-10.0", "t"])
dist_param = ot.Uniform()
dist3_ot = ot.BayesDistribution(dist_param, dist1_ot, link)
g = dist3_ot.drawPDF()
g.add(ot.Cloud(dist3_ot.getSample(1000)))
g.setXTitle(r"$x_1$")
g.setYTitle(r"$x_2$")
g.setTitle("Bayes distribution iso-PDF (abs case)")
g.setLegendPosition("")
view = otv.View(g)
view.save("dist3_abs.png")
view.close()

# OT + chaospy
ot.Show(dist1_ot.drawPDF())
dist1 = cp.OpenTURNSDist(dist1_ot)
dist2 = cp.Uniform(-10, dist1)

joint = cp.J(dist1, dist2)

samps = joint.sample(1000)
c = ot.Cloud(ot.Sample(samps.T).getMarginal([1,0]))
c.setColor("black")
g.add(c)
view = otv.View(g)
view.save("dist3_abs_cp.png")
view.close()
```
which produces for the minimum case:
With the 100% OpenTURNS version:
![dist3_min](https://user-images.githubusercontent.com/8220933/224568977-f7b386ed-fa19-442e-a431-0fe77720bc92.png)

and with the mix OpenTURNS/chaospy:
![dist3_min_cp](https://user-images.githubusercontent.com/8220933/224568990-cfdc1a64-4664-4546-88ff-e1fa4a458ac8.png)

and for the abs case:
With the 100% OpenTURNS version:
![dist3_abs](https://user-images.githubusercontent.com/8220933/224569030-1fe5a706-f8e9-48bb-af0b-97295619aaf8.png)

and with the mix OpenTURNS/chaospy:
![dist3_abs_cp](https://user-images.githubusercontent.com/8220933/224569050-17124fab-a883-4856-b424-a3459af16a2b.png)

It looks like the problem can be expressed using the right tools ;-)!

Cheers

Régis

**Comment by jonathf** [comment]
Cool to see that this is possible, @regislebrun. And thanks for taking the time to make a working example.
