### ISSUE TITLE
cp.fit_regression()has no atrribute 'A'

### ISSUE THREAD

**Issue by nealcha** [jonathf/chaospy#404]
Hi
Recently I have tried `cp.fit_regression().A` ,however, it reported a mistake:
'AttributeError: 'ndpoly' object has no attribute 'A'',I WONDER whether there is other attribute replaced 'A'.
THANKS!

**Comment by jonathf** [comment]
Yes, that attribute was depricated a while back when the backend was switched out. There is a `.todict()` method now that lets you recreate the dictionary if you need it.

If you need to go back to the polynomial representation afterwards you can also do so with: `cp.polynomial(dict_representation)`.
