### ISSUE TITLE
Depreciation pkg_resources

### ISSUE THREAD

**Issue by beroda** [jonathf/chaospy#408]
Hello. First of all, thank you for contributing this package to the scientific community, this is highly appreciable :smile:.

**Is your functionality related to a problem? Please describe.**
We use  `chaospy` at work inside our python project and inside our test suite, we chose to convert `DepreciationWarning`s into errors to keep our codebase up-to-date with latest packages implementations.

However, it seems that you use the `pkg_resources` module from `setuptools`, which is deprecated in favor to the `importlib` one (see https://setuptools.pypa.io/en/latest/pkg_resources.html) in recent python versions.

Would it be possible for your to consider switching from `pkg_resources` to `importlib` ?
If it if fine for you, I can propose you a pull request promptly.

**Additional context**
We use `python3.8` and above, as `python3.7` is reaching end-of-life in [June](https://endoflife.date/python)

**Comment by jonathf** [comment]
Thank you. It is a joy to have a PhD that created value for others.

Yeah, pkg_resource is a relic from the time chaospy supported Python 2. Not really needed anymore.

A PR is much appriciated, thank you. :)
