### ISSUE TITLE
Handle categorical variables

### ISSUE THREAD

**Issue by xavArtley** [jonathf/chaospy#41]
Hello,

I would like to know if it was possible to use chaospy with discrete variables in the model.

Greetings

**Comment by jonathf** [comment]
Short answer is partially yes.

First of all, if your goal is to address categorical variables, then I am not aware of theory that allows for the use of polynomial chaos expansions.

If you have discrete variables with high (or countable infinite) number of random states, then the theory allows for that, but I haven't implemented a framework for it. That being said, I can think of more than one way to make a 5 liner hack that allows for it anyways, but that depends a little on the problem.

Do you have a minimal example I can take a look at (that isn't categorical)?

**Comment by xavArtley** [comment]
No I'm sorry I don't have such example.
My problem is sensitivity analysis for a NDT (non destructive test) where the defect type in the material is categorical. 
And the probability of the defect type depends on the charasteristic of the material
So the categorical variable is dependent to other variables too.
I was just looking for Sensitivity analysis method rather global with dependencies and type of variables.

**Comment by jonathf** [comment]
Sorry the late reply, I had to ask a friend about the sensitivity analysis part, since he is more familiar. Here is his response. I hope it is useful.

> If the model is linear, and non additive:
> 
> linear regression with standardized sensitivity coefficients (standardized regression coefficients) might be a way to go.
> 
> I think GPC or MC with variance based sobol indices should work.
> You need to reformulate your problem such you can apply it.
> If you have a categorical variable with a probability function you might be able to define
> it differently such as a range from 0 to 1 instead of 0 or 1.
> If you MC-cost function is a step function which jumps by 1 for all defects your you might also be able to do variance based sensitivity on it.
> 
> From this little information I can not see how it should be done.
> Since the description of the problem is crucial.

**Comment by jonathf** [comment]
I consider the issue as resolved.

If you consider that not to be the case, or if there are other problems related to the same issue, feel free to re-open.
