### ISSUE TITLE
Wrong results with Scipy 1.13

### ISSUE THREAD

**Issue by mancellin** [jonathf/chaospy#418]
**Describe the bug**
Something changed between Scipy 1.12 and 1.13, that causes Chaospy to return clearly wrong values with the latest version of Scipy.

**To Reproduce**

```shell
$ pip install scipy==1.12
[...]
$ python -c 'import chaospy; print(chaospy.Normal().mom(2))'  
1.0000000000000002
$ pip install scipy==1.13
[...]
$ python -c 'import chaospy; print(chaospy.Normal().mom(2))'
[...]/lib/python3.12/site-packages/scipy/special/_basic.py:2930: RuntimeWarning: overflow encountered in scalar negative
  def corr(k, r): return np.power(k, -r / k) / gamma(r / k + 1) * r
[...]/lib/python3.12/site-packages/scipy/special/_basic.py:2930: RuntimeWarning: overflow encountered in power
  def corr(k, r): return np.power(k, -r / k) / gamma(r / k + 1) * r
inf
```

**Expected behavior**
The result returned by Scipy 1.12 is correct.

**Desktop (please complete the following information):**
 - OS: Linux
 - Python version: 3.12
 - Chaospy version: 4.3.13

**Comment by omnivagant** [comment]
We noticed this in alpinelinux after upgrading our `py3-scipy` to 1.13.0, we consider downgrading to 1.12.1. There is an upcoming 1.13.1 release where it would be good if this was addressed, if it isn't already, https://github.com/scipy/scipy/milestone/84

**Comment by jonathf** [comment]
Looks like `scipy.special.factorial2` can't handle `uint32` dtypes anymore.

I've made a bug report here: https://github.com/scipy/scipy/issues/20580

I see also some of the other tests I have set up fails. I'll have a look and see if we need to make some patches.

**Comment by jonathf** [comment]
Solved upstream.
