### ISSUE TITLE
Distribution normalization and cp.Std magnitude

### ISSUE THREAD

**Issue by pvaezi** [jonathf/chaospy#42]
Hi, 

I am trying to use chaospy for a 5d uncertainty analysis with point collocation method. My problem is that when I don't normalize the distribution to the reference values (don't divide by norm param), the standard deviations become very big, cp.Std(U_hat, dist), after fitting the polynomials with simulation results. cp.E(U_hat, dist) function works properly though. Maybe I don't quite understand the procedure, but shouldn't the method be independent of distribution normalizations?

I have copied the code here:

```
norm = 11602.
Ln = cp.Normal(mu=0.565992, sigma=0.0807134)
LTe = cp.Lognormal(mu=-1.46212, sigma=0.229387)
Ti0 = cp.Normal(mu=0.6, sigma=0.1816)
Tg0 = cp.Normal(mu=5801.0/norm, sigma=2106.9232/norm)
Tgb = cp.Uniform(300./norm,1160./norm)
dist = cp.J(Ln,LTe,Ti0,Tg0,Tgb)
order = 2
P = cp.orth_ttr(order, dist)
nodes = dist.sample(11, "M")
#solve for nodes here...
U_hat = cp.fit_regression(P, nodes, solves, rule="T")
mean = cp.E(U_hat, dist)
std = cp.Std(U_hat, dist)
```

-Payam

**Comment by jonathf** [comment]
Preferable it should, but scaling is a problem.

The topic got discussed in issue #36. Take a look at the discussion, it should answer your question I think.

**Comment by pvaezi** [comment]
Thanks! That was a very useful link! I think the tikhonov regularization was also causing the problem. Switched it to least square method, and it seems fine now!

Thanks for the quick response!

**Comment by jonathf** [comment]
Great.

I consider the issue as resolved.

If you consider that not to be the case, or if there are other problems related to the same issue, feel free to re-open.
