### ISSUE TITLE
Create orthonormal expansion from glexindex output

### ISSUE THREAD

**Issue by oarcelus** [jonathf/chaospy#423]
I would like to know if there is a way to generate an orthonormal expansion of polynomials from the output of glexindex directly.

**Comment by jonathf** [comment]
Sure.

Something like the following?
```python
expansion = cp.prod([
  cp.generate_expansion(order, dist[idx])[glexindex[idx]]
  idx in range(len(dist))
], axis=1)
```
This assumes `dist` is of type `cp.J` and `glexindex` is of type `np.ndarray` with `len(glexindex) == len(dist)`.

**Comment by oarcelus** [comment]
Hi, thanks for the input. I have tried to compare this with `generate_expansion` function directly. And I see there are some differences.

    alpha = cp.glexindex(
                    start=0,
                    stop=p + 1,
                    dimensions=dimension,
                    cross_truncation=q,
                    graded=True,
                    reverse=True,
                ).T

    polyno = cp.prod(
        [
            cp.generate_expansion(
                config.order, config.distribution[idx], normed=True
            )[alpha[idx]]
            for idx in range(dimension)
        ],
        axis=1,
    )

    print(polyno)

    polyno = cp.generate_expansion(
        p,
        config.distribution,
        normed=True,
        graded=True,
        reverse=True,
        cross_truncation=q,
    )

    print(polyno)

There is a difference between the two methods.

[1.7320508075688774*q0 1.7320508075688774*q0 1.7320508075688774*q0
 1.7320508075688774*q0]

[1.0 1.7320508075688774*q3 1.7320508075688774*q2 1.7320508075688774*q1
 1.7320508075688774*q0]

The coefficients look the same but the polynomial functions are not. Here `p = 1` and `dimension=4` and `q=0.5`

**Comment by jonathf** [comment]
Odd. Ill take a look.

**Comment by jonathf** [comment]
I was a bit too quick there. Try: `axis=0`.

**Comment by oarcelus** [comment]
[1.0 1.7320508075688774*q0 1.7320508075688774*q0 1.7320508075688774*q0
 1.7320508075688774*q0]

[1.0 1.7320508075688774*q3 1.7320508075688774*q2 1.7320508075688774*q1
 1.7320508075688774*q0]

I now recover the 1.0 component but still only `q0`'s present. I think since the distribution is indexed `distribution[idx]` it thinks the problem only has a single random variable?

**Comment by jonathf** [comment]
Right. They are all in dim 1.

Here is a working example where each expanstion get assigned their own dim:
```python
import chaospy as cp

qs = cp.variable(4)

dist = cp.J(cp.Normal(), cp.Normal(), cp.Normal(), cp.Normal())
alpha = cp.glexindex(
    start=0,
    stop=2,
    dimensions=len(dist),
    cross_truncation=0.5,
    graded=True,
    reverse=True,
).T
print(alpha)

polyno = cp.prod(
    [
        cp.generate_expansion(
            2, dist[idx], normed=True
        )[alpha[idx]](**{f"q0": qs[idx]})
        for idx in range(len(dist))
    ],
    axis=0,
)

print(polyno.round(4))

polyno = cp.generate_expansion(
    1,
    dist,
    normed=True,
    graded=True,
    reverse=True,
    cross_truncation=0.5,
)

print(polyno.round(4))
```

**Comment by oarcelus** [comment]
Hi! Now it works well. Thanks!

**Comment by oarcelus** [comment]
One last question about this. How can we verify that the polynomials are orthonormal? 

My distribution is Uniform(-1, 1) as you suggested in a previous github post. The associated orthogonal polynomials are of the Legendre type. However, I see in the tables of polynomial families that the concrete distribution is Uniform(-1,1)/2, so maybe the norms of the polynomials are not 1?

**Comment by oarcelus** [comment]
Thank you!
