### ISSUE TITLE
Typo in README Installation?

### ISSUE THREAD

**Issue by Xifus** [jonathf/chaospy#43]
Hi, may I ask if there is a typo in the installation readme?

git clone git@github.com:jonathf/chaospy.git
cd chaospy
pip install -r requirements.txt
python setupy.py install

I wonder if the last line should be "python setup.py install" instead.
Thank you so much for your work :) I really appreciate it!

**Comment by jonathf** [comment]
Thank you.

Yes, that is a typo. Thanks for pointing it out. Fixed now.
