### ISSUE TITLE
Prediction using g-pce

### ISSUE THREAD

**Issue by hamzabuw** [jonathf/chaospy#430]
Dear Jonathan, 

I have a question regarding generalized polynomial chaos expansion(g-pce). When using the model created by g-pce to generate prediction, do I have to transform my unseen input parameter values before make predictions?

I attached the code below for an example. Here I wish to predict for _new_samples_ (input parameter values) using the model _approx_

```

E2 = chaospy.Uniform(0.8*E2_actual, 1.2*E2_actual)
rho = chaospy.Uniform(0.8*rho_actual, 1.2*rho_actual)
h = chaospy.Uniform(0.8*h_actual, 1.2*h_actual)
joint = chaospy.J(E2, rho, h)
distribution_q = joint
distribution_r = chaospy.J(chaospy.Uniform(-1, 1), chaospy.Uniform(-1, 1), chaospy.Uniform(-1, 1))
samples_r = distribution_r.sample(num_samples, rule="sobol")
samples_q = distribution_q.inv(distribution_r.fwd(samples_r))  # to generate evaluations (evals) below

for timestep in range(time_steps):
    evals = MLR[timestep, :]
    polynomial_expansion, norms = chaospy.generate_expansion(order, distribution_r, normed=True, retall=True)
    approx, coefficients = chaospy.fit_regression(polynomial_expansion, samples_r, eval, retall=True)
```
Now I wish to use my model to make predictions:
```
  # Predict on new input parameter samples
  evals_pred = approx(*new_samples)

```

Here do I need to transform my _new_samples_ before using my `approx` model to make prediction?

**Comment by jonathf** [comment]
Yes, that is correct. You need to transform the samples.

**Comment by hamzabuw** [comment]
Thank you.
