### ISSUE TITLE
On regression error for models

### ISSUE THREAD

**Issue by oarcelus** [jonathf/chaospy#432]
Hi again,

I am trying to deal with a model that contains 13 unknown variables (which I understand start to be in the limit of traditional PCE). I am for now trying regression approaches (although I am seeing that model evaluations are robust so spectral projection might be an option). For the regression method I am using the "Generalized PCE" where the sampling is done with `cp.Uniform(-1, 1)` distributions. Once I get my surrogate models, I am trying to see how the error behaves with respect to the order of the expansion and the amount of model evaluations. For this I am following 3 approaches.

1) The one shown in the documentations. Where I calculate the mean using the chaospy builting function and compare the L2-error of the difference between the surrogate mean and the reference mean (100k model evaluations in my case). 
     ```
        mean = cp.E(ysurr, distribution_r)
        error = (mean-refmean)**2```

![image](https://github.com/user-attachments/assets/aa8b9269-17ba-441a-a61f-e32551a49211)

2) The error in point 1) is good, however I then try to evaluate other types of errors. For example in the following reference (https://www.sciencedirect.com/science/article/abs/pii/S0021999110006856) they talk about the following:

![image](https://github.com/user-attachments/assets/f12b0d24-a423-4970-924d-f4f0bdd7178f)

So there is the experimental design "X" and the model evaluations "Y". When calculating the "Empirical Error" (formula 33) they explicitly use the same samples from experimental design "X" to evaluate the difference between the model and surrogate evaluations. This is counter intuitive to me, why do they use the same "X" to evaluate fir the surrogates and to compare them with the model evaluations?. I would expect that a second experimental design "X1" is created to perform as a "test" set to calculate the error. In any case, when following their approach and applying Equation 33 I get the following:

![image](https://github.com/user-attachments/assets/0b199438-0cf6-4294-8c29-3c92645e36f1)

You can see that when only using "X" I get something really different from what I would expect. That the larger the experimental design "X" the larger the error when performing a regression of the polynomial coefficients. This is something I do not understand, and I do not get how in the paper above they get the expected behavior with decreasing errors. Am I seeing some overfitting? In any case the minimum error is of 1e-25, which is ridiculously low.

3) When calculating the "Empirical Error" (formula 33), but now evaluating the models and the surrogates on a second experimental design "X1", different from the training set "X", I get something that makes more sense to me, althout the errors are really not that good.  Which is different from point 1)

![image](https://github.com/user-attachments/assets/4b94cd9f-83a4-4502-ad5a-50e6212d3d99)

So, my questions are:
- Why are the errors from points 1) and 3) are so different? Errors on the mean are much more precise than the "Empirical Errors". Do you have any insight on why could this be?
- Why could it be the behavior of the error in point 2)

If you need more details about the implementation I can give it here without a problem.

Bests,

**Comment by jonathf** [comment]
This brings back memories to my PhD-days.

I am not sure if I am the right person to ask this. My time is limited and the offset has many possible reasons, which is hard for me to say anything sensible about without diving into your problem.

I will note that "Empirical Errors" in (2) looks wierd to me. Traditional statistics explicitly want to avoid self-testing for bias reasons. But the graph tells me just in general that polynomials might be a bad fit for this problem. Using other samples, as you do in (3) makes a lot more sense. It tells me that the model is converging, but you need the high order for the approximation to work.

But in general, PC is a specialized tool for getting high precision statistical moments from a suregat model that othwerwise will not be as precise. So looking at an "Empirical errors" might be useful from a model validation point, it is not where you would expect PC to excelle compare to other suregate models.

Anyways, I hope you find this information useful.

**Comment by oarcelus** [comment]
Thanks you again for the response. Your insights really help any time.

So for what I can understand, the graphs I showed kind of make sense for 2) and 3). The "empirical errors" shown in the paper are "training errors" really. For such a high dimensional problem as a 5th order polynomial expansion with 13 unknowns, the polynomials are "flexible" enough to fit low amounts of samples almost perfectly. However the testing or generalization errors are really high. So yes, they are extremely overfitted. Indeed higher order polynomials would improve the error of the model, but would also need higher number of evaluations to get a good fit.

I would like to understand a bit more you last paragraph. Do you mean that the errors calculated in 3) are not as useful for the PCE? Because what you are really interested in is in representing statistical moments (mean, variance, skewness, ...) precisely? In short, if my interest is to calculate the sobol indices for the 13 parameters, I really just need to have a good surrogate for this statistical indicators. Not a surrogate that perfectly represent each of the model outputs for a given set of samples.

Anyway, I am still learning about all these things. I will try to test the limits a little bet. See if I get a better results by reducing the number of unknown parameter first. I also want to test the sparse-PCE approach of the paper. I will update you if I have any advances.

Best regards,
Oier.

**Comment by jonathf** [comment]
So PCE is useful as a surugate model like many others, but if you are not getting your statistical moments based metrics, I would not use it, as it is specifically for them it performs well. So from a paper point of view, do these other tests to make sure the model isn't giving you non-sensical values, but show the performence of the metrics to illustrate that PCE is a good fit.

Note though that Sobol indices are a type statistical moment, so you are good.
