### ISSUE TITLE
Joining input dist and qoi_dist

### ISSUE THREAD

**Issue by pvaezi** [jonathf/chaospy#44]
Hi, 

I want to make contours of QoI-distribution versus input-distribution after obtaining QoI-distribution using PCM. I am using `cp.J(dist, qoi_dist)` to join the distributions and make multivariate distribution. However, it seems cp.J does not properly create co-variance matrix between two distributions (I believe `qoi_dist` should be a dependent distribution with respect to input `dist`). Is there an easy way to obtain the joined distributions co-variance matrix using `U_hat` and `P`?

I have copied the relevant part of my code here:
```
dist = cp.Lognormal(-0.0408,0.012)
nodes = dist.sample(nosamples,"M")
P = cp.orth_ttr(order, dist)
U_hat = cp.fit_regression(P, nodes, solves, rule="LS")
qoi_dist = cp.QoI_Dist(U_hat, dist)
joined_prob = cp.J(dist, qoi_dist)
x, y = np.meshgrid(x_range, y_range)
prob_pdf = joined_prob.pdf([x, y])
ax.contour(x, y, prob_pdf)
```

Thanks,
Payam

**Comment by jonathf** [comment]
I have looked closer at the code for QoI distribution, and the current implementation uses a sampling scheme to be able to create the distribution. This makes it very difficult to add the proper dependency structure that you are looking for through QoI.

But if all you need is the co-variance between P and U_hat should be straight forward manually for each polynomial in `P` (requires loops in the multivariate case):
```
cov = cp.E(P*U_hat, dist) - cp.E(P, dist)*cp.E(U_hat, dist)
```

**Comment by jonathf** [comment]
Oh, and you can can add that co-variance dependency structure into the joint. E.g.:
```
joined_prob = (joined_prob - cp.E(joined_prob)) / cp.Std(joined_prob) * numpy.linalg.cholesky(cov) + cp.E(joined_prob)
```

**Comment by pvaezi** [comment]
Thanks for the instructive comments. I am still a little confused. Now, `cov` is a covariances vector of `P` with `U_hat`. How is it possible to perform Cholesky decomposition on it?

**Comment by jonathf** [comment]
`cov` in the last equation is the full joint co-variance matrix, not the vector as in the first case. In the case where `len(P) == 2`, give the following matrix:
```
Cov = [[Var(P[0]), Cov(P[0], P[1]), Cov(P[0], Uhat))],
       [Cov(P[0], P[1]), Var(P[1]), Cov(P[1], Uhat)],
       [Cov(P[0], Uhat), Cov(P[1], Uhat), Var(Uhat)]]
```
You should easily be able to generalize upon this using a for-loop or two.

**Comment by pvaezi** [comment]
Oh, I see! I found this conversation very useful. Thanks for your quick response and follow up!

**Comment by jonathf** [comment]
I consider this matter as closed.
