### ISSUE TITLE
Lagrange polynomials

### ISSUE THREAD

**Issue by dlouk** [jonathf/chaospy#45]
Hi there! 

I was trying to use the **_lagrange_polynomial_** function which is in **_chaospy/orthogonal.py_**. I assume that those are the Lagrange basis polynomials. I have encountered the following issues:

1. Calling **_chaospy.orthogonal.lagrange_polynomial([0,1])_** (or with any number combination, as long as there is a zero in there) results in the error "_raise numpy.linalg.LinAlgError("invertable matrix") LinAlgError: invertable matrix_".

2. Calling **_chaospy.orthogonal.lagrange_polynomial([1, 2])_** results in the polynomials **_[-q0^2+2.0q0, 0.5q0^2-0.5q0]_**. However, using the definition of Lagrange polynomials, e.g. https://en.wikipedia.org/wiki/Lagrange_polynomial, one should get **_[-q0+2.0, q0-1.0]_**.

Therefore, I would like to ask what exactly am I missing in how chaospy constructs Lagrange polynomials?

Best regards,
Dimitris

**Comment by jonathf** [comment]
The Lagrange polynomials have been experimental so far, but should work fine. What you have found is a bug.

I've made a quickfix and I it seems to solve the problem. Please let me know if it works as it should now.

**Comment by dlouk** [comment]
Hi again and sorry for the late reply,

I have run the following tests:
1. lagrange_polynomial[1.] or any other test with just one point in the array fails. Error message "Arrays cannot be empty".
2. Same to my first comment, given any array with a zero in it, the lagrange_polynomial function produces the error message "LinAlgError: invertible matrix"
3. Again as before, when the function works, the polynomial order is always one higher than the one I expect, according to theory (e.g. given as input the array [1.0, 2.0]).

Best,
Dimitris

**Comment by jonathf** [comment]
Are you getting the following output?
```
[1]: print chaospy.orthogonal.lagrange_polynomial([0, 1])
[-q0+1.0, q0]

[2]: print chaospy.orthogonal.lagrange_polynomial([1, 2])
[-q0+2.0, q0-1.0]

[3]: print chaospy.orthogonal.lagrange_polynomial([-1, 0, 1])
[0.5q0^2-0.5q0, -q0^2+1.0, 0.5q0^2+0.5q0]
```

If not are you sure you have updated your verision of the repo. If not:
* Download/update the repo
* (re)install with `python setup.py install`
* then try to run it again.

**Comment by dlouk** [comment]
Hi again and thanks for the quick reply,

I updated the repo, but the last change I see is from 5 months ago (Sun Dec 18, according to git log), so I do not get your results. They do look good though, thanks for checking it.

Best,
Dimitris

**Comment by jonathf** [comment]
Sorry about that. I pushed it directly to `master`, which I really shouldn't.

I merged the changes to the `development` branch now.
Do git pull and you should see the updates.

**Comment by dlouk** [comment]
Hi again,

one small thing that I noticed: if one gives as input an array with just one point, then the result is not the expected one, e.g.:
print cp.orthogonal.lagrange_polynomial([1])  --> q0-1.0
print cp.orthogonal.lagrange_polynomial([0]) --> q0

I would have expected a constant, e.g. 1.0.

Thanks for your time and effort and best regards,
Dimitris

**Comment by jonathf** [comment]
Thank you. I made the fix for the single point as well now, and added it to development.

I consider the issue as close. If that is not the case, feel free to reopen.
