### ISSUE TITLE
New truncation schemes

### ISSUE THREAD

**Issue by Phesao** [jonathf/chaospy#49]
Hello there,

I came across chaospy recently and it is really helpful. Just wanted to mention that one could easily improve the scalability of the regression approaches towards higher input dimensionality by limiting the number of polynomial basis functions a priori. For example, one could rely on some hyperbolic cross truncation scheme, or limit the number of interactions between the variables. Such features would make the software much more powerful.

Regards
Ben

**Comment by jonathf** [comment]
I am not aware of the hyperbolic cross truncation scheme, but I agree, that having a better selection scheme for what polynomials to choose in higher dimensions would be nice.

I could likely churn through google scholar, but prefer recommendations. Do you know any papers/introductions/tutorials on the topic that you could recommend?

**Comment by flapingwings** [comment]
If I understand correctly, hyperbolic cross truncation does what Smolyak sparse grid algorithm do (which is already implemented in chaospy.

**Comment by jonathf** [comment]
So, the Smolyak sparse grid truncation only becomes visible if the growth rule (the number of nodes between collocation order) is non-linear. To mock this behavior I had to add a new `cross_truncation` parameter.

I've added the features into the polynomial creation schemes. E.g.:
```
[3]: print(cp.orth_ttr(3, cp.Iid(cp.normal(), 2), cross_truncation=1)) # default no-truncation behavior
[1.0, q1, q0, q1^2-1.0, q0q1, q0^2-1.0, q1^3-3.0q1, q0q1^2-q0, q0^2q1-q1, q0^3-3.0q0]

[2]: print(cp.orth_ttr(3, cp.Iid(cp.normal(), 2), cross_truncation=1.5))
[1.0, q1, q0, q1^2-1.0, q0q1, q0^2-1.0, q1^3-3.0q1, q0^3-3.0q0]

[3]: print(cp.orth_ttr(3, cp.Iid(cp.normal(), 2), cross_truncation=2))
[1.0, q1, q0, q1^2-1.0, q0^2-1.0, q1^3-3.0q1, q0^3-3.0q0]
```
Does this look about right?

Feel free to checkout the branch `cross_truncation` if you want to take a look at the feature for yourself.

**Comment by flapingwings** [comment]
Thanks for the new feature. This is perfect.

**Comment by jonathf** [comment]
This is added to master now, and I consider the matter as closed.
