### ISSUE TITLE
License

### ISSUE THREAD

**Issue by utsekaj42** [jonathf/chaospy#50]
Hi,

I was creating a conda-build file for chaospy and noticed there is no license file. It's stated in setup.py that it is a BSD license or a MIT compatible license, while most of the libraries included are GPL.  I think it would be good to have an explicit license file for chaospy, as well as to be clear which BSD or MIT compatible license actually applies.

Best,
Jacob

**Comment by jonathf** [comment]
Good point. Adding BSD licence now.
