### ISSUE TITLE
test failure during installing chaospy in mac OS version 10.12.5

### ISSUE THREAD

**Issue by cc636489** [jonathf/chaospy#52]
Hello! Jonathan,

Thank you first of all about this program, it's very useful and helpful. Previously I install chaosy in linux machine successfully following the given steps. But things start fail when I try to install it in my macOS 10.12.5. Attachment is the stdout for running "python setup.py test". Could you provide any guidance about it?

Thank you,
Chen
[chaospy_test_stdout.txt](https://github.com/jonathf/chaospy/files/1081680/chaospy_test_stdout.txt)

**Comment by jonathf** [comment]
I believe the problem isn't related to OSX as much the dependency Numpy just deprecated some operators chaospy was using.

I fix the problem areas in chaospy just now and pushed the update. Please let me know if the fixes works for you.

**Comment by jonathf** [comment]
I assume that the matter is closed. If that is not the case, please feel free to reopen.
