### ISSUE TITLE
errors in orth_bert

### ISSUE THREAD

**Issue by utsekaj42** [jonathf/chaospy#54]
```
n = cp.Normal(0, 1)
polynomial_order = 3
poly = cp.orth_bert(polynomial_order, n, normed=True)
```
doesn't work for me.

The first issue was in chaospy/poly/basy.py line 200 was not checking for numpy.int types. I fixed this in my [devbranch](https://github.com/utsekaj42/chaospy/commit/2059f75e32ad1037e1e4063863110c0cd280f1c7) but now the error occurs when numpy's asarray calss __iter__ . This seemed likely some special edge case for a 1D polynomial expansion, however, trying the following produces the same "not iterable" error. Any ideas on the correct way to fix this?

```
n = cp.Normal(0, 1)
n = cp.Iid(n,2)
polynomial_order = 3
poly = cp.orth_bert(polynomial_order, n, normed=True)
```

**Comment by jonathf** [comment]
The function `orth_bert` is a legacy feature that I planed to deprecate. (If you look in the `development` branch, it isn't there anymore.)

If you have a usecase where you need `orth_bert`, I'll both reinstate it, and fix the corner case. Let me know if that is the case.

**Comment by utsekaj42** [comment]
I don't need it. It was just in a tutorial I was updating. Though it does appear to me that it's still in the development branch (orthogonal.py lines 304ff).

**Comment by jonathf** [comment]
Ah, sorry, to quick on the trigger finger. The branch I am referring to is `jf_pep8` which is my current experimental branch, not `development`.

Okay, then I consider this a non-issue as the function is about to be removed.
