### ISSUE TITLE
folded normal distribution 

### ISSUE THREAD

**Issue by cepez** [jonathf/chaospy#55]
Hi again, 

Could you please give some tips about how to build a folded normal distribution?
I was expecting some parameters like mu,sigma and the location of the fold, however there are not 
such arguments in this function.

   Thanks!

**Comment by jonathf** [comment]
I presume that you found the `cp.foldnorm` class since correctly it does not contain those features. Take a look at the constructor `cp.Foldnorm`. It should contain what you are looking for.
