### ISSUE TITLE
Saving a PCE regression 

### ISSUE THREAD

**Issue by Argantonio65** [jonathf/chaospy#56]
Hello, 

Thanks for this contribution. It is simply a pleasure to use your package!

I was wondering if there is a way to "store" a fitted regression for a point-collocated PCE. 
On a long dataset, the regression can take a few minutes and I would like to avoid refitting whenever I would like to make use of the surrogate model. 

Thanks in advance,
Best regards

**Comment by jonathf** [comment]
I am glad to hear that.

All distributions and polynomials support saving to and loading from disk using built-in `pickle`.

If you want to reduce the amount of space the model takes on disk, you can just save the expansion's data content instead. Here is how that would work:
```python
import pickle

# save to disk
with open("path/to/file", "w") as filehandler:
    pickle.dump(pce_expansion.A, filehandler)

# load from disk:
with open("path/to/file", "r") as filehandler:
    pce_expansion = chaospy.Poly(pickle.load(filehandler))
```

**Comment by Argantonio65** [comment]
That makes it! 

Thanks a lot.

**Comment by shehan807** [comment]
Hello @Argantonio65 and @jonathf, 

I am a new user of Chaospy and had a quick follow-up question regarding this thread: 

Is the "A" attribute that follows the `pce_expansion` variable just a placeholder in this example or is it required to save the `pce_expansion` to a pickle file? I am trying to save a quadrature fit myself based on the following code

```js
distr = cp.J(x_var, y_var)
nodes, weights = cp.generate_quadrature(3, distr, rule='Gaussian')
samples = [solver(input1, node[0], node[1]) for node in nodes.T]
poly = cp.orth_ttr(order=3, dist=distr)
model = cp.fit_quadrature(poly, nodes, weights, samples)

with open('model.pkl') as filehandler: 
     pickle.dump(model.A, filehandler)
```

Resulting in 

```js
AttributeError: 'ndpoly' object has no attribute 'A'
```

When I remove this attribute and try to just save the `model` variable to the pickle file, I get the following error: 

```js
TypeError: write() argument must be str, not bytes
```

Any advice on this would be greatly appreciated, thanks!
