### ISSUE TITLE
Theory Guide - SerialLayers function

### ISSUE THREAD

**Issue by mluckeroth** [jonathf/chaospy#57]
In 1.3 Tutorial of the Theory Guide there is a function called SerialLayers that I cannot find any reference or documentation for.  Can you add this to the example python code?

**Comment by jonathf** [comment]
Sure.

I've pushed the files to `development` branch as `tutorial/flow_in_serial_layers.py` and `tutorial/Heaviside.py`.

**Comment by jonathf** [comment]
I consider the issue as resolved.
