### ISSUE TITLE
Truncated Gamma distribution?

### ISSUE THREAD

**Issue by Confareneoclassico** [jonathf/chaospy#58]
Hi,

I am a novel user and probably this question is very trivial - I'll try to ask it anyways.

I would need to generate a distribution type (truncated gamma, having an upper threshold in addition to the lower) non included in the list of default distribution, from which I should select a sample according to the Sobol rule. I know I could simply generate the distribution with _SciPy_ and then try to extract a sample coding the Sobol-rule algorithm it. However, I was wondering if there was any _ChaosPy_ functionality that would allow to tackle this issue straightforwardly.

Many thanks in advance for your help and apologies for my question, should it be too trivial. :)

**Comment by jonathf** [comment]
something like this perhaps?
```
dist = cp.trunk(cp.Gamma(4, 2), 5)
dist.sample(10, rule="S")
```

**Comment by Confareneoclassico** [comment]
That is exactly what I was looking for.

Thank you so much, Jonathan!

Cheers,
-Sam
