### ISSUE TITLE
PCE of a set of data points

### ISSUE THREAD

**Issue by phauseux** [jonathf/chaospy#6]
Hi, I am a postdoc researcher at Université du Luxembourg.

I have a vector which contains a set of data points (Monte-Carlo realisations).

I would like to use chaospy to compute the PCE of the data points by choosing the order and the type of polynomials (Hermite, Jacobi, etc.).

Sincerely,
Paul.

**Comment by jonathf** [comment]
I'm assuming you are wondering how to go about to do this.

Here is an example of how that is done:

    import chaospy as cp

    # select distribution
    dist = cp.Normal(0, 1) # Hermite
    #dist = cp.Beta(a, b) # Jacobi

    # generate polynomials
    polyOrder = 3
    orth_poly = cp.orth_ttr(polyOrder, dist)

    # join together
    func_approx = cp.fit_regression(orth_poly, dataPoints, evaluations)

    # analysis
    print cp.E(func_approx, dist), cp.Var(func_approx, dist)

**Comment by jonathf** [comment]
If you choose higher order polynomials, proper use of normalizing constants become important.
This can be implemented as follows:

    orth_poly, norms = cp.orth_ttr(polyOrder, dist, retall=True)
    func_approx = cp.fit_regression(orth_poly, dataPoints, evaluations, norms=norms)

**Comment by phauseux** [comment]
Ok thanks a lot for your help !
Sincerely,
Paul
________________________________
De : Jonathan Feinberg [notifications@github.com]
Envoyé : mardi 19 janvier 2016 17:22
À : hplgit/chaospy
Cc : Paul HAUSEUX
Objet : Re: [chaospy] PCE of a set of data points (#6)


I'm assuming you are wondering how to go about to do this.

Here is an example of how that is done:

import chaospy as cp

# select distribution
dist = cp.Normal(0, 1) # Hermite
#dist = cp.Beta(a, b) # Jacobi

# generate polynomials
polyOrder = 3
orth_poly = cp.orth_ttr(polyOrder, dist)

# join together
func_approx = cp.fit_regression(orth_poly, dataPoints, evaluations)

# analysis
print cp.E(func_approx, dist), cp.Var(func_approx, dist)

**Comment by phauseux** [comment]
Hello,

I don't understand what is evaluations in:

# join together
func_approx = cp.fit_regression(orth_poly, dataPoints, evaluations)

In fact I have a set of datat points in a vector (for example u[0]=1.2, u[1]=1.4, etc.)
and I want to write u like u = u_0 + u_1 q0 + u_2 (q0^2-1) + ...
with q0 a gaussian variable N(0,1)

Thanks,
Paul.



________________________________
De : Jonathan Feinberg [notifications@github.com]
Envoyé : mardi 19 janvier 2016 17:22
À : hplgit/chaospy
Cc : Paul HAUSEUX
Objet : Re: [chaospy] PCE of a set of data points (#6)


I'm assuming you are wondering how to go about to do this.

Here is an example of how that is done:

import chaospy as cp

# select distribution
dist = cp.Normal(0, 1) # Hermite
#dist = cp.Beta(a, b) # Jacobi

# generate polynomials
polyOrder = 3
orth_poly = cp.orth_ttr(polyOrder, dist)

# join together
func_approx = cp.fit_regression(orth_poly, dataPoints, evaluations)

# analysis
print cp.E(func_approx, dist), cp.Var(func_approx, dist)

**Comment by jonathf** [comment]
If `u` is your model to be approximated, then `evaluations` and `dataPoints` are related as follows:

    evaluations = [u(Q) for Q in dataPoints]

In other words, given your `dataPoints`, (typically generated from your every day random number generator in MC,) evaluations are your model function evaluation at those points.

**Comment by jonathf** [comment]
A full experiment would look as follows:

    dist = cp.Normal(0,1)
    noSamples = 100
    dataPoints = dist.sample(noSample)

    evaluations = [u(Q) for Q in dataPoints]

    polyOrder = 3
    orthPoly = cp.orth_ttr(polyOrder, dist)

    approx = cp.fit_regression(orthPoly, dataPoints, evaluations)

**Comment by phauseux** [comment]
Thank you for your help. I understand now.
________________________________
De : Jonathan Feinberg [notifications@github.com]
Envoyé : mercredi 20 janvier 2016 11:15
À : hplgit/chaospy
Cc : Paul HAUSEUX
Objet : Re: [chaospy] PCE of a set of data points (#6)


A full experiment would look as follows:

dist = cp.Normal(0,1)
noSamples = 100
dataPoints = dist.sample(noSample)

evaluations = [u(Q) for Q in dataPoints]

polyOrder = 3
orthPoly = cp.orth_ttr(polyOrder, dist)

approx = cp.fit_regression(orthPoly, dataPoints, evaluations)

**Comment by phauseux** [comment]
Dear Jonathan,
In dimension 3 for example that works:

distribution = cp.J(cp.Normal(0,1), cp.Normal(0,1), cp.Normal(0,1))

How can I write it in dimension n (in an concise manner) ?
Thanks,
Paul.

**Comment by jonathf** [comment]
The simplest solution is to use `cp.Iid`:
```
distribution = cp.Iid(cp.Normal(0, 1), n)
```
Hope this helps.

**Comment by phauseux** [comment]
yes thanks !

**Comment by phauseux** [comment]
Dear Jonathan,

I work with random fields with a large stochastic dimension ( m > 100)
When I want to evaluate the Sobol'indices, the number of dimensions must be within [0, 32].
It is possible to work with m > 32 ?
thanks,

Paul.

**Comment by jonathf** [comment]
I am sorry for the question, but for clarification, are we talking about variance based sensitivity analysis or quasi-random samples? Both have the name Sobol indices and both are available in the library.

**Comment by phauseux** [comment]
I am talking about variance based sensitivity analysis

**Comment by jonathf** [comment]
I was not aware that there where an 32-dimensional limitation on the sensitivity methods.
They might not be constructed for such high dimensions and be very slow, but as far as I know there is no such limitation.

Are you getting any errors? If so, do you mind posting the traceback?

**Comment by phauseux** [comment]
I have this error:

Traceback (most recent call last):
  File "sobol.py", line 27, in <module>
    SA_ordre1 = cp.Sens_m(f_pce, distribution, retall=True)
  File "/home/fenics/src/chaospy/chaospy/descriptives.py", line 808, in Sens_m
    out[i] = Var(E_cond(poly, zero, dist, **kws), dist, **kws)/(V+(V==0))*(V!=0)
  File "/home/fenics/src/chaospy/chaospy/descriptives.py", line 754, in E_cond
    keys = [i for i in np.ndindex(*kmax)]
  File "/usr/lib/python2.7/dist-packages/numpy/lib/index_tricks.py", line 559, in __init__
    strides=_nx.zeros_like(shape))
  File "/usr/lib/python2.7/dist-packages/numpy/lib/stride_tricks.py", line 48, in as_strided
    array = np.asarray(DummyArray(interface, base=x))
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: number of dimensions must be within [0, 32]

**Comment by phauseux** [comment]
----------------------------------------------------------------------------------------------------
polyOrder = 2
nbmodes = 32
distribution = cp.Iid(cp.Normal(0, 1), nbmodes)
orth_poly, norms = cp.orth_ttr(polyOrder, distribution, retall=True)		
f_pce = cp.fit_regression(orth_poly, [omega[i] for i in range(0, nbmodes)], evaluations, norms=norms)
SA_ordre1 = cp.Sens_m(f_pce, distribution, retall=True)
----------------------------------------------------------------------------------------------------

with nbmodes = 32 It works but with nbmodes > 32, I get the above error.

**Comment by jonathf** [comment]
Okay, that made more sense.

As part of calculating the conditional expectation I make use of ``numpy.ndindex`` function. However there is a limitation in ``numpy`` for the number of axes it support, which you are experiencing for your use case.

The problem function in question can be replaced, but I will have to write the function in question, which I don't have time for this second. Give me a couple of weeks and I should have a fix ready.

**Comment by phauseux** [comment]
ok thank you !

**Comment by jonathf** [comment]
I apologies that it took longer than I said it would, but the problem should be solved now.

I have only tested it against the tiny example you provided. Let me know if it work on the large problem as well.

If it doesn't feel free to re-open the issue.

**Comment by phauseux** [comment]
Thank you for your help. Yes it works. 
It is very slow (but it is normal when the dimension is large).

**Comment by phauseux** [comment]
Dear Jonathan,

I am in dimension 10 and I evaluate the PCE:
...
f_pce = cp.fit_regression(orth_poly, omega, samples, norms=norms)
...
I want to evaluate the PCE at a specific point:

print f_pce(0.4, 0.3, 0.4, 0.5, 0.5, 0.5, 0.4, 0.5, 0.4, 0.3) WORKS

how can I write in a concise manner ? like:
print f_pce(point) with point = [0.4, 0.3, 0.4, 0.5, 0.5, 0.5, 0.4, 0.5, 0.4, 0.3]

Thanks for your help.
Paul.

**Comment by phauseux** [comment]
Ok I have the solution. It is necessary to add a *:
print f_pce(*point)
