### ISSUE TITLE
ModuleNotFoundError: No module named 'chaospy.quadrature'

### ISSUE THREAD

**Issue by jschueller** [jonathf/chaospy#61]
after installing latest v2.2.4 I cannot even import chaospy, v2.2.3 seems ok though

**Comment by jonathf** [comment]
I am not having any such problems. Weird.

I've not pushed v2.2.4 to PyPi so I assume you did manual install from git tag.

I have now pushed 2.2.4 to PyPi now so you should be able to do `pip install chaospy==2.2.4`. If that doesn't work, do you mind letting me know what version of Python and OS you are on?

**Comment by jschueller** [comment]
pypi version is ok, if you look at the tag there's an "import chaospy.quadrature" in poly/collection/core.py which fails

**Comment by jschueller** [comment]
it's missing https://github.com/jonathf/chaospy/commit/c0184604164459934ef58872de66a42f1ab435a9

**Comment by jonathf** [comment]
Yes, you are right it was.

I have moved the tag forward one step ow to include the patch. (It is the same as the one uploaded to Pypi.)

Thank you for catching it.
