### ISSUE TITLE
Using partial derivatives of model response in polynomial expansion

### ISSUE THREAD

**Issue by flapingwings** [jonathf/chaospy#68]
I see that in your doctoral thesis you mentioned that - 

> To be able to incorporate partial derivatives of the response, the partial derivative of the polynomial expansion must be available as well. In both Turns and Chaospy, the derivative of a polynomial can be generated easily.

I am using least square regression method to obtain the coefficients in polynomial chaos expansion, therefore, my objective is to obtain a set of linear algebraic equations of the form **A.x = B**. The coefficient matrix **A** will contain both shape functions and their partial derivatives evaluated at regression points.

Could you please elaborate a bit on how I can obtain the partial derivative of shape functions if I want to use the gradient information of model response.

**Comment by jonathf** [comment]
Without more details it is unclear to me exactly what you need. But I can answer on a general note, and you can let me know if that does not solve your problem.

Derivative of the uncertain parameters can be done in a single variable using `differential`:
```
>>> p = cp.orth_ttr(2, cp.Iid(cp.Normal(), 3))
>>> print(p)
[1.0, q2, q1, q0, q2^2-1.0, q1q2, q0q2, q1^2-1.0, q0q1, q0^2-1.0]
>>> x, y, z = cp.variable(3)
>>> print(cp.differential(p, x))
[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, q2, 0.0, q1, 2.0q0]
>>> print(cp.differential(p, y))
[0.0, 0.0, 1.0, 0.0, 0.0, q2, 0.0, 2.0q1, q0, 0.0]
```
Or if you need all derivative in all variables at once, use `gradient`:
```
>>> print(cp.gradient(p))
[[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, q2, 0.0, q1, 2.0q0],
 [0.0, 0.0, 1.0, 0.0, 0.0, q2, 0.0, 2.0q1, q0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 2.0q2, q1, q0, 0.0, 0.0, 0.0]]
```

If the output polynomial has a temporal/spacial axis that needs differentiating, chaospy can not help you. But in that case, you are likely already in a discretized space, and using an approximation formula should be easy.

**Comment by flapingwings** [comment]
Thank you, exactly what I needed.
