### ISSUE TITLE
Saving Chaospy Objects to File

### ISSUE THREAD

**Issue by pvaezi** [jonathf/chaospy#69]
Hi,

Is there anyway I can save the Chaospy objects to the file? I couldn't pickle them.

Thanks,
Payam

**Comment by jonathf** [comment]
The chaospy objects should be picklable, so if it is failing it is a bug.

Do you mind providing OS, Python version, Chaospy version, and a minimal code example that replicates the behavior?

**Comment by flo2k** [comment]
I also have this problems when pickling distributions. For loading/saving I moved to the [dill](https://pypi.python.org/pypi/dill) library. With dill it works perfectly for me.

**Comment by jonathf** [comment]
Thank you @flo2k. That is a good suggestion.

I will also note that this problem is not reproducible in Python3. So if you end up having to upgrade your code to the newest python, pickling choaspy distributions will work out of the box.

**Comment by pvaezi** [comment]
Thanks for the comments, using dill library solved my problem.
