### ISSUE TITLE
Is it possible to directly evaluate the polynomial surrogate?

### ISSUE THREAD

**Issue by kilojoules** [jonathf/chaospy#70]
I'm in a situation where I want to be able to directly evaluate the polynomial surrogate. For example, I want to evaluate `foo_approx` at specified points in the uncertain space. Can this be done with `chaospy`?

    import chaospy as cp
    import numpy as np
    
    def foo(coord, param):
       return param[0] * np.sin(coord) + param[1] * np.sin(coord * 30)
    
    coord = np.linspace(0, 10, 200)
    distribution = cp.J(
         cp.Normal(1, 0.6),
         cp.Normal(2, 0.2)
     )
    
    polynomial_expansion = cp.orth_ttr(3, distribution)
    
    samples = distribution.sample(50)
    evals = [foo(coord, sample) for sample in samples.T]
    
    foo_approx = cp.fit_regression(polynomial_expansion, samples, evals, rule='T')
    
    # Now I want to evaluate the polynomial surrogate at param = [1.5, 1.5]

**Comment by flo2k** [comment]
Hi, just use:

`vals = foo_approx(1.5, 1.5)`

**Comment by kilojoules** [comment]
@flo2k Thanks very much! Is it possible to also evaluate local derivatives? As in, can I find the derivative of the polynomial expansion with respect to each input, given a point of interest?

**Comment by flo2k** [comment]
@jonathf can you answer that question? I'm not soo deep in the polynomial class functions.

**Comment by jonathf** [comment]
Sure. E.g.

    foo_grad = chaospy.gradient(foo_approx)
    vals = foo_grad(1.5, 1.5)

The gradient function expands the polynomial function with an extra dimensions, as it contains the derviative along all axes. So `vals[0]` contains "d foo / d q0" and `vals[1]` contains `d foo / d q1`.
