### ISSUE TITLE
Concerning shoot-up in memory usage while calculating Sobol's Indices   

### ISSUE THREAD

**Issue by flapingwings** [jonathf/chaospy#71]
[Sobolsindices.txt](https://github.com/jonathf/chaospy/files/1692000/Sobolsindices.txt)
Hi Jonathan,

I found that the memory usage for my computer shoots up while calculating Sobol's Indices when the number of random variables is higher than 14.

As I understand the calculation of cartesian product in function E_cond() causes this problem.

Could you please suggest a work-around for this problem.

Note: Please see the file attached

**Comment by jonathf** [comment]
Hey!

Yea, that didn't look right.

I have add a bugfix in the branch `development` now, if you want to try.

BTW, if you are not familiar, you might want to look into `cp.Iid(cp.Uniform(0, 1), 16)` to simplify the distribution construction in your example there.

**Comment by flapingwings** [comment]
Thank you.
