### ISSUE TITLE
Bug with joint probability distribution

### ISSUE THREAD

**Issue by RRiva** [jonathf/chaospy#73]
Hi,

I've recently started using chaospy, and I might have found a bug with the joint probability distributions.
Here is an example.

```
import numpy as np
import chaospy as cp

dist_1 = cp.Uniform(-7.0, 15.0)
dist_2 = cp.Uniform(-3.0, 2.0)

dist_J = cp.J(dist_1, dist_2)

dist_J * 2.0
```

Changing the last line into `dist_J * np.array([[2.0]])` causes the code to crash somewhere else.

Best regards,
Riccardo

**Comment by jonathf** [comment]
Yes. Multiplying a multivariate distribution with a scalar isn't supported.

I've added a fix to `development` branch. Let me know if it solves the problem.

**Comment by RRiva** [comment]
Yes, it does. Thank you very much!
