### ISSUE TITLE
Extract the Fourier Coefficients

### ISSUE THREAD

**Issue by marcrocasalonso** [jonathf/chaospy#74]
First of all, thanks you for your time.

My issue is how to determine or if exist a function to determine the Fourier coeffcients **_C_n_** from a Surrogate Model created with _fit.quadrature function_.

For example:

Surrogate Model= 0.13*q0+0.1*q1-10
Hermite Polynomial =[1,q1-100,q0-25.13]

Y=QoI=C0*Psi_0 + C1*Psi_1 + C2*Psi_2 = C0*(1)+ C1*(q1-100) + C2*(q0-25.13)

**Comment by jonathf** [comment]
It isn't documented very well, but you can add the flag `retall=True` to the `fit_quadrature` function, and it will return both the approximation function and coefficients as tuple:
```
surrogate, coefficients = cp.fit_quadrature(..., retall=True)
```
Hope this solves your problem.

**Comment by marcrocasalonso** [comment]
Thank you very much! You have solved my problem so quickly.
