### ISSUE TITLE
Total effect Sobol Indices in Monte Carlo approach

### ISSUE THREAD

**Issue by marcrocasalonso** [jonathf/chaospy#81]
First of all, thank you for your time.
I have a doubt with how to make Sobol Sensitivity analysis with Monte Carlo implementation because the Sobol function needs a polynomial surrogate model.

I have for example:

- 3 random parameters with Normal distribution.
- 100 simulations of our QoI with above input parameters.
- QoI=[QoI_1,QoI_2,...,QoI_100]
- How to make Sobol Indices of this 3 random inputs with respect QoI?

thank you very much!!!

**Comment by jonathf** [comment]
If you want to do this using traditional Monte Carlo, then Saltelli's method is what you are looking for. The procedure is described on the wikipedia article: https://en.wikipedia.org/wiki/Variance-based_sensitivity_analysis

If however you want to use polynominal chaos expansion, you do the following:
```
distributions = chaospy.Iid(chaospy.Normal(0, 1), 3)
polynomials = chaospy.orth_ttr(order, distributions)
approx_model = chaospy.fit_regression(polynomials, dist_samples, QoI)
total_sens = chaospy.Sens_t(approx_model, distributions)
```
Here `order` is the polynomial order. I usually set it at around 7, but you can obviously experiment.
The `dist_samples` are the samples generated from the Normal distribution and used as input to calculate your QoI.

Hope this is helpful.

**Comment by marcrocasalonso** [comment]
Thank you! I have implemented with PC the Sobol Indices and give good results, but now I wanted to compare with Montecarlo Sobol Indices becuase I have only lineal correlation indices implemented with MC and it's not the same.

Thank you, I will discard this comparation between Sobol indices with this two methods

**Comment by jonathf** [comment]
Well, if you are using only 100 samples I expect there should be allot of noise in your results. This goes double for Saltelli's method which effectively halves the number of samples in your set for calculating indices.

Try turning the number of samples up to 10000 to verify what the methods converge towards. If you can not afford this computationally, switch out your QoI with something cheaper to see. If they both converge to the same value, this is a strong indicator that both methods are implemented correctly and the low samples size is the cause of your discrepency.

**Comment by marcrocasalonso** [comment]
I'm only launch 100 samples becuase each QoI simulations needs 15hours... because I'm doing a crashworthiness stochastic approach.

**Comment by jonathf** [comment]
Then you are using the right tool for the job I think.

The suggestion was more of a sanity check to ensure that you have implemented the method correctly. Replace QoI with a dummy where you can run 10k samples easily. If that works, it is a good indicator that you haven't done anything wrong code-wise for the sensitivity analysis part. This is just a suggestion to ease your mind about the results. I made them since you seemed to be concerned that PCE and MC produced different results.

Ignoring that, stick to PCE as I suggested and you should be fine.

**Comment by marcrocasalonso** [comment]
Thank you very much for your advices! See you soon! 

Marc
