### ISSUE TITLE
Sobol sensitivity indices

### ISSUE THREAD

**Issue by joventino** [jonathf/chaospy#85]
Dear Jonathf,

I am trying to use the sensitivity indices functions from ChaosPy in a cardiac mechanics problem. Four parameters was considered as uncertain and a quantity of interest with a low variance was analysed. I am expecting that the main sensitivity indices would be close to zero for all parameters, due to the low variance (Var = 5.0549893493e-26). However, the main sensitivity index for the second parameter was 0.96500090321 when I used the function Sens_m.
Then I tried to compute this index manually using the functions Var and E_cod. I found the same value for the index, but I could see that the conditional variance was Cond_Var = 5.28776503722e-28 and variance was Var = 5.0549893493e-26. So, when I computed the index Si = Cond_Var/Var, the result is 0.96500090321.

Shouldn't this sensitivity index be zero? If yes, how can I fix this error?

Seeing your function:
```
def Sens_m(poly, dist, **kws):
    """
    Variance-based decomposition
    AKA Sobol' indices
    First order sensitivity indices
    """
    dim = len(dist)
    if poly.dim<dim:
        poly = chaospy.poly.setdim(poly, len(dist))

    zero = [0]*dim
    out = np.zeros((dim,) + poly.shape)
    V = Var(poly, dist, **kws)
    for i in range(dim):
        zero[i] = 1
        **out[i] = Var(E_cond(poly, zero, dist, **kws), dist, **kws)/(V+(V == 0))*(V != 0)**
        zero[i] = 0
    return out
```
I thought in changing the bold line to:
`out[i] = Var(E_cond(poly, zero, dist, **kws), dist, **kws)/(V+(V < 1e-16))*(V > 1e-16)`

What do you think?

**Comment by jonathf** [comment]
Main sensitivity indices are normalized such that `sum(main_indices) == 1`. So having a variable around 0.956 is not unreasonable. It sounds more like you want to just decompose the variance. You can do this by multiplying the indices with the total variance. See the difference in definition between `Si` and `Vi` in the Wikipedia article for Sobol indices:
https://en.wikipedia.org/wiki/Variance-based_sensitivity_analysis

**Comment by joventino** [comment]
Thank you for your kind answer!
I think I was not so clear. 
My question is: Are these Si results reliable even when the variance is close to zero (1e-26) ?
Should I discard this quantity of interest, considering that the variance is very low?

**Comment by jonathf** [comment]
Okay, then I misunderstood.

The scale of the problem shouldn't matter. Here is a dummy example scaling down:
```
import chaospy as cp

x, y, z = cp.variable(3)
P = x + 0.1*y + 0.001*z + 1
dist = cp.Iid(cp.Uniform(0, 1e-26), 3)

print(cp.Sens_m(1e-40*P, dist))
print(cp.Sens_m(1e-20*P, dist))
print(cp.Sens_m(P, dist))
print(cp.Sens_m(1e20*P, dist))
print(cp.Sens_m((P-cp.E(P, dist))/cp.Std(P, dist), dist))
```
Same as you: very tiny variation, one variable sticking out. Since this is sensitivity analysis, multiplying the model by a constant should have no effect on the output. And indeed it is: The results are the same for all versions.

Thinking the problem through I do think what you are describing could be a problem in some cases. So I had to test the idea for my self to be more confident with the assertion that it indeed was stable at those levels. To be sure in your case in particular, I recommend you do a similar test as I did with your own code.

**Comment by joventino** [comment]
I think my problem is before the sensitivity analysis. The quantity of interest fitted by the Polynomial Chaos has a low variation, then the resultant polynomial was almost a constant:

```
P = 3.62354276098e-15*q0**2-1.61042288039e-14*q1**2-9.20482010298e-15*q0*q1-\
2.70628953576e-14*q0*q2+1.51116446873e-14*q0*q3+6.13505508343e-14*q0-\
2.92263052108e-15*q1*q2+5.98936619873e-15*q2**2+1.92608363839e-14*q1*q3-\
1.97322022956e-14*q1+2.11207259955e-14*q2*q3-2.13668367458e-14*q2-\
3.19917115398e-14*q3**2-1.62539344105e-14*q3+76.5821
```

where all the coefficients are very low, except the independent term. And when I performed the sensitivity analysis using this polynomial, the most sensitive parameter seems to be the parameter with the high magnitude value:

```
C = cp.Normal(1.1,0.165)
bf=cp.Normal(6.6,0.99)
bt=cp.Normal(4.0,0.6)
bfs=cp.Normal(2.6,0.39)
dist = cp.J(C, bf, bt, bfs)

print(cp.Sens_m(P, dist)):
```

[0.00235065 0.9776656  0.00916712 0.00861232]

**Comment by jonathf** [comment]
That is not much, indeed.

What I would recommend for you is to transform your evaluations before creating your approximation.
Something like:
```
values = (values - 76.5821) * 1e15
P = cp.fit_regression(orth, dist, nodes, values)
print(cp.E(P, dist)*1e-15 + 76.5821) # mean
print(cp.Sens_m(P, dist)) # sensitivity is not affected by scaling
```

If this gives the same results, you should be safe.

**Comment by joventino** [comment]
Thank you very much for your help!
When I transformed the evaluations, the result was different and now it makes sense.

**Comment by jonathf** [comment]
I am glad you were able to solve your problem.
