### ISSUE TITLE
Help me in the Non-Intrusive Polynomial Chaos Methods (Point collocation)

### ISSUE THREAD

**Issue by nguyenhoaiThanhbk2811** [jonathf/chaospy#92]
Hi you,
I have a problem. I defined my parameter in the problem is Uniform (0.9,1.1). Via experiment, I have the output corresponding to (0.024,0.02456). And then when I use 3rd Order I have the value (0.9, 1.0, 1.1) the same as above step I have output corresponding to (0.024, 0.02435, 0.02456). Just like that, I have the output of the 8th order. I want to use Point collocation to calculate Mean and deviation of my problem.
In here, I don't know the function for relative between the Input parameter and Output It is only from experiment process.
I hope you can give me the advice for my problem. 

Thank you very much

**Comment by jonathf** [comment]
I am not sure what you mean by 3rd and 8th order. You will have to explain that if you want me to comment on it.

As for calculating mean and variance from respectively 2 and 3 experimentally observed response values, that can be done as follows:
```
nodes = np.array([0.9, 1.0, 1.1])
evaluations = np.arrray([0.024, 0.02435, 0.02456])
distribution = cp.Uniform(0.9, 1.1)
polynomials = cp.orth_ttr(1, distribution)
proxy_model = cp.fit_regression(polynomials, nodes, evaluations)
mean = cp.E(proxy_model, distribution)
variance = cp.Var(proxy_model, distribution)
```
For 2-3 samples, I would not use polynomial order above 1.

**Comment by nguyenhoaiThanhbk2811** [comment]
Hi you,
Order means the degree of the polynomial. I want to generate Sampling with 1000 experiment. and Then I plot the histogram between evaluations of 100 experiment and frequency of it. but I only have:
case 1: with nodes (0.9,1.1) corresponding to (0.024,0.02456)  evaluation. I will generate 1000 experiment to have 1000 evaluation. And calculate mean and variance of its.
case 2: with nodes (0.9, 1.0, 1.1) corresponding to (0.024, 0.02435, 0.02456) evaluation. I will generate 1000 experiment to have 1000 evaluation. And calculate mean and variance of its.

thank you.

**Comment by nguyenhoaiThanhbk2811** [comment]
I have an idea for case 1:

distribution = cp.Uniform(0.9, 1.1)
samples = distribution.sample(100, "H")

distribution2=cp.Uniform(0.023991,0.0244017)
samples2=distribution2.sample(100,"H")

polynomial_expansion = cp.orth_ttr(1, distribution)
approx = cp.fit_regression(polynomial_expansion, samples, samples2)
expected = cp.E(approx, distribution)
variance = cp.Var(approx, distribution)

Is it okay?

**Comment by jonathf** [comment]
I am not sure what you are trying to accomplish here, so my comments under might not fit your need. But I give it a shot.

The distributions do contain analytical statistical moments, so you can do as follows:
```
expected = cp.E(distribution2)
variance = cp.Var(distribution2)
```
No errors.

When you talk about "corresponding", you kind of have to make sure that your input and output correspond. If that is the case, I would change your forth line to:
```
samples2 = distribution2.fwd(distribution.inv(samples))
```
This way you do not rely on the deterministic nature of  `rule="H"` to do your calculation.

If you want to create a histogram from `approx`, you can create samples from it as follows:
```
samples3 = distribution.sample(1000)
samples4 = approx(*samples3)
```

Hope this is helpful.

**Comment by nguyenhoaiThanhbk2811** [comment]
I think you right. Because the variable of Distribution1 is corresponding to Distribution2. But with my idea then it is not corresponding each other. I have tried to with your comment:

 _#creat the sampling for input
_distribution1 = cp.Uniform(0.9,1.1)
samples1=distribution1.sample(100)_
#creat the output
distribution2 =cp.Uniform(0.023991,0.0244017)
samples2 = distribution2.fwd(distribution.inv(samples))
print (samples2)_

perhaps it is not working for the code _samples2._

My problem is how to generate the output that has to correspond to input. With random variable of input about (0.9,1.1) and I also have an output (0.023991,0.0244017). 

Example: With sample(10)  I have ten values for input and ten values for output but they have to correspond to input and output. And then I will calculate "approx" and mean and variance.

But my problem is I don't know how to find the output satisfying conditions above "correspond" when I don't know the function of input and output. I only have the value of out throughout experiment. But I can not do 100 or 1000 experiment to find the output.

**Comment by jonathf** [comment]
Sorry, my code was incorrect. The right line is:
```
samples2 = distribution2.inv(distribution.fwd(samples))
```
How does that work?

**Comment by nguyenhoaiThanhbk2811** [comment]
with my process 

"_import chaospy as cp
import numpy as np
import matplotlib.pyplot as plt

nodes = np.array([0.9083, 1.0, 1.0917])
distribution = cp.Uniform(0.9, 1.1)
evals = np.array([0.023991,0.0235877,0.0244017])
polynomial_expansion = cp.orth_ttr(2, distribution)
approx = cp.fit_regression(polynomial_expansion, nodes, evals)
expected = cp.E( approx, distribution)
variance = cp.Var(approx, distribution)
deviation = cp.Std( approx, distribution)
print (expected)
print(deviation)_"

Now ,I have a  approx equation. How to create the 1000 Sample to have 1000 node value and have corresponding to 1000 evals value. And then I can create a histogram from approx.

Thank you

**Comment by jonathf** [comment]
Something like this?
```
samples = distribution.sample(1000)
evaluations = approx(samples)
plt.hist(evaluations)
```

**Comment by nguyenhoaiThanhbk2811** [comment]
Hi you,
Now I want to use the point collocation for multiple variable inputs. I have been writing the code as follows.
import chaospy as cp
import numpy as np
import matplotlib.pyplot as plt

nodes1 = np.array([0.9083, 0.91 , 0.92, 0.93, 1.0, 1.032, 1.058,1.065, 1.087, 1.0917])
nodes2 = np.array([49, 49.5, 49.7, 50 , 50.2, 50.4, 50.6, 50.7, 50.8, 51])
nodes3 = np.array([0.3,  0.4, 0.45,  0.5,  0.55,  0,.6 , 0.7, 0.8, 0.85, 0.9])

distribution = cp.J(cp.Uniform(0.9, 1.1), cp.Uniform(49 51),cp.Uniform( 0.3, 0.9))

evals = np.array([0.023991,  0.024, 0.0231, 0.0222, 0.02541, 0.0258, 0.0235877, 0.0232, 0.0224, 0.0244017])

polynomial_expansion = cp.orth_ttr(2, distribution)
approx = cp.fit_regression(polynomial_expansion, ??? , evals)

**# (how to I can identify the approx)**

expected = cp.E( approx, distribution)
variance = cp.Var(approx, distribution)
deviation = cp.Std( approx, distribution)
print (expected)
print(deviation)

samples = distribution.sample(1000)
evaluations = approx(samples)
plt.hist(evaluations,normed = True, bins =50)
plt.show()

In the approx  I don't How to I can calculate approx equation in this case? 
please give me the advice.

Thank you.

**Comment by jonathf** [comment]
How about `nodes = np.vstack([nodes1, nodes2, nodes3])`?

**Comment by nguyenhoaiThanhbk2811** [comment]
Hi you,
When I use the node = np.vstack ([nodes1,nodes2,nodes3]) then I can calculate the mean value. But This time the samples are a matrix has 3 three rows. I use the command:

 **samples = distribution.sample(100,"L")
evaluations = approx (samples)
plt.hist(evaluations)
plt.show()**

It is can not plot the histogram.

this is my code:

**import chaospy as cp
import numpy as np
import matplotlib.pyplot as plt

nodes1 = np.array([0.9083, 0.9, 0.9, 0.91 , 0.91, 0.92, 0.92, 0.93, 0.92, 0.93, 1.0, 1.0, 1.032, 1.04, 1.058, 1.065, 1.072, 1.087, 1.088,1.0917])
nodes2 = np.array([49, 49.2, 49.4, 49.5, 49.7, 50, 50, 50.06, 50.2, 51, 50.1, 50.25, 50.2, 50.4, 50.6, 50.7, 50.8, 50.9,51, 51])
nodes3 = np.array([0.3, 0.31, 0.0312, 0.0313 , 0.4, 0.45, 0.451, 0.412, 0.5, 0.512, 0.521, 0.55, 0.6, 0.7512, 0.6251, 0.622 , 0.7, 0.8, 0.85, 0.9])


distribution = cp.J(cp.Uniform(0.9, 1.1), cp.Uniform(49, 51), cp.Uniform( 0.3, 0.9))

nodes = np.vstack([nodes1, nodes2, nodes3])

evals = np.array([0.023991, 0.024, 0.0231, 0.0222, 0.02541, 0.0258, 0.0235877, 0.0232, 0.0224, 0.0244017, 0.0245, 0.02356, 0.0245, 0.0226, 0.02365, 0.0214, 0.0255,0.02145,0.0231,0.0258])
polynomial_expansion = cp.orth_ttr(1, distribution)
approx = cp.fit_regression(polynomial_expansion, nodes, evals)
expected = cp.E( approx, distribution)
variance = cp.Var(approx, distribution)
deviation = cp.Std( approx, distribution)
print (expected)

samples = distribution.sample(100,"L")
evaluations = approx(samples)
plt.hist(evaluations)
plt.show()**

Do you know how to plot the histogram in the have multiple variables?

Thank you

**Comment by jonathf** [comment]
Try `approx(*samples)`.
