### ISSUE TITLE
Problem with nodes generation

### ISSUE THREAD

**Issue by chomikzimon** [jonathf/chaospy#93]
Hi!

Thank you for your great code. I use it a lot in my projects.

I have a quick question regarding the non-intrusive polynomial chaos approach using quadratures. I need to generate samples for high polynomial order - above 25. However, when I run e.g.
`nodes, weights = generate_quadrature(29, dist, rule='G')`, 
the number of nodes is smaller than expected:
`np.size(nodes) = 26`.
Could you let me know what's happening?

Thank you for your help!
Gosia

**Comment by jonathf** [comment]
Good question. I am unable to reproduce using standard random variables. Do you mind providing the distribution you used?

**Comment by chomikzimon** [comment]
Hi!
Thank you for your quick response. Actually just the following basic distribution is causing problems:
```
from numpy import shape
from chaospy import generate_quadrature, Normal
dist = Normal(0, 1)
nodes, weights = generate_quadrature(29, dist, rule='G')
shape(nodes)
```

**Comment by jonathf** [comment]
Indeed you are right.

I've made a fix. If you install Chaospy from the git branch `development`, you should be able to use the fix right away.

**Comment by chomikzimon** [comment]
Thank you!

**Comment by chomikzimon** [comment]
Hi!
I am sorry for going back to this. I installed Chaospy from the development branch and I still seem to be having the same problem. Should I obtain the code from a different branch?
Thank you,
Gosia

**Comment by jonathf** [comment]
No, branch `development` is correct. I just ran your example, and it prints out `(1, 30)` on my machine.

Have you done `git checkout development; git pull` to ensure the branch is up to date?

**Comment by chomikzimon** [comment]
I did. My branch is up to date with 'origin/development'. And it still doesn't work for me. I must be doing something wrong. I will remove the Chaospy and install again.
