### ISSUE TITLE
Calculate Expectation on the square root of orthogonal polynomial basis function

### ISSUE THREAD

**Issue by cc636489** [jonathf/chaospy#94]
Hello!

Could we calculate the expectation value on square root of orthogonal polynomial chaos basis? Something like: 
         cp.E( sqrt( orth[1]*orth[2] ) * orth[4] ,  jointCDF)

Thanks for the great code by the way, it helps a lot indeed!

**Comment by jonathf** [comment]
Unfortunately, no.

However the polynomials does vectorized evaluation, so it is possible to get a pretty good approximation using Monte Carlo simulation. Something like:
```
samples = jointCDF.sample(large_number)
numpy.mean(numpy.sqrt(orth[1](*samples)*orth[2](*samples)) * orth[4](*samples))
```

Thank you for your kind words.

**Comment by jonathf** [comment]
No problem.
