### ISSUE TITLE
How to calculate Sobol index in Point-colocation-method?

### ISSUE THREAD

**Issue by nguyenhoaiThanhbk2811** [jonathf/chaospy#99]
Hi you,
How to calculate Sobol index in Point colocation method?
My problem:
+3 random parameters with Normal distribution.

thank you

**Comment by jonathf** [comment]
Hey!

Have you tried taking a look at `chaospy.Sens_m` (first order main sensitivity), `chaospy.Senn_m2` (second order main sensetivity) and `chaospy.Sens_t` (total sensetivity)?

**Comment by nguyenhoaiThanhbk2811** [comment]
Hi you.
This is my code. How to calculate Sobol index of  the variables (nodes 1,nodes 2, nodes 3)
example: nodes 1 = 0.995246, node 2=0.002971, node 3 =0.001791
This is a result when I use the scilab for UQ.
You can help me how to calculate sobol index within the nodes.
Thank you very much

> import chaospy as cp
import numpy as np
import matplotlib.pyplot as plt

> nodes1 = np.array([0.05673,0.06495,0.06387,0.05776,0.06468,0.05865,0.06529,0.06145,0.054427,0.05699,0.062805,0.060559,0.058559,0.060739,0.057265,0.05995,0.055746,0.0624327,0.057555,0.054536,0.060224,0.054846,0.062055,0.065653,0.0636225,0.062915,0.058249,0.057887,0.064002,0.0550871,0.062141,0.065405,0.054342,0.057428,0.0592801,0.060889,0.061055,0.0644627,0.059531,0.056463,0.065995,0.062291,0.064369,0.055919,0.059471,0.05797948,0.059116,0.058809,0.064151,0.063223,0.061752,0.059709,0.0626428,0.0544942,0.065003,0.0583102,0.056076,0.055276,0.065799,0.05416229,0.0635202,0.0604489,0.055603,0.061691,0.0612995,0.0555371,0.06340495,0.056806,0.06004907,0.056359])
nodes2 = np.array([1.0604,1.057,1.0961,1.04826,0.9419,1.0108,0.94967,0.95404,0.934353,0.92986,1.01186,1.0171,0.93406,0.9091749,0.97495,1.04084,1.08877,0.9485,1.07825,0.989146,0.96316,0.90367,1.00594,1.024436,1.07331,0.9386,1.08003,0.9844,0.9545,1.0264,1.0336,1.05911,0.9206,1.09965,0.99987,1.00183,1.0646,1.05117,1.0703,0.9597,1.0443,0.91243,0.90216,1.02054,0.94373,0.96864,0.9865,1.05395,0.90688,1.093135,1.03023,0.92385,0.928027,0.96212,0.99694,0.97726,1.07577,1.0042,0.917438,1.0846,0.96597,1.037998,1.08793,0.993397,0.98063,1.03522,0.971917,1.06788,1.01864,0.91479,])
nodes3 = np.array([47.2077,46.946,50.4957,49.6127,53.7066,46.3901,49.8155,46.4507,51.0172,49.5674,51.3808,51.5939,48.5126,53.7584,54.9941,52.0027,45.5259,49.1831,46.6636,49.0727,49.9844,52.3181,53.3407,47.7143,50.7756,54.658,45.2127,50.4137,52.1962,51.2629,47.8578,48.8532,47.3787,45.7184,52.6667,54.7167,51.4339,51.984,45.6214,51.8309,54.4398,54.2475,52.84,50.593,54.08737,52.9997,46.2201,47.0793,48.3998,48.1503,48.0671,53.037,53.9088,53.4974,45.9251,48.5799,47.4953,54.3871,53.1727,52.5146,50.9876,50.04822,46.0117,46.8049,49.3075,50.173,45.3663,48.9281,45.0681,47.6711])


> distribution = cp.J(cp.Uniform(0.054, 0.066), cp.Uniform(0.9, 1.1), cp.Uniform( 45, 55)) # (ca2,ce1,ce2)
nodes = np.vstack([nodes1, nodes2, nodes3])
evals = np.array([0.00399515,0.00398227,0.00394473,0.00399177,0.00428289,0.00402384,0.00425382,0.00425516,0.00435983,0.00438203,0.00399536,0.00399769,0.00435985,0.00447336,0.00411729,0.00398211,0.00398573,0.00427101,0.00398547,0.00407801,0.00419411,0.00452373,0.00399431,0.00399516,0.00395894,0.00430193,0.0039868,0.00408894,0.00422265,0.00400649,0.00399906,0.00397117,0.00444291,0.0039759,0.00400788,0.00399548,0.00396765,0.00396634,0.00398908,0.00421659,0.00395789,0.00445051,0.00450565,0.00400982,0.00428402,0.00416113,0.0040897,0.00399587,0.00449611,0.00395744,0.00400107,0.00439792,0.00436135,0.00420427,0.00403154,0.00412564,0.00398687,0.00400764,0.00441344,0.00396947,0.00416698,0.00398991,0.00398469,0.00405197,0.00410021,0.00400324,0.00416019,0.00398405,0.00402102,0.00447441])
polynomial_expansion = cp.orth_ttr(4, distribution)
approx = cp.fit_regression(polynomial_expansion, nodes, evals)
expected = cp.E( approx, distribution)
variance = cp.Var(approx, distribution)
deviation = cp.Std( approx, distribution)

> sobol_1 = cp.Sens_m(polynomial_expansion,distribution)
print (sobol_1)
print (expected)
print(deviation)
samples = distribution.sample(10000,"L")
evaluations = approx(*samples)
plt.hist(evaluations,bins = 80, rwidth =0.75, color = 'b')
plt.show()

**Comment by jonathf** [comment]
Have you tried replacing sobol creation line with the following?
```
sobol_1 = cp.Sens_m(approx, distribution)
```
